### ISSUE TITLE
Final legal things from The Atlantic

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#1001]
The legal folks have sent two more things we need to implement, if anyone is around:

- Privacy Policy link ([linking to this page](https://www.theatlantic.com/privacy-policy/))
- Copyright notice: CovidTracking.com Copyright (c) 2020 by The Atlantic Monthly Group. (CC BY-NC 4.0))

I am not a lawyer, but I would like that copyright thing to link to our licence, please.

Many thanks.

**Comment by schwartzadev** [comment]
Should the privacy policy be a footer link?

**Comment by kissane** [comment]
Yes, please, @schwartzadev !
