### ISSUE TITLE
Update the footer design now that it’s got more links in it

### ISSUE THREAD

**Issue by tealtan** [COVID19Tracking/website#1009]
<img width="1631" alt="Screen Shot 2020-06-08 at 9 31 27 PM" src="https://user-images.githubusercontent.com/293844/84096229-6a99a500-a9cf-11ea-9887-3baf3aa21f8e.png">

Has a few more links and an attribution added recently, we should update the design here to fit things better.

**Comment by burhanuday** [comment]
![image](https://user-images.githubusercontent.com/25934701/84103952-fdeccd80-aa03-11ea-99fd-edf14b1124ed.png)

Something like this with three columns - The CovidTracker logo, important links and social

I would like to do this if it is unassigned

**Comment by schwartzadev** [comment]
Related: #1010 will fix the current link color in the copyright section

**Comment by tealtan** [comment]
Thank you @burhanuday! But I think we will need to take an extra beat to work out the organization and design first.

**Comment by jhuashao** [comment]
I can take on the design aspects for this ticket! will post a quick redesign of this soon

**Comment by jhuashao** [comment]
### Finalized Footer Design

<img width="1661" alt="Screen Shot 2020-06-16 at 1 06 53 PM" src="https://user-images.githubusercontent.com/24916540/84806100-2f046980-afd3-11ea-97da-f63b5f033a93.png">


v3 Refresh FIGMA FILE FOR ASSETS, SPECS, AND REFERENCE***](https://www.figma.com/file/GwkYSPVlTkdgLyGNgeMrLz/v3-Refresh?node-id=47%3A1797)

Attached above gives detailed visual guidance on what the footer should look like at 1440, 782, and 375 breakpoints. Assets (icons, logos, etc) are also located in the 'final draft' area of the v3 Refresh Figma file as well. 

<img width="1197" alt="Screen Shot 2020-06-16 at 1 12 07 PM" src="https://user-images.githubusercontent.com/24916540/84805980-109e6e00-afd3-11ea-88a0-3139e2bb8bf0.png">
<img width="661" alt="Screen Shot 2020-06-16 at 1 12 20 PM" src="https://user-images.githubusercontent.com/24916540/84805987-12683180-afd3-11ea-8718-9337c632bd26.png">
<img width="351" alt="Screen Shot 2020-06-16 at 1 12 29 PM" src="https://user-images.githubusercontent.com/24916540/84805997-14ca8b80-afd3-11ea-99f7-467ab2202956.png">

**Comment by kevee** [comment]
Closing per #1063
