### ISSUE TITLE
Update traceSVG colors

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1018]
Right now, we trace all of the image fluids with the same color: #A7DEF6. Let's be a little more intentional about which color we choose for each image so the trace color roughly corresponds to the image color.

- [ ] `src/components/pages/homepage/datasets.js:12`
- [ ] `src/components/pages/homepage/datasets.js:20`
- [ ] `src/components/pages/homepage/large-dataset.js:13`
- [ ] `src/components/pages/homepage/large-project.js:15`
- [ ] `src/components/pages/race/header-hero.js:15`
- [ ] `src/pages/about-data/visualization-guide/index.js:299`

**Comment by kevee** [comment]
Good idea, @schwartzadev! I marked this as a good first issue and am seeing if anyone wants to take it on. Some thoughts:

- [Here's the docs on the traced svg](https://using-gatsby-image.gatsbyjs.org/traced-svg/)
- There's a `threshold` option you can also use with the `traceSVG` GraphQL selector, but I haven't tested it. This might help make the placeholder look more like the original image
- Maybe we should [automatically snag the image color](https://www.gatsbyjs.org/packages/gatsby-plugin-extract-image-colors/), but I also feel like bespoke color selection would be good, especially for the images on dark backgrounds.

**Comment by Melvin-Viana** [comment]
Hi, I created a PR for changing 5/6 of the images. I couldn't find anything on line 299 of : `src/pages/about-data/visualization-guide/index.js:299`
