### ISSUE TITLE
Grid system (depends on units)

### ISSUE THREAD

**Issue by tealtan** [COVID19Tracking/website#1020]
Here’s what we are thinking:

## From 0 to $viewport-md (768px)

- 4 flexible width columns
- 3 fixed width gutters, 1 rem each
- Page container goes full width with 1.5 rem margins ( width: 100% vw - 3 rem )
- Page content by default takes up the same width as the page container (4 cols), some elements may go full-bleed across (100% vw)

## From $viewport-md (768px) to $viewport-lg (1080px)

- 6 flexible width columns
- 5 fixed with gutters, 1 rem each
- Page container goes full width with 3.5 rem margins ( width: 100% vw - 7 rem )
- Page content by default takes up the same width as the page container (6 cols), some elements may go full-bleed across (100% vw)

## From $viewport-lg (1080px) and beyond

- 12 flexible width columns
- 11 fixed with gutters, 1 rem each
- Page container goes full width with 2 rem margins ( width: 100% vw - 4 rem )
- Page content by default takes up less width inside the page container (8/12 cols), some elements may go wider: 10/12 cols, 12/12 cols, or full-bleed across (100% vw)

**Above $viewport-xl (1200px)**

Above this breakpoint, we want the page container to stop growing, something like:
- width: 71.25 rem (1140px)
- max-width: 100% vw - 4 rem (to account for people increasing their browser font size)

**Comment by kevee** [comment]
Implementation notes:

## SCSS Mixin

- [ ] Create a new mixin file at `src/scss/grid.module.scss`. Implement a `row()` and `col()` mixin. [Some inspiration[(http://www.thesassway.com/intermediate/simple-grid-mixins).
- [ ] Column mixin should accept three widths: mobile, middle, desktop, that map to what @tealtan has described above
- [ ] Also allow defining padding to the left/right of a column using our standard spacers as units (also an array, so you can define padding on each of the three defined breakpoints
- [ ] Add the file to `src/utilities/sass-imports.js`

## React components
- [ ] Create new `<Row>` and `<Col>` components

**Comment by kevee** [comment]
I have implemented both a mixin and component for these grids. I also ripped apart our container component and simplified it based on our grid.

The container component was also applying things like font sizes to 'text heavy' pages, which I don't think is the role for that component. So, I created a new 'long-content' component that just bumps the font size a bit.
