### ISSUE TITLE
Clean up state data page link language

### ISSUE THREAD

**Issue by tealtan** [COVID19Tracking/website#1026]
We had a suggestion to change the state links on pages such as [this](https://covidtracking.com/data) and [this](https://covidtracking.com/data/state/alabama):

<img width="532" alt="Screen Shot 2020-06-12 at 12 18 35 PM" src="https://user-images.githubusercontent.com/293844/84523732-d8cbb980-aca6-11ea-9199-9f2256670e5f.png">

to something more inline and removing repeated language:

<img width="584" alt="Screen Shot 2020-06-12 at 12 22 31 PM" src="https://user-images.githubusercontent.com/293844/84524143-7921de00-aca7-11ea-975d-dc31024e678d.png">
<img width="649" alt="Screen Shot 2020-06-12 at 12 22 37 PM" src="https://user-images.githubusercontent.com/293844/84524144-79ba7480-aca7-11ea-8f3f-b98bd4391d9e.png">

Maybe someone can answer whether this change should happen on Contentful or if it is in the template? If it is purely within Contentful then we can go with the option above with the vertical separators, if we have template access then it’d be nice to use the separator dots.

**Comment by kevee** [comment]
This is in the template at `components/pages/state/state-links`. I'm marking this as a first good issue!
