### ISSUE TITLE
Mobile nav focus issues

### ISSUE THREAD

**Issue by tealtan** [COVID19Tracking/website#1028]
Two issues with focus-management on the mobile nav:

- [ ] when the nav expands, the search box gets auto-focused. I think the idea behind this (if I’m remembering Ethan’s note right) was that because the nav items appeared before the [Menu] button in the source order, people using screenreaders would not find them unless they moved back. I think we could still achieve this by shifting focus to the nav items div instead?

- [ ] When opening the sub-menus inside the nav, focus moves on the div containing submenu items - which is good – but @Josh Rubenoff and I noticed that "losing focus" (by tapping anywhere on the screen) would close the submenu. This also has the effect of making it so that tapping on the [Menu] button does not collapse the nav – the "losing focus" thing happens, and you have to tap on the [Menu] button a second time to actually close it.

**Comment by schwartzadev** [comment]
https://github.com/COVID19Tracking/website/pull/1024/commits/f6bd37728014ff7aede288529e8a191ac3f0efa3 partially addressees the auto-focus issue: it stops the search bar from auto-focusing when the nav opens, but does not auto-focus the nav items `ul`

**Comment by kevee** [comment]
CLosing per #1032
