### ISSUE TITLE
Hospitalization column is causing visual collision

### ISSUE THREAD

**Issue by olivierlacan** [COVID19Tracking/website#103]
On: https://covidtracking.com/data/

![image](https://user-images.githubusercontent.com/65950/77237158-1afbc800-6b9c-11ea-9a9c-e8fbf47379f4.png)

We probably need to rework the way we set up the grid since it's now overflowing.

**Comment by schwartzadev** [comment]
I'll work on this. It's cut off on mobile as well:
![image](https://user-images.githubusercontent.com/18607205/77238071-0e26a680-6b93-11ea-8427-ec7333ace3f9.png)
