### ISSUE TITLE
Add more detail to the RSS feed

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1071]
This issue builds on #1066 and #1069.

Note that the RSS feed currently only exists in the `schwartzadev/add-rss` branch.

[Here's a helpful guide for adding the RSS feed](https://www.gatsbyjs.org/docs/adding-an-rss-feed/)

## Add authors

Currently we handle names of authors in the `byline.js` file in the blog components and in the `list-spacer.js` file in the utils components directory.

This entails:
- [x] Abstracting the list spacer logic to a file in `/utilities` (probably retain the same logic, but stop using components
- [x] Updating the `byline.js` file to use this abstraction
- [x] Add an author tag to the RSS, (see #1069 for reference) and use this abstraction

([the author spec is here](https://validator.w3.org/feed/docs/rss2.html#ltauthorgtSubelementOfLtitemgt))

##  Add the CTP Image to the channel
- [x] [Documentation here](https://validator.w3.org/feed/docs/rss2.html#ltimagegtSubelementOfLtchannelgt)

**Comment by kevee** [comment]
Authors was fixed in #1158

**Comment by schwartzadev** [comment]
Thank you @PhastPhood @JasnaMRB @kevee for the team effort on this one!
