### ISSUE TITLE
Antircism Center link is broken because  of their SSL certificate

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/website#1072]
Maybe we can link to https://www.bu.edu/antiracist-center/ until the issue is resolved?

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_24wup)

**Comment by schwartzadev** [comment]
I assume this is the link in the first paragraph on https://covidtracking.com/race/about .

If that is the case, I updated the link in Contentful.

**Comment by muamichali** [comment]
Thanks, Andrew!
