### ISSUE TITLE
"Last updated (ET)" times are -4 hours wrong on data pages

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/website#1075]
On https://covidtracking.com/data and on state pages such as https://covidtracking.com/data/state/delaware there are "Last updated" times underneath each state's main data table, and all of them seem to be 4 hours behind what they should be. Delaware's time zone is Eastern, for example, and according to [our spreadsheet](https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vRwAqp96T9sYYq2-i7Tj0pvTf6XVHjDSMIKBdZHXiCGGdNC0ypEU9NbngS8mxea55JuCFuua1MUeOj5/pubhtml#) its last update time in Eastern was 6/20 18:00 (see both States Current and States Daily). But the data pages report its last update time as 6/20 at 14:00 (i.e., 2pm). Same is true for all other states I've spot-checked. 
<img width="688" alt="Screenshot 2020-06-22 08 31 27" src="https://user-images.githubusercontent.com/227453/85288196-5cce3000-b463-11ea-88a9-083625ace9d4.png">

I also think it would be clearer if that timestamp were labeled something like "State's reported update time" and the one in the blue box were labeled something like "This page last synced with our spreadsheet."

**Comment by schwartzadev** [comment]
My first thought is that we're using UTC instead of Eastern time for these times, but I'll poke around some more!

**Comment by schwartzadev** [comment]
Yep! It looks like in the case of Delaware, we're posting the UTC time: `2020-06-19T18:00:00Z`. I'll have a fix up soon.

**Comment by kevee** [comment]
The blue box is also the last time the API updated, which can be things like CRDT dashboard or volunteer lists updating.
