### ISSUE TITLE
Sort/filter for state pages

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#108]
I would love to see a feature to jump to a particular state from the `/states/` page. I've used [chosen](https://harvesthq.github.io/chosen/) before, which allows for both entering text to search and for choosing from a dropdown.

Something similar would be great. I'm curious to hear others' thoughts.

**Comment by kevee** [comment]
I think this is a great idea, as the data page is pretty long. 

`<off-topic-ish>`
Looking at #59, and #100, I think we're going to have a pretty big rethink coming soon in terms of how the site is structured, and what JS we want to add to pages. In context of both of these things, should we back up just a little bit and think about what our longer-term approach to client-side code should be. There's lots of different approaches in terms of build pipelines, frameworks, etc and I think having that conversation and settling on a solution now will help prevent costly refactors later.
`</off-topic-ish>`

**Comment by schwartzadev** [comment]
#114 partially addresses this -- `master` now has navigation

**Comment by kevee** [comment]
Rolling into requirements doc and closing
