### ISSUE TITLE
Double border on tables

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#109]
This was my doing and should be the literal last priority.

----

The horizontal top and bottom borders are half as thick as the vertical ones. They should be twice as thick as they are now. (They should match the thickness of the vertical right and left borders.)

![image](https://user-images.githubusercontent.com/18607205/77242930-7a240180-6bc9-11ea-8af2-e15039d82c53.png)

Here's a close-up:

![image](https://user-images.githubusercontent.com/18607205/77242929-75f7e400-6bc9-11ea-97fc-82a02449af2d.png)

The top and bottom borders should be just as thick the rest of the table.

A fun game of hide-and-go-seek in CSS if anyone is up for it :)

**Comment by beep** [comment]
👋 Hey @schwartzadev, just checking: will this issue still be relevant once v2 launches?

**Comment by schwartzadev** [comment]
I don't think so -- thanks for following up 👍
