### ISSUE TITLE
Link to our best practices document

### ISSUE THREAD

**Issue by hammer** [COVID19Tracking/website#11]
https://docs.google.com/document/d/1OyN6_1UeDePwPwKi6UKZB8GwNC7-kSf1-BO2af8kqVA/edit

**Comment by kissane** [comment]
https://github.com/COVID19Tracking/website/pull/22

**Comment by kissane** [comment]
OK, I cleaned this up and annotated it lightly, it's at the bottom of the homepage, we'll find a better place for it in v2 if necessary.
