### ISSUE TITLE
About page redesign

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#1103]
[Figma file](https://www.figma.com/file/GwkYSPVlTkdgLyGNgeMrLz/v3-Refresh?node-id=472%3A6459)

Change `/src/pages/about-project/index.js` to:

- [x] Remove `narrow` from layout so the contributor container is wider
- [x] Wrap the contentful content up top and bottom with containers with `narrow` props
- [x] Change the contributors section to 6 cols on large breakpoints, 2 on medium, and 1 on small.

**Comment by schwartzadev** [comment]
Closed by #1119
