### ISSUE TITLE
Paginate blog posts

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1120]
As we get the blog running more, we should create infrastructure to paginate our blog post pages

Let's:
- [x] Add a blog page template (see the blog category template for a starting point)
- [x] Create a design for navigating between blog pages
- [x] Choose the number of posts per page (@kevee: any suggestions?) and use GraphQL to configure

**Comment by tiagofsanchez** [comment]
@schwartzadev I started with this and created a new blog page template `blog-list-template` and working on [tfs/blog-pagination](https://github.com/COVID19Tracking/website/tree/tfs/blog-pagination) branch.
