### ISSUE TITLE
About page: shrink the supported by image

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1125]
This image on [the about page](https://covidtracking.com/race/about) used to be smaller, but seems to have grown recently!
![image](https://user-images.githubusercontent.com/18607205/85931123-38b58900-b87f-11ea-962d-7aabd29db93f.png)

Let's reduce the image size to be ~350px.

**Comment by kevee** [comment]
Added `?w=350` to image URL in contentful.
