### ISSUE TITLE
Add Peter Walker’s Tableau charts on their own page

### ISSUE THREAD

**Issue by tealtan** [COVID19Tracking/website#1132]
Based on previous discussion with Júlia Ledur and Peter Walker:

They’d like to add Peter’s charts to its own page on the CTP site:
https://public.tableau.com/profile/covid.tracking.project#!/vizhome/CTPGallery/0_Gallery

They have quite a bit of detail and functionality that is useful for experts using this data, so these are power user tools compared to the charts being made for the state pages.

The charts would be organized by 4 categories: (condensed compared to the 5 columns in the link above)
- US Overall
- US Regions
- State Comparisons
- Single-State

---

There are some open questions re: implementation, with an eye towards speed:

- **The quicker path:** the entire set of charts, incl. the chart category navigation, could be added as a single Tableau embed.
- **The longer path:** the site handles the category navigation, which can load individual Tableau embeds. This may be more desirable but if we did this, we’d want to allow Peter and Júlia the flexibility to rename or add new embeds, so would need to build in some CMS control.

**Note about the Tableau chart sizes:** I asked Peter to reformat the charts to a 1000px by 500px size, so that it fits within the 1080px and above breakpoint. (We discussed making them responsive, but this seems to be not a well-supported option by Tableau.) This seems fine for now given the limited power user audience (we can expect everyone to have a desktop at some minimum size).

**Site nav location:** I’m all ears re: where we can put this and what to call it – probably something under Our Data?

**Comment by kevee** [comment]
Since I've already figured out wrangling Tableau's charts, I can get on this quickly. I'm going to:

- [ ] Add a new content type for Charts in Contentful - I'm going to keep them generic in case we want to add more than Tableau charts later
- [ ] Accept fields title, description, category, chart ID, and accessible description
- [ ] We can list them out on a page. We might need some design work on this

**Comment by tealtan** [comment]
Awesome! Since we are good w/ handling the chart nav on the site directly, @julialedur and I can look at the design part of it.

**Comment by tealtan** [comment]
Designs are here!
https://www.figma.com/file/GwkYSPVlTkdgLyGNgeMrLz/v3-Refresh?node-id=715%3A1724
