### ISSUE TITLE
State and US overview chart issues

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#1137]
- [x] [WY](https://feature-state-data-charts--upbeat-lovelace-3e9fff.netlify.app/data/state/wyoming), [SC](https://feature-state-data-charts--upbeat-lovelace-3e9fff.netlify.app/data/state/south-carolina), [Georgia](https://feature-state-data-charts--upbeat-lovelace-3e9fff.netlify.app/data/state/georgia), [Hawaii](https://feature-state-data-charts--upbeat-lovelace-3e9fff.netlify.app/data/state/hawaii), [DC](https://feature-state-data-charts--upbeat-lovelace-3e9fff.netlify.app/data/state/district-of-columbia), [Puerto Rico](https://feature-state-data-charts--upbeat-lovelace-3e9fff.netlify.app/data/state/puerto-rico) All have negative numbers in the new test column. 
- [x] [American Samoa](https://feature-state-data-charts--upbeat-lovelace-3e9fff.netlify.app/data/state/american-samoa) Deaths and Cases should just have a warning saying there is no data.
- [x] [Florida](https://feature-state-data-charts--upbeat-lovelace-3e9fff.netlify.app/data/state/florida) We should hide any chart that has null data for over 30% of days.
- [x] [Hawaii](https://feature-state-data-charts--upbeat-lovelace-3e9fff.netlify.app/data/state/hawaii), [Idaho](https://feature-state-data-charts--upbeat-lovelace-3e9fff.netlify.app/data/state/idaho), [Kansas](https://feature-state-data-charts--upbeat-lovelace-3e9fff.netlify.app/data/state/kansas) Has a blank hospitalization chart

**Comment by ckelly17** [comment]
Seems to be a national shadow on the per 1M figures
![image](https://user-images.githubusercontent.com/10016217/86030262-3def1100-ba02-11ea-9e4e-2e2c6aba657c.png)

**Comment by kevee** [comment]
@ckelly17 I think we want that in there so you can compare numbers to US.

**Comment by ckelly17** [comment]
nevermind - carry on! That's what I get for not reading closely

**Comment by olivierlacan** [comment]
If it can help for verification here are the charts I make from FDOH (Florida) data (the same data we use mostly): 
![image](https://user-images.githubusercontent.com/65950/86033688-59104f80-ba07-11ea-9e68-6d2fa90e86ff.png)
