### ISSUE TITLE
Grid System - 100% width in first & last child is different that middle children

### ISSUE THREAD

**Issue by goleary** [COVID19Tracking/website#1141]
because there is no left/right padding in the first/last child columns of a row if you have inner content that is 100% width it will differ in size from the cols that are not first/last.
https://www.loom.com/share/0cc769507ac74a2889646ab4cfe75a1f

**Comment by kevee** [comment]
Right, there is an explicit padding of 8 units on our columns on all viewports. You can override this by explicitly setting `paddingLeft` to `[0, 0, 8]` so there's no left padding on small or medium breakpoints.

We can either:

- Set a padding of 0 on full-width grid elements (4, 6, and 12)
- Set no padding on columns and ask the implementation to state the padding (like what [reflexbox](https://rebassjs.org/reflexbox/) does)

**Comment by goleary** [comment]
ok, i'll play around with some options to resolve the alignment issue with the charts when I get a chance.

**Comment by tiagofsanchez** [comment]
Thank you for this - @kevee I did the paddingLeft [0,0,8] and it worked for the [PR I have made](https://github.com/COVID19Tracking/website/pull/1133).

**Comment by goleary** [comment]
my fix for this introduced a new issue:
![image](https://user-images.githubusercontent.com/16123225/87090389-bc129b00-c1ec-11ea-94ec-f6af96b9e17d.png)
(no space between notes and the next chart title).
I tried hardcoding the `left/rightPadding`
```
    paddingLeft: [0, 8, 8],
    paddingRight: [0, 8, 8],
```
but because of [this line](https://github.com/COVID19Tracking/website/blob/7035903b6714d0246372a2d2ed01f1cf07bb3f7d/src/components/common/grid.module.scss#L12) I'm back where I started (with the charts taking up different width/heights depending on which column they're in).

Before I go changing anything about the grid system, I'd like to get your opinion @kevee. I could wrap the charts with a `div` within the `Col` component to solve my problem but it feels like I shouldn't be fighting against the Grid system in this way.  Do you have any other suggestions on how to get around this?
