### ISSUE TITLE
State charts incomplete data warning text change

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#1154]
https://covidtracking.com/data/state/tennessee

"Tennessee does not report data on current COVID-19 hospitalizations." is actually not true. It should be "Tennessee has not report data on current COVID-19 hospitalizations for at least 30% of the past 90 days."

Twitter immediately noticed, I should have spotted the problem earlier. SORRY.

**Comment by kevee** [comment]
Fixed in #1155
