### ISSUE TITLE
Investigate site build tool

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#116]
As the very important work of #59 continues, along with PRs that include client-side code like #100, it's clear that we need a plan for the technical backend of the site. This is an issue to discuss options for either refactoring the existing Eleventy site, or move to another tool. 

**Technical requirements**

- **Accessible** - People with a wide variety of technologies (mobile, slow connections) and abilities should have fast access to information.
- **Available without Javascript** - Client-side code should not be required to access critical information
- **Client-side code management** - Client-side code should be compiled to support external packages and modules.
- **Easily documented** - Comes with a clear set of coding and style guides.
- **Editable** - Static should be easily editable with Markdown.
- **Data integration** - Easily integrates with existing APIs.
- **Static** - A static site with no backend to manage/go down.
- **Developer experience** - Uses technology that is widely available, and has low barriers to entry.

**Options**

- Refactor on Eleventy
- Move to Gatsby
- Move to another site generator

**Comment by goleary** [comment]
Gatsby seems to meet the requirements and from my perspective (working on #presentation / data viz) a lot of what I've done on my [personal dashboard](https://covid19-dash.netlify.com/) is done with React/Recharts so would be easy to port if we start working with Gatsby (React).

Having never worked with 11ty before I feel much less productive in the current code base especially while trying to get pretty visualizations to work (both the charting of the data but also transforming data to support the graphs/charts we'd like to create which I think would be easier with a Gatsby plugin).

**Comment by kissane** [comment]
FWIW as ad-hoc website product lead, my deal is I'm fine with anything that keeps us EXTREMELY FAST and VERY STABLE. React is fine for viz, if that is what Jeremia and Júlia (co-leading that effort) can use, please talk to them before you make tech calls, but I want to keep the bulk of the site as basic as possible, we are going to be working with slow connections and crappy old devices so anything that adds complexity has to be managed super hard.

**Comment by olivierlacan** [comment]
And if you need React or any client-side framework, don't use it for the whole site unless you have to. Just use it for pages like visualizations where it's absolutely needed (if it is, not convinced).

**Comment by kevee** [comment]
So in my experience, Gatsby addresses some of these issues because the React template actually renders on site build to flat HTML, so you don't actually need to use JS at all to view the pages.

That's not to say that we need to go to Gatsby. We can address some of the current problems by  some refactoring and adding on other build tools as well.

**Comment by kissane** [comment]
I have had good experiences with Gatsby elsewhere, no bad feels there, and I do hear you (and @webmasterkai) about rendering out the React, I just have scars

**Comment by schwartzadev** [comment]
I would suggest adding support for markdown to the list of technical requirements -- I think its important that people without major technical experience can still easily contribute to the website.

Other than that, I think shifting away from 11ty would be nice but I'm flexible.

**Comment by kevee** [comment]
Added!

**Comment by schwartzadev** [comment]
We should also likely develop a style guide (or at the very least, some standards) for contributors. The main things I am thinking of are:

* standard css sizes (should be scss variables) and when to use them (for font sizes, padding, margins, colors, etc.)
* general common practices
* how scss files are organized in the project

**Comment by kevee** [comment]
Agreed, added "Easily documented" to the requirements.

**Comment by jeremiak** [comment]
Just chiming in here, just the presentation work stream will be able to pretty easily adapt if y'all want to use something Gatsby and React.

In fact, lots of our current volunteers seem more experience with a React based visualization library called "Recharts". We're also totally OK with sticking with 11ty!

In short, both tools would be fine for us and we just ask for a few days heads up so that we can make sure our charts continue to function.

**Comment by kevee** [comment]
After this issue, along with internal discussion with the website team, we are going to implement new designs and mockups within a separate Gatsby branch. We'll then assess whether we have met all our user need and technical requirements before moving forward.
