### ISSUE TITLE
Update color used

### ISSUE THREAD

**Issue by goldfarb** [COVID19Tracking/website#1190]
Update assets to our current color scheme, including:

- [x] The [logo for twitter](https://twitter.com/COVID19Tracking/photo)
- [x] The [background for twitter](https://twitter.com/COVID19Tracking/header_photo)
- [x] The [social card](https://pbs.twimg.com/card_img/1278355880107323392/DMGAETOH?format=jpg&name=medium) that gets used on twitter and the blog.

The social card may be in Figma, though I can not find it at the moment.

Current indigo:

![image](https://user-images.githubusercontent.com/3722037/86554028-7323c380-bf1a-11ea-8922-63078f8ac335.png)

Indigo in need of an update:

![image](https://user-images.githubusercontent.com/3722037/86554393-7a979c80-bf1b-11ea-85b4-6d055074de21.png)

**Comment by schwartzadev** [comment]
[Here's the Figma file!](https://www.figma.com/file/fKUKsYMNw3NLSyIEOI1HKc/v2-refresh?node-id=1828%3A11558)

**Comment by schwartzadev** [comment]
Here are the new share images:

![AT Share Image Indigo (Current)](https://user-images.githubusercontent.com/18607205/86609535-48149080-bf69-11ea-9c4f-ffe056051e2b.png)

![CRDT no logo Indigo (Current)](https://user-images.githubusercontent.com/18607205/86609572-5367bc00-bf69-11ea-9652-85ab25b64d69.png)

**Comment by schwartzadev** [comment]
:ballot_box_with_check: Updated the CRDT share image in contentful

**Comment by schwartzadev** [comment]
@goldfarb could you ping someone who has Twitter access and see if they have a moment to update the icon + bg photo?

- [ ] Update Github logo - @kevee could you maybe do that?

Files, for reference:

Twitter (General) Logo:
![Indigo Twitter Logo](https://user-images.githubusercontent.com/18607205/88215279-a8b5f580-cc18-11ea-8a81-6832bef9bc9f.png)

Twitter Header
![Twitter Header](https://user-images.githubusercontent.com/18607205/88215309-b0759a00-cc18-11ea-8546-1ecb05032ead.png)

**Comment by goldfarb** [comment]
@schwartzadev Asking now!

**Comment by kevee** [comment]
Github org updated

**Comment by goldfarb** [comment]
[Twitter graphics](https://twitter.com/COVID19Tracking) updated

![image](https://user-images.githubusercontent.com/3722037/88229344-9484ef00-cc3e-11ea-8dc8-954faa9819bf.png)
