### ISSUE TITLE
Design: data cards to replace tables

### ISSUE THREAD

**Issue by tealtan** [COVID19Tracking/website#1193]
[Overall proposal for context](https://docs.google.com/document/d/10V8JGuPeRFMmqpGuJXlyEMICjmxQY95fFbm1BVhnIC4/edit#)

Many of the proposed changes are centered around a card-based, rather than table-based design. Tables are great for listing many of the same items over time, for example, our history tables. However, we have many interfaces that are tables with single rows that can be broken out visually. Cards allow us to surface groups of data in order of importance, and give more room to provide context.

In terms of functionality, we’d also want the ability for these cards to include, for each of the numbers:
- notes or caveats about incomplete data
- a note about where the data comes from (is it being calculated / how is it being calculated vs when we are pulling something straight from a gov website)

They would appear on the data landing page and at the top of each state’s data page:

Make each state on the data page a smaller visual unit, with current data broken into distinct visual hierarchies instead of a single table. Each state will have several cards, which help group similar numbers, and provide room for things like visual cues about changes over the past 7 days. We can provide additional details like % of population, or per 10,000 people, and elaborate missing data instead of just displaying “N/A”. These cards will be:

- Cases
- Tests
- Outcomes
- Current Hospitalization
- Cumulative Hospitalization

(See proposal for list of data points within each card)

**Comment by tiagofsanchez** [comment]
@tealtan I have put [this](https://www.figma.com/file/FxVk3lXqSSe2W3CUek3lNA/tfs%2Fcovidtracking%2Fcard-design-proposal?node-id=0%3A1) together on Figma. 

What do you think?
