### ISSUE TITLE
Design: persistent nav for data pages

### ISSUE THREAD

**Issue by tealtan** [COVID19Tracking/website#1194]
We need a persistent navigation option to jump between states whenever a user is in the /data pages. This navigation should:

- Always appear in the same place
- Allow searching for a state (like our state nav on the data page)
- Provide navigational context (ways to get back to the all-states page, and eventually getting back to the state page from that state’s sub pages.

**Comment by kevee** [comment]
@tealtan I think we have completed this with the current design, except for the search, but I think that might be unneeded.

**Comment by tealtan** [comment]
I agree – with all the states exposed in the persistent nav I think we’re good.

**Comment by kevee** [comment]
OK closing!
