### ISSUE TITLE
Design: state data page

### ISSUE THREAD

**Issue by tealtan** [COVID19Tracking/website#1196]
[Overall proposal for context](https://docs.google.com/document/d/10V8JGuPeRFMmqpGuJXlyEMICjmxQY95fFbm1BVhnIC4/edit#)

State data pages should have:

- [x] - highlight the state grade
- [x] - top level data as cards  #1193 
- [x] - charts for top-line trends
- [x] - include a persistent nav for switching between state data pages #1194
- [x] - full-length history table (using existing table design)
- [x] - include CRDT data
- [x] - link to historical screenshots

---

In the future, we’d want to add additional subpages for further breakdown of data:

- Cases
- Testing
- Hospitalization
- Outcomes

**Comment by kevee** [comment]
@tealtan I converted your list to some checkboxes and it looks like they're all checked! Can we close this?

**Comment by tealtan** [comment]
Yes! Closing.
