### ISSUE TITLE
Data definitions

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#1202]
- [x] Create data-definition environment in Contentful
- [x] Create `dataDefinition` content type in new environment with fields:
  - [x] Name (text)
  - [x] API fieldname (text)
  - [x] Definition (markdown text)
  - [x] API field description (markdown text)
  - [x] Slug
  - [x] CDC related definition? (boolean)
  - [x] CSTE related definition? (boolean)
  - [x] Relationship with state
  - [x] Date range
- [x] Migrate some test content
- [x] Add new page that lists all data definitions
- [x] Add one page per data definition

**Comment by amandafrench** [comment]
Great, thanks — I can provide test content when needed
