### ISSUE TITLE
UX Enhancement: Identify State history more clearly on states page

### ISSUE THREAD

**Issue by kickingvegas** [COVID19Tracking/website#121]
Thanks much to all who are working on this project.

Link to "the recent data broken out by state" on <https://covidtracking.com/us-daily/> goes only to the most recent data per state. Would like to see historical data per state also tracked.

**Comment by kickingvegas** [comment]
Doh. Didn't dig deeper by clicking on the name of the state for the historical data. Perhaps adding text link to more explicitly show history for each state on https://covidtracking.com/data/ ?

**Comment by schwartzadev** [comment]
Looking for input -- (1) or (2) or another course?


![image](https://user-images.githubusercontent.com/18607205/77263769-a9d11900-6c5e-11ea-9c50-3690b8e67dad.png)

**Comment by kickingvegas** [comment]
Thanks for responding! For me, either is fine, although prefer 1 to keep the page concise.
