### ISSUE TITLE
No applications coming from volunteer form

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/website#1220]
We've stopped getting applications from the volunteer form in Slack -- maybe the Zaps broke? There might have been too many. I tried to log in to Netlify to see the form submissions there but I cleared my cache and cookies yesterday when our website was down and now can't log in. I think we use SSO for Netlify but neither `covidtracking.com` nor my ctp email worked, and when I log in with my ctp email my Netlify account is not linked to the ctp site.

**Comment by schwartzadev** [comment]
The last form submission that Netlify has is from 12 days ago. I bet it's something wrong there, not with Zapier.

**Comment by kevee** [comment]
Taking a look, I think these are getting submitted as spam.

**Comment by kevee** [comment]
I did a ticket with Netlify to discuss this.
