### ISSUE TITLE
"New" CRDT Banner

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1223]
The top banner:
> New We just launched the COVID Racial Data Tracker

...went live in the first few days of May, which was over 2 months ago.

Can we discuss:
* Eliminating the banner
* Removing "New" and "just" from the banner language
* Replacing the banner with something else
* Doing nothing

It seems like "New" is no longer appropriate.

**Comment by kevee** [comment]
This is being discussed and I started tracking clicks in Fathom as well.

**Comment by schwartzadev** [comment]
Got it! Feel free to close this in lieu of other discussions @kevee 👍

**Comment by kevee** [comment]
I looped this in website leads, closing.
