### ISSUE TITLE
Remove "confirmed cases" language from home page 

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/website#1227]
Current sub-tag on home page is as follows: `Every day, our volunteers compile the latest numbers on tests, confirmed cases, hospitalizations, and patient outcomes from every US state and territory.` This implies that "Cases" on our web tables is only confirmed cases, which is no longer the case. Suggested revision removes "confirmed": `Every day, our volunteers compile the latest numbers on tests, cases, hospitalizations, and patient outcomes from every US state and territory.`

**Comment by kevee** [comment]
Fixed in https://github.com/COVID19Tracking/website/commit/3c2c6bec68d6d82fea6e941d8e6a3b8d45ef8d56
