### ISSUE TITLE
Horizontal scroll on US Daily for mobile viewports

### ISSUE THREAD

**Issue by olivierlacan** [COVID19Tracking/website#123]
![CEF8B520-9AA2-4BB9-A236-A6206B1D7C1D](https://user-images.githubusercontent.com/65950/77263779-71860680-6c6f-11ea-99b4-dcd9c8d25dab.png)

The table seems to be overflowing in some way.

**Comment by kevee** [comment]
Added a wrapper for large tables that just scrolls horizontally if it's too big for the page. Let me know if this works:

https://deploy-preview-138--upbeat-lovelace-3e9fff.netlify.com/us-daily/
