### ISSUE TITLE
Missing blog post categories on main blog page

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1240]
On the [blog page](https://covidtracking.com/blog/), we don't identify which categories our blog posts are a part of.

Previously, we had something like:

```
CATEGORY | ANOTHER CATEGORY
**Blog Post Title**

Blog lede blog lede blog lede blog lede blog lede blog lede
 blog lede blog lede blog lede blog lede blog lede blog lede
 blog lede blog lede blog lede blog lede blog lede blog lede

By Author Lastname and Author Firstname
```

@tealtan do you have any strong feeling about how (and whether or not) we re-incorporate this element?

**Comment by tealtan** [comment]
Oh yea we definitely should include them! Here they are in the design:
https://www.figma.com/file/GwkYSPVlTkdgLyGNgeMrLz/v3-Refresh?node-id=105%3A1309

**Comment by schwartzadev** [comment]
Sorry I wasn't clear -- I'm hoping to add categories on the blog index page:
![image](https://user-images.githubusercontent.com/18607205/87072430-f7a36a00-c1d8-11ea-9f1e-8bfa50915cf3.png)

I'm not seeing those mocks in the Figma link...are they somewhere else?

**Comment by tealtan** [comment]
Sorry, my fault for not seeing the link in your original comment –

No, I don’t think there’s any reason not to have them on the landing page, I’d say we can add them above the headline (to match with the blog post header) if that works for you?

**Comment by schwartzadev** [comment]
OK, works for me, I'll give it a go soon.
