### ISSUE TITLE
Add update date/time to blog post

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#1242]
To add a tad of transparency, let's add update date/time to blog posts:

- [x] Add an "Update date/time" field to blog posts in Contentful - field `updateDateTime`
- [x] Display on blog page

**Comment by schwartzadev** [comment]
Mock: 
![image](https://user-images.githubusercontent.com/18607205/87096433-0ea98280-c200-11ea-995c-86868626fd3a.png)

**Comment by schwartzadev** [comment]
So far, we don't have any posts that include this field, so I can't get to it in GraphQL yet.
