### ISSUE TITLE
Add subnav border

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1268]
Let us know what the design issue is. Screenshots are helpful!
![image](https://user-images.githubusercontent.com/18607205/87596943-2eccbc00-c6ae-11ea-94f0-d4b29c380062.png)

Hey @tealtan I noticed that the subnav sometimes drops down out of the dark purple section, and user's cant identify where the subnav ends and the page begins.

How do you feel about this:

![image](https://user-images.githubusercontent.com/18607205/87597204-9e42ab80-c6ae-11ea-82ba-19ed2cae17ed.png)

```
.navigation-module--sub-menu--1-S2j {
  outline: solid 2px #31347a;
}
```

**Comment by tealtan** [comment]
Thanks, this is fine by me!
