### ISSUE TITLE
Update layout, iconography for CRDT footnotes

### ISSUE THREAD

**Issue by neeshabeee** [COVID19Tracking/website#1282]
This is a small improvement to the flags and notes on the CRDT dashboard. The intention behind this is to make the table data easier for users to read and interpret.

![flags and notes on crdt dash](https://user-images.githubusercontent.com/22971446/87833947-0247aa00-c83e-11ea-95dc-748443095702.png)

**Updates to "disparity likely":**

_Logic:_

- [x] - The static definition for "disparity likely" no longer appear above the table.
- [x] - Instead this definition conditionally appears in the "Notes" section below the table. And it has a "See why" expand/collapse interaction with it.
- [x] - If there are no "disparity likely" flags that apply to the table, then the definition does not appear in the Notes section either.
- [x] - If there are multiple "disparity likely" flags on the table, probably best to display it just once in the Notes section.

_Visuals/interaction:_

- [x] - New flag icon replaces the existing triangle icon for "disparity likely"
- [x] - When the flag icon appears, the data point is underlined too
- [x] - When a reader hovers over the new flag icon (or the underlined data point), a tooltip appears. Copy: Racial/ethnic disparity 

likely. Please also add screen-reader only text for the tooltip.

**Updates to the numbered footnotes:**

_Logic:_

- [x] - If a data point has also been marked as "should not be compared" - prepend the existing footnote with this copy. Copy: This data should not be compared with percentage of the the population: 

_Visuals/interaction:_

- [x] - New icons and styling for the numbered footnotes
- [x] - Same as above - When the footnote icon appears, the data point is underlined too
- [x] - When a reader hovers over the new numbered footnote (or the underlined data point), a tooltip appears. Tooltip copy should 

include the entire text of the footnote. Please also add screen-reader only text to the tooltip.

**Updates to "should not be compared":**

_Logic:_

- [x] - Static definition no longer appears above the table.
- [x] - There is no longer a separate visual icon or element for "should not be compared." It's now folded into the number 

footnotes.

**Comment by samWinfield** [comment]
Adding links for the CRDT Footnotes here, and the attaching images for each. I'll add specifications and notes for individual parts below. 

**Chart with new icons and notes section:**  [Figma Link](https://www.figma.com/file/GwkYSPVlTkdgLyGNgeMrLz/v3-Refresh?node-id=1191%3A13056)
**Chart with Tooltips Active:** [Figma Link](https://www.figma.com/file/GwkYSPVlTkdgLyGNgeMrLz/v3-Refresh?node-id=1421%3A12991)
**Chart with notes section expanded:** [Figma Link](https://www.figma.com/file/GwkYSPVlTkdgLyGNgeMrLz/v3-Refresh?node-id=1421%3A12869)

Attached is an svg copy of the disparity icon, with the red diamond background. Please let me know if you need a different format, or size!
**Disparity Icons SVG:** [disparity-icons.zip](https://github.com/COVID19Tracking/website/files/4944644/disparity-icons.zip)

**Comment by samWinfield** [comment]
I'm listing the formatting details here, too. Again, please let me know if there is a more helpful way to list these things.
 
**For the whole chart:** 
![CRDT-footnotes-spacing-notes](https://user-images.githubusercontent.com/19784290/87885132-766e8300-c9e1-11ea-87c7-80d661ca6872.jpg)

**For the Disparity Tooltip:**
![disparity-tooltip](https://user-images.githubusercontent.com/19784290/87885229-5095ae00-c9e2-11ea-8d1a-bf0a8c3f0574.png)

Tooltip-sized flag icon: [SVG File](https://github.com/COVID19Tracking/website/files/4944696/tooltip-disparity-icon.svg.zip)
_I think for both tooltips, the caret would 12px wide and 6px tall._

```
Tooltip{
padding: 8px 16px;
color: #fff;
border-radius: 2px;
background-color: #303030; ($slate-800) 
font-size: 11px;
line-height: 1.4;
}
Tooltip-icon{
margin-right: 8px;
}
```

**For the state-specific tooltip:**
![state-tooltip](https://user-images.githubusercontent.com/19784290/87885429-f5fd5180-c9e3-11ea-9f6a-2422e50f9c91.jpg)

I would suggest a max-width of 296px for the state-specific tooltip.

```
Tooltip{
padding: 12px 16px;
border-radius: 2px;
color: #fff;
background-color: #303030; ($slate-800) 
font-size: 11px;
line-height: 1.4;
}
Tooltip-footnote-number{
margin-right: 4px;
}
```

**State specific flag: within chart**
<img width="140" alt="in-chart-state-specific" src="https://user-images.githubusercontent.com/19784290/87885608-36110400-c9e5-11ea-8cff-33dde900dd60.png">

Space between number and tooltip: `8px`
Underline style: `1px dotted #000`
Tooltip size: `width:16px; height: 16px;`
Tooltip background-color: `FBE8A9` or `$honey-200`
Tooltip font-size: `8px`
Tooltip font-weight: `bold`

**Disparity Flag: within chart**
<img width="140" alt="in-chart-state-specific" src="https://user-images.githubusercontent.com/19784290/87885779-f991d800-c9e5-11ea-948a-56c75c49fe46.png">

Space between number and tooltip: `6px`
Underline style: `1px dotted #000`
Icon color: `#fff`
Tooltip background-color: `E35942` or `$alert-dark`

**Disparity Notes Expanded**
<img width="721" alt="Screen Shot 2020-07-19 at 5 35 45 PM" src="https://user-images.githubusercontent.com/19784290/87885829-54c3ca80-c9e6-11ea-83b4-eac2022cb39b.png">

_Text for: "How we calculate likely disparity" will be bold._ 

```
margin: 16px 0;
padding:  32px;
background color: #F9DED9; (or $alert-light)
font-size: 18px;
line-height: 1.5;
```

**Comment by kevee** [comment]
Thanks for the detailed notes, @samWinfield! Let's adjust the spacers to [match our existing spacer set](https://covid19tracking.github.io/website-docs/?path=/story/layout--spacing).

**Comment by kevee** [comment]
Just to be clear, @neeshabeee, we are completely removing the blue 'caution' indicators from this layout. These were also in the spreadsheet. Are you going to remove these columns from the sheet eventually?

**Comment by neeshabeee** [comment]
Question answered in slack - but repeating here for tracking purposes. No, we are not planning on removing any 'caution' columns from the spreadsheet.

Does this pose any issues for this piece, where we prepend the note with "This data should not be compared with percentage of the the population: " ?

**Comment by samWinfield** [comment]
@kevee Sounds good! Would it be best to make that change just in the notes above, or in the file as well?

**Comment by kevee** [comment]
@samWinfield OK I updated all the margins you had - can you check the [preview in the PR](https://github.com/COVID19Tracking/website/pull/1285) and let me know if you see anything else that needs updating?

**Comment by samWinfield** [comment]
@kevee It looks awesome, thank you! 

The only big thing I noticed is that the tooltip for state notes runs right off the page. Can we set a max-width on the tooltip to prevent this?

<img width="744" alt="Screen Shot 2020-07-22 at 7 33 24 AM" src="https://user-images.githubusercontent.com/19784290/88171712-d20d5c00-cbed-11ea-9c09-8a444ce5a17e.png">


These rest of my notes below are nitpicky and definitely not a priority:
- [ ] I would make the cursor the pointer over the number, when there is a tooltip.
- [ ] It would be nice to make the disparity icon sit a little lower relative to the numbers/text next to it. (It's happening in the chart and the notes section.) Maybe we can add a `position:relative;` and `top:4px` to the disparity-symbol module?
- [ ] The note is a little low. For the note module (and for where it appears in the notes section below) can we add a `position:relative;` and `top: -2px;`
- [ ] Change the padding on the disclosure pane to `1.5rem`. Remove the margin-top from the first child paragraph within the disclosure pane. (It's adding a little too much extra space, there.)

Please let me know if anything needs clarifying, or anything looks weird.

**Comment by kevee** [comment]
@samWinfield Done! Thanks for the detailed notes.
