### ISSUE TITLE
Include clearer "per 1M" chart labels

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1286]
With the `total` charts, it seems clear that the y-axis represents the value mentioned in the chart title:
![image](https://user-images.githubusercontent.com/18607205/88084944-5b675480-cb42-11ea-8882-6333bcd95aa6.png)

Once a user clicks the `Per 1M People` button, though, neither the chart axis labels nor the titles change.
![image](https://user-images.githubusercontent.com/18607205/88085544-39ba9d00-cb43-11ea-8c38-2198224187fa.png)

Could we more clearly indicate that the charts are showing cases/hosp/deaths _Per 1M People_ when that setting is toggled?

I'm thinking:
- Add a label to the y-axis
- Modify the title like `New tests per 1M people`
- Something else

@goleary do you have any thoughts/preferences about this?

**Comment by goleary** [comment]
Yeah, I guess for screenshots taken of these charts a viewer might not be able to tell at first glance what the y-axis represents.

- Add label to the y-axis - my first instinct is that this wouldn't look good. I'd be happy to look at any ideas you have for it though
- Modify title - I'm not sure there is room for some of them to fit on a single line (like 'Current hospitalizations') espeically with the "notes" link that we haven't yet removed.

Another idea:

- Make the y-axis ticks show '2,500/M'... - This could make it clear without cluttering things, but maybe it's not clear enough?

What do you think?

**Comment by schwartzadev** [comment]
> Make the y-axis ticks show '2,500/M'... - This could make it clear without cluttering things, but maybe it's not clear enough?

I like this -- I think that if I hit the toggle button and saw all of the axis labels change at once, it would be pretty clear that the values represent `per 1M` calculations

**Comment by goleary** [comment]
Personally I'm less concerned about about _users_ because I think that if you click that button it's pretty obvious what happening.

I'm more concerned about viewers of screenshots taken of the charts...they are the ones who might not have the context to understand those numbers are per M, but maybe this will fix that?  Did you want to take a crack at this or would you like me to? (happy either way)

**Comment by schwartzadev** [comment]
Yeah, good point about screenshots.

It's all yours @goleary!
