### ISSUE TITLE
Chart y-axis ticks at very small values

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1293]
![image](https://user-images.githubusercontent.com/18607205/88330257-60fe9f00-cce8-11ea-909b-e8fc759c6a34.png)
(This is for Alaska)

## Actual behavior
When the values for ticks get very small (less than 1), the labels lose their meaning.
There are multiple labels for the same value.

## Expected behavior
Either
* There would be fewer y-axis ticks OR
* There would be the same number of y-axis ticks, but fewer labels

**Comment by kevee** [comment]
Closing per #1327
