### ISSUE TITLE
DESIGN: Blog pagination not scalable

### ISSUE THREAD

**Issue by tiagofsanchez** [COVID19Tracking/website#1297]
The current blog pagination will became a little bit messy as we continue to increase our number of blog posts. Currently we will have all the pages being presented in the **jump to page** section.
![Screenshot 2020-07-24 at 2 06 25 PM](https://user-images.githubusercontent.com/11288873/88364891-e8b2df00-cdb6-11ea-980a-9990b3f6a308.png)
When we have more than 10 or more pages, it will be a little bit too much.

Proposed design in figma [HERE](https://www.figma.com/file/GwkYSPVlTkdgLyGNgeMrLz/v3-Refresh?node-id=1562%3A13986). 
![Screenshot 2020-07-24 at 2 09 28 PM](https://user-images.githubusercontent.com/11288873/88365019-50692a00-cdb7-11ea-91d7-8d1a0304ce99.png)

**Comment by schwartzadev** [comment]
@tiagofsanchez thanks for taking this on! A couple design thoughts and suggestions.

1. I think we should drop the double carets: I'm not sure what behavior those cause...do they jump two pages? Ten pages? I think we should just have a single increment/decrement option.
2. We should put together some inactive styles for the first and last pages


Here are two options I put together, based on your work so far. I prefer the second one, but I'd love your input!
![image](https://user-images.githubusercontent.com/18607205/90534773-5c86a400-e137-11ea-9925-a0a9e22a17bc.png)
