### ISSUE TITLE
🚀 Cards redesign launch list

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1298]
I'm sure there are many other things to include here, but I figured I would start a working doc.

### 🚀 Launch items
- [ ] Update `data-preamble` Contentful snippet
- [ ] Remove references to spreadsheet and CSV downloads
- [ ] Remove the `Our most up-to-date...` header
- [ ] Change navigation link for data definitions
- [ ] Publish [staged change notice for API descriptions](https://headwayapp.co/the-covid-tracking-project-api-changes).

### 📝 Pre-launch items
- [x] Merge in #1296 so data definitions are consistent
- [x] Update all data definitions based on the current document in Contentful
- [x] Confirm persistent state nav behavior @tealtan
- [x] Add definitions from Contentful to API page
- [x] Find a way to bring back the data source links on the main `/data` page @tealtan
- [ ] Possibly make visual refinements to the cards @tealtan
- [ ] Data-related items:
  - [ ] Confirm plan on people vs specimen distinction in testing card (awaiting discussion with Michal / Kevin / others) @tealtan
  - [x] Confirm plan on CRDT card (awaiting discussion with Alice) @tealtan
  - [x] Double check card values with spreadsheet values (should be someone very familiar with the data) @schwartzadev

**Comment by tealtan** [comment]
Thanks! Mine are:

- [ ] Figure out what to do about the top on mobile
- [ ] Mock up the state historical data pages
- [ ] Confirm persistent state nav behavior
- [ ] Find a way to bring back the data source links on the main `/data` page
- [ ] Possibly make visual refinements to the cards

**Comment by kevee** [comment]
On the CSV download and spreadsheet - that is preamble content in Contentful that we'll have to schedule to change during launch

**Comment by kevee** [comment]
Also we need to figure out what to do with the [data sub-pages](https://feature-data-redesign-cards-subpages--upbeat-lovelace-3e9fff.netlify.app/data/state/arizona/tests):

- [ ] Move all the data definitions into the table headers
- [ ] Add charts to the top of the headers? Some sort of preamble?
- [ ] Improve the breadcrumbing to jump back to the our data page

**Comment by tealtan** [comment]
Data-related ones:

[ ] Confirm plan on people vs specimen distinction in testing card (awaiting discussion with Michal / Kevin / others)
[ ] Confirm plan on CRDT card (awaiting discussion with Alice)

**Comment by schwartzadev** [comment]
- [ ] Double check card values with spreadsheet values

**Comment by schwartzadev** [comment]
- [ ] Finish new line delimiters for notes @muamichali

**Comment by muamichali** [comment]
I added the new line delimiters, @schwartzadev :)

**Comment by schwartzadev** [comment]
Meta: all of the above comments are consolidated into the main issue. Let's keep one list there for clarity.

**Comment by kevee** [comment]
All these to-dos are moved to #1317, closing issue.
