### ISSUE TITLE
CRDT Web Dashboard: Don't show 0% in the data tables if the value is actually blank

### ISSUE THREAD

**Issue by neeshabeee** [COVID19Tracking/website#1309]
_Current Behavior:_
For race/ethnicity groups where the percentage is blank, we display that value as 0% on the CRDT dashboard. However, this is not truthful. Connecticut has an example of this in action.

Screenshot of dashboard (NHPI group - cases and deaths shown as 0%)
![image](https://user-images.githubusercontent.com/22971446/88971525-ec3bdf80-d268-11ea-92b6-74a64ccc8fa4.png)

....vs. screenshot of data in the CRDT tab (NHPI group - cases and deaths data is actually blank/not recorded):
![image](https://user-images.githubusercontent.com/22971446/88971596-12617f80-d269-11ea-83bf-d046c36294ac.png)

_New Behavior:_
For race/ethnicity groups where the percentage is blank, we should display `N/A` on the web dashboard instead.

**Comment by kevee** [comment]
So the number actually comes from the computed percent positive in the sheet, and the dashboard is programmed to show a "-" if that data is null or empty. Right now I'm seeing a zero for `nhpiPctPos` in the publish sheet.

![image](https://user-images.githubusercontent.com/270536/89329210-5d054200-d643-11ea-8b71-80ac640cf9b8.png)

**Comment by kevee** [comment]
@goldfarb Thoughts?

**Comment by neeshabeee** [comment]
Hey! Actually I have worked with Aviva on this, followup coming shortly.

**Comment by goldfarb** [comment]
@neeshabeee let me know if I can be of help, otherwise I'll leave it to you & AGS
