### ISSUE TITLE
Blog categories clarity

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1310]
Let us know what the design issue is. Screenshots are helpful!
![image](https://user-images.githubusercontent.com/18607205/89087372-4d3ee280-d351-11ea-9f58-120717586e10.png)
It looks like the categories display is showing `Data (5)` as a category, but it's really `Hospitalization and Death Data (5)`. Let's add some styles/spacing to make this more clear.

**Comment by samWinfield** [comment]
I can't seem to affect the values in inspect, so I'm kind of guessing at some numbers here. I can't think of a better solution than tightening the line-height on all of the links so if they break to two lines it's clear that they're associated.

Change the line-height for each `blog-categories-list-module--category` to `1`. 
I think that should help it, but if the needs to be more spacing between items, add `padding-top: .5rem` to each category.

Screenshot attached:
![image](https://user-images.githubusercontent.com/19784290/90202510-e6d3ae80-ddab-11ea-9b75-727e8fea4f41.png)
