### ISSUE TITLE
CRDT: New page to "Help Us Get Better Race and Ethnicity Data"

### ISSUE THREAD

**Issue by neeshabeee** [COVID19Tracking/website#1311]
The Race Data + State Outreach team are spinning up a new page that allows anyone to help advocate for better race + ethnicity data. 

---

**Task 1 of 2: Create a new page**

From this page, users can:
- Get contact information for their desired state (with the help of an API to pull in this contact information)
- See a suggested script to use when contacting their state (only available for a handful of states)
- Submit a form to share feedback/details about their advocacy experience (this would be connected to Mailchimp, so Ryan and State Outreach can start list-building and gathering feedback)
- See a confirmation page after they successfully submit the form

Resources:
- [Figma file with more details is available here](https://www.figma.com/file/GwkYSPVlTkdgLyGNgeMrLz/v3-Refresh?node-id=1775%3A0).
- See the right-side box in [this Google Doc](https://docs.google.com/document/d/1-6UwGDAiAsGRcbF5evnnGSnM_zOPJJ8KWQPDQLa7duc/edit?usp=sharing) to get the state-specific scripts for: North Dakota, Texas, West Virginia, New Mexico, and New York. Please note that the scripts for Texas and New York includes data that should be programmatically filled in (these are highlighted in the Google Doc). 

**Task 2 of 2: Update links on the existing CRDT Dashboard**
On the `/race/dashboard` page, update these links to point to this new "Help Us Get Better Race and Ethnicity Data" page
- Links that have this text: "Help us advocate for better data."
- Links that have this text: Help us get better data.
- This includes the box at the very top and also the data tables for these states: Guam, Hawaii, Louisiana, Montana (both tables), New York, North Dakota, Puerto Rico, South Dakota, Virgin Islands

**Comment by kevee** [comment]
Developer notes:

- The preamble to the page is stored as a snippet in Contentful with the slug `crdt-advocacy-page-preamble`
- The text on the right-side of the google doc (the scripts for each state) are in Contentful as `crdtAdvocacyState` entries. These are already filled in. There's a field for the state name, and a markdown field with the content.

**Comment by kevee** [comment]
@neeshabeee do we have actual contact information for each of these states?

**Comment by neeshabeee** [comment]
@kevee Hm, I was under the impression there was an existing API or library that grabbed contact information for state governors. If that's not the case though, I can certainly work on pulling this together!

Immediately what comes to mind is that we can create a spreadsheet of contact information from this site: https://www.usa.gov/state-governor. But will also do some brief research and ask State Outreach if they know of any better resources.

**Comment by kevee** [comment]
Sorry I thought we were going to have folks reach out to specific officials. If it's just govenor's offices we can use an API.

**Comment by neeshabeee** [comment]
Yes - we want to target the governor's offices for V1, so the API is perfect.

Farther down the line, we may want to change who the points of contact are, but that's still hypothetical/unknown right now. Sorry that wasn't clear!

**Comment by schwartzadev** [comment]
@neeshabeee Could please share your thoughts for styling the currently selected state? (Highlighted in the screenshot below)
![image](https://user-images.githubusercontent.com/18607205/89230771-3a225180-d5a1-11ea-9c75-5afe67e31566.png)

Thanks so much!

**Comment by schwartzadev** [comment]
Scratch that, it's already in the mock. 
![image](https://user-images.githubusercontent.com/18607205/89231786-3ee80500-d5a3-11ea-9c53-39583804ba8b.png)
