### ISSUE TITLE
Add meridiem to last updated text

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1313]
Right now, we don't specify if 11:00 is in the AM or PM. Let's add that detail.

Also note that we should use `am` and `pm`, per the style guide.

![image](https://user-images.githubusercontent.com/18607205/89314611-1c9fc700-d637-11ea-9c1c-6d8a03c62a65.png)

**Comment by schwartzadev** [comment]
@kevee it looks like this is from the `lastUpdateEt` field, which is from the API. Would it make sense to add this to the API v2 release?

**Comment by kevee** [comment]
This is fixed by https://github.com/COVID19Tracking/website/pull/1317/commits/ee600fdb11c09c65651077f9687a7c1ac849b44b in the data redesign.
