### ISSUE TITLE
State shortcuts show up on top of the UI in some narrow viewport sizes

### ISSUE THREAD

**Issue by olivierlacan** [COVID19Tracking/website#133]
![image](https://user-images.githubusercontent.com/65950/77335773-fb2fe580-6cfc-11ea-98bd-abe373dca303.png)

This happens with `#main` width set to 1024 pixels which I believe is the same as the body width.

**Comment by kevee** [comment]
Looks like #135 fixes this, please double check here and if it's good for you we can merge it:

https://deploy-preview-135--upbeat-lovelace-3e9fff.netlify.com/data/

**Comment by olivierlacan** [comment]
@kevee Fixed by #135. Feel free to add a `Fixes #133` to the PR in there. I think that'll auto close this issue.

**Comment by olivierlacan** [comment]
Oh duh you did, never mind.
