### ISSUE TITLE
feat: Create table of contents content type 

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/website#1337]
I'd like a TOC-like content type in Contentful or some kind of component that generates a list of links at the top of the [FAQ](http://covidtracking.com/about-data/faq) for better in-page navigation.

**Comment by kevee** [comment]
What if we just add a "make table of contents" checkbox in Contentful, and if so that page gets one auto-generated from the headers on the page?

**Comment by amandafrench** [comment]
Why that would be wonderful! How would you do that from a van with half the vowels on your keyboard inoperable?

**Comment by kevee** [comment]
I got a new computer, so in essence I bought some vowels ;)

**Comment by kevee** [comment]
@amandafrench here's a simple sample of putting the TOC on the top of the page:

https://deploy-preview-1346--upbeat-lovelace-3e9fff.netlify.app/about-data/faq

**Comment by amandafrench** [comment]
Can y'all make the TOC include h1 headings as well as h2 headings? The code looks to me like it tells it to go to a _depth_ of h2, but instead the TOC shows _only_ h2. Would like to show h1 as well

**Comment by amandafrench** [comment]
Ping @schwartzadev and @kevee since I can't reopen the issue (though this is not at all urgent, no rush)
