### ISSUE TITLE
Help for those who are sight-impared?

### ISSUE THREAD

**Issue by tomByrer** [COVID19Tracking/website#1350]
This is more about the charts for twitter, but might help with the website data to be more digestible for sight-impaired also.

reference:
https://twitter.com/HerHandsMyHands/status/1296231257890840576
https://twitter.com/HerHandsMyHands/status/1296231680672489475
[Instructions to **add alt-text** in Twitter](https://help.twitter.com/en/using-twitter/picture-descriptions)

Perhaps an automated solution would be to give a rough description of the chart?
E.G. for [this daily nationwide chart](https://twitter.com/COVID19Tracking/status/1296215751418757121/photo/1)
"For August 19, daily tests are 680,896, 7 day average is 722,000, 4% down from the August 15 peak, and 8% down from the highest peak on July 20."
(I made up the numbers; for illustration only.)

I used to have to make report like this like 19 years ago, but I think can be scripted now.

**Comment by kevee** [comment]
Hi, Tom, we definitely have been thinking about how to automate chart annotations on the website, and this is one of the things I hope to tackle post redesign launch.
