### ISSUE TITLE
Incorporate county data into API and website?

### ISSUE THREAD

**Issue by hammer** [COVID19Tracking/website#137]
The crew at https://coronadatascraper.com/#features.json have got some very impressive county-level data that we've been tracking for a while. I think it may be time to bring into our API and display on state-level data pages, with a huge attribution and shout-out to them.

Anyone interested in picking this up? cc @webmasterkai for API, and @kevee for state data pages.

**Comment by hammer** [comment]
The other source for county data is the NYT: https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html#g-cases-by-county. We could just scrape this table and pull into a visualization on each state page. By my count they have 54 states and territories, which appears to be more complete than the CDS data.

**Comment by kissane** [comment]
I would like us to not scrape the NYT please, but I would propose that we ask them if they'd like to share

**Comment by kissane** [comment]
(We can't scrape newsroom work without permission, for legal/ethical reasons)

**Comment by hammer** [comment]
Another data source is JHU https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv

**Comment by hammer** [comment]
Perhaps our role could be to compare the data from these 3 sources?

**Comment by kissane** [comment]
Just an update where everyone can see it, for clarity: 

We get a lot of our key data from newsrooms. If we cite them thoroughly, it is totally fine right now to grab a number here and there. Where we are working with larger datasets, like the LAT and potentially the NYT, we gotta be in touch with their teams to make sure it's all good on both sides. We have that connect in on both LAT and apparenlty the NYT right now, so this is all fine, we just need to be meticulous in citing our data back to the newsroom folks busting their asses to get it from the states/counties.

**Comment by hammer** [comment]
One other source of county data: https://coronavirus.1point3acres.com/en

**Comment by hammer** [comment]
Looks like there’s already an API for the CSBS county-level data https://github.com/ExpDev07/coronavirus-tracker-api/blob/master/README.md

**Comment by metasj** [comment]
Comparing the data from these 3 sources would be excellent

**Comment by llaflair** [comment]
Agreed! The sources above provide cross-sectional data by county. Where can one find regularly updated time-series (January-present) county-level data on COVID cases and deaths? Thanks!

**Comment by mattbk** [comment]
Some of the county data is on the screenshots included already: https://covidtracking.com/data/

**Comment by hammer** [comment]
We've determined this issue to be out of scope for our project.
