### ISSUE TITLE
Remove or split module on Contact Us page with links to the two contact forms

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/website#1382]
It might not help with the problem that people are using the 'Data Issues" form for all issues (sigh), but if possible I'd like to remove the module at the bottom of https://covidtracking.com/contact so that I can explain what each link is for separately in the text of the Contact Us page snippet.

**Comment by schwartzadev** [comment]
This is super doable -- we'll need to coordinate the contentful snippet update and merging the code updates, though.

One thing to note: we'll lose the gold color and the arrows for these links.
![image](https://user-images.githubusercontent.com/18607205/91685730-68e80500-eb18-11ea-87d4-1928c4d67a7b.png)

If you'd still like to make this update, ping me and we can get it out the door!

**Comment by amandafrench** [comment]
Yep, just remove it, @schwartzadev -- argh, sorry didn't reply, I accidentally stopped getting my GH notifications. Tell you what, I will go write the snippet update right now but will not publish it, and then when you remove this you can hit publish, or ping me and I will. I'm fine with losing the component formatting. It's the snippet with slug "contact-page-form" in Contentful.

**Comment by amandafrench** [comment]
Okay, have made the changes to the contact form snippet (which is really now a full page) -- remove module at will, @schwartzadev.
