### ISSUE TITLE
Feature Request: Display probable and confirmed cases on cases card where available

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/website#1394]
State Page:
(i.e. Delware)

https://covidtracking.com/data/state/delaware

![image](https://user-images.githubusercontent.com/1749380/91874516-51a83500-ec48-11ea-81fe-8a003b15139a.png)

We don't have the full time series of confirmed vs. probable cases in all the states, but we can report the topline number for increased transparency of the data we capture.

**Comment by kevee** [comment]
@muamichali  Are these fields already in the API?

**Comment by muamichali** [comment]
> 
> 
> @muamichali Are these fields already in the API?

Only one of them: `positiveCasesViral`
