### ISSUE TITLE
Include local news source on each state page

### ISSUE THREAD

**Issue by hammer** [COVID19Tracking/website#141]
We often check local news sources for the most recent data for each state. I think we should include a link to these sources for each state.

**Comment by kevee** [comment]
Is there a separate sheet with this information?

**Comment by hammer** [comment]
I put it into the states tab of our dev sheet for now

**Comment by schwartzadev** [comment]
I don't think this is in the production spreadsheet yet. Is this data accessible via the API at the moment? @webmasterkai

**Comment by kevee** [comment]
Closing. There is a new proce
