### ISSUE TITLE
Proposal: Exclude negative numbers from the 7-day average plot

### ISSUE THREAD

**Issue by vlucent** [COVID19Tracking/website#1415]
Large outlier negative numbers skew the 7-day average line significantly (and, arguably, in a way that does not benefit the reader). May I propose that such that extreme values be excluded from the plot?

e.g. North Carolina
![92125652-42062900-edcd-11ea-8149-fd930bcedee2](https://user-images.githubusercontent.com/22573473/92683616-5aac9c80-f301-11ea-9f65-a298300d7bb5.png)

**Comment by kevee** [comment]
Hm, should we just treat negatives as zero? @goleary ?

**Comment by goleary** [comment]
I suggested that when I wrote code to handle the line dropping below the x-axis back in the day but was directed to leave it as is (I forget who by).

Treating as 0 is definitely better than the way it's currently handled....

**Comment by muamichali** [comment]
Is this the zerp conversation we had?

**Comment by goleary** [comment]
HA! Yes, @muamichali that's exactly the conversation where we talked about it.

For reference (for those who have access):
https://covid-tracking.slack.com/archives/C015UKK7L20/p1593454274084100?thread_ts=1593446558.069100&cid=C015UKK7L20

**Comment by AaronMullan** [comment]
#1454
