### ISSUE TITLE
Charts truncated on iPad

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/website#1428]
Final chart gets truncated in iPad view according to user report. 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_29p5d)

**Comment by amandafrench** [comment]
[image0.png.pdf](https://github.com/COVID19Tracking/website/files/5219322/image0.png.pdf)

**Comment by amandafrench** [comment]
![image0](https://user-images.githubusercontent.com/227453/93103777-07c54300-f67b-11ea-9381-87b64f752546.png)

**Comment by schwartzadev** [comment]
@AaronMullan is taking a look at this!

**Comment by kevee** [comment]
Fixed in #1449
