### ISSUE TITLE
Fix missing icons for mobile 

### ISSUE THREAD

**Issue by olivierlacan** [COVID19Tracking/website#144]
![image](https://user-images.githubusercontent.com/65950/77367010-9fcb1b00-6d2f-11ea-8af6-5e31215cfedc.png)

I'd focus on the icons first, the rest we can probably tackle later.

Here they are: https://github.com/COVID19Tracking/website/blob/274b520564da7a171efafae59565cacaad96518e/_src/_templates/base.njk#L21-L24

**Comment by bhays** [comment]
Happy to fix other missing assets as well, although I'm not quite sure on how they'd work with the current build setup.
