### ISSUE TITLE
Initialize new front end stack

### ISSUE THREAD

**Issue by lucasgonze** [COVID19Tracking/website#150]
Get Gatsby and React going. Do first draft of all the components.

**Comment by kevee** [comment]
I have a storybook up in a separate netlify instance (the deploy steps are different, so I'll work with Kai on that tomorrow). This way we can implement design on a component-based level.

https://5e798067e08bcc000acdf70b--goofy-tesla-43452a.netlify.com/__storybook/

I'll be working on getting together all the pages tomorrow and keep a list of what pages have no defined content yet.

**Comment by lucasgonze** [comment]
(Moving this from the master tracking ticket #125) Components that are either just plain needed, or defined in the doc. I'm going to boilerplate these out and hook up a storybook so we can monitor.

- [ ] Accessibility utilities
- [x] Skip content (probably reach skipnav)
- [ ] Header
- [ ] Footer
- [ ] Help/small text
- [ ] Secondary navigation
- [x] Buttons (big, small)
- [x] Lead paragraph
- [ ] Data visualization links
- [ ] Lists (UL, OL, UL unstyled)
- [ ] Table (support horizontal scroll in mobile)
- [ ] Visualization wrapper with associated data in table for a11y
- [ ] Company/supporter logo

**Comment by lucasgonze** [comment]
#145 is an ask for the Table component.

**Comment by schwartzadev** [comment]
So was #108 , for sort/filter
