### ISSUE TITLE
Support blog image width equal to blog content width

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1501]
Right now, we're adding horizontal whitespace within images on our blog. This is just fine for desktop users:
![image](https://user-images.githubusercontent.com/18607205/95483215-34a00980-094c-11eb-954e-09cc49e94633.png)
(looks good!)

However, this looks...not as good for mobile users:
![image](https://user-images.githubusercontent.com/18607205/95484074-40400000-094d-11eb-8d59-451c2d9fa1a4.png)

Let's add a flag to Contentful that sets the image width to the width of the blog content. This will let our editorial + viz folks submit images without the horizontal whitespace that render at the same width as the blog content.

This flag should render images like this:
![image](https://user-images.githubusercontent.com/18607205/95617202-45be4880-0a28-11eb-9780-bdf1a7e1cc48.png)
![image](https://user-images.githubusercontent.com/18607205/95617236-5373ce00-0a28-11eb-980d-ecdb97a25b4b.png)

- [x] Add the flag to the Contentful blog image embed (@kevee could you please tackle this?)
- [x] Consume the flag in the code (I'm happy to handle this @schwartzadev )
- [ ] Notify editorial/blog/viz of the feature

**Comment by kevee** [comment]
@schwartzadev - added new field `fullWidthMobile`

**Comment by schwartzadev** [comment]
Amazing, thank you @kevee!
