### ISSUE TITLE
Order of blog posts with the same publishing date

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1505]
Right now, blog posts are sorted by date published. This is generally good, but causes strange behavior when multiple posts are published on the same day. For example, assume we published blog post Z yesterday, X this morning, and Y this afternoon. The posts currently appear in the following order on the `/blog/` page:

```
X <- this morning
Y <- this afternoon
Z <- yesterday
```
...while we would expect them to display like this:

```
Y <- this afternoon
X <- this morning
Z <- yesterday
```

Let's make a solution that handles this edge case.

**Comment by kevee** [comment]
We already have support for time in the publish date, should we start using that?

**Comment by kevee** [comment]
I updated this afternoon's blog post to have a later time than 0 and it's now on top.

**Comment by schwartzadev** [comment]
Amazing, yes. I think we should do that!
