### ISSUE TITLE
Home page (website restructure)

### ISSUE THREAD

**Issue by lucasgonze** [COVID19Tracking/website#151]
Implement 1.0 Homepage

This one has subpieces (this is Erin I hijacked the issue):

- [x] Final homepage spec
- [ ] Final homepage comp
- [ ] Final homepage template
- [ ] Final homepage content

Requirements:
https://docs.google.com/document/d/1NPypuNap-yFaOpzd2SKkXbI9GnkzI5QOsozLACSBuww/edit#bookmark=id.gdoqjntnfhdf

**Comment by kissane** [comment]
Updated the page outlines doc with a real HP spec, which I copy here for discussion and visibility:

- **Big tagline:** 
> The COVID Tracking Project obtains, organizes, and publishes high-quality, state-level data required to understand and respond to the COVID-19 outbreak in the United States. 

- **Get the Data/Learn About the Data** (as comped)
- **Two previews of dataviz** from the Visualizations section
- **Press logos**
- **Why This Data Matters**
> Without complete data—including not just identified cases, but how many people have been tested, how many tests are pending, and all known COVID-19 patient outcomes (hospitalization, ICU admission, etc.)—we will never understand enough about this outbreak to make sound decisions about interventions. No federal, state, or institutional source is publishing complete state-level information, so our volunteers are keeping at it . (Read more link, styled in a way that is pleasing to the designers) [TEXT NOT FINAL BUT USE IT FOR NOW]
> And some version of [this visual](https://twitter.com/covid19tracking/status/1242183959275909131?s=21)

- **Press links**, maybe like six?
- **Look up your state’s data report card** and **find out how to help**
