### ISSUE TITLE
Data Builders Local 1 overlapping with site-header-tabs

### ISSUE THREAD

**Issue by goldfarb** [COVID19Tracking/website#1521]
On https://covidtracking.com/race, the amazing image overlaps the text.

P.S. I think this looks awesome, and it may be on purpose, in which case disregard this issue.

![image](https://user-images.githubusercontent.com/3722037/96492408-99dbe080-1211-11eb-8eaf-c2b949cf2c55.png)

**Comment by schwartzadev** [comment]
Not on purpose! It does look fun, but the link cannot be clicked right now since the image is in the way. Thanks for flagging this @goldfarb 👍
