### ISSUE TITLE
Re-evaluate race homepage external news links 

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1524]
We currently have this section at the bottom of https://covidtracking.com/race

![image](https://user-images.githubusercontent.com/18607205/96513351-3e185400-121f-11eb-9499-1ef3b091f109.png)

I think there are two main options here:

1. These should have the publication name next to the dates, but don't have that now. We could fix this and move on.
2. These articles are a little dated (they run from April through June), so another option could be to remove this section from the race page.

@goldfarb et al: what do you think?

**Comment by goldfarb** [comment]
I can update the links in the meantime.

I like the idea of the publication name being included.

Thank you @schwartzadev

**Comment by goldfarb** [comment]
The publication data is in contentful, so it should be easy to include in the display.
