### ISSUE TITLE
Implement "See the Data" page

### ISSUE THREAD

**Issue by lucasgonze** [COVID19Tracking/website#153]
Requirements:
https://docs.google.com/document/d/1NPypuNap-yFaOpzd2SKkXbI9GnkzI5QOsozLACSBuww/edit#bookmark=id.uu209f9dnxxk

**Comment by lucasgonze** [comment]
Thoughts from Dustin Preisler on the V1 of this page:

1. The jump to states on /data/ is cluttery and I am curious of it's real utility.  Do we have any tracking setup to understand what people use (haha, i know).  Anyway, just my 2 cents.

2. It would be great to see US Totals in the same font and position as states, on top of the main top block of data.  It seems inconsistent.

3. I would love to see the grade move up in the list of things under the state to the first thing after the block.  I also think it would be great to enable a hover over per state (or at least an understanding for the state somehow) of which +1s, they actually got in the scoring.

**Comment by kissane** [comment]
This is all underway and fixed in the new designs, closing this for decluttering.
