### ISSUE TITLE
Atlantic logo in press section is outdated

### ISSUE THREAD

**Issue by olivierlacan** [COVID19Tracking/website#1585]
Very minor issue but we have two conflicting Atlantic logos:
- 2019 edition (shown in the masthead): 
  - https://github.com/COVID19Tracking/website/blob/1da842a125a40630139ead0e7414f4a4624a8dd0/src/images/atlantic-logo.svg
- old one (shown in press section)
  - https://github.com/COVID19Tracking/website/blob/1da842a125a40630139ead0e7414f4a4624a8dd0/src/images/press-logos/the-atlantic.svg

Top of page:
![image](https://user-images.githubusercontent.com/65950/99020713-33569380-252d-11eb-9244-c34d9da22be4.png)

Press section:
![image](https://user-images.githubusercontent.com/65950/99020762-49645400-252d-11eb-8cf5-ab42627a7158.png)

We need a black on white version for the press section and the masthead Atlantic logo is white but Wikimedia has our backs: https://upload.wikimedia.org/wikipedia/commons/d/da/The_Atlantic_Logo_11.2019.svg

**Comment by schwartzadev** [comment]
Great catch, thanks @olivierlacan 👍
