### ISSUE TITLE
Always show the state navigation list

### ISSUE THREAD

**Issue by swiperthefox** [COVID19Tracking/website#159]
Thanks for creating this project.

Since the states data page is quite long, I think it's useful to have the state list fixed on the left side of the page. Here is a quick hack to show what I mean.

```
--- /tmp/_states.scss	2020-03-24 09:15:23.994177972 -0400
+++ /tmp/_states_new.scss	2020-03-24 09:17:04.249103796 -0400
@@ -19,9 +19,10 @@
 .states-nav {
   max-width: 6vw;
   padding-left: 5px;
-  position: absolute;
+  position: fixed;
   right: 1vw;
   top: 150px;
+  bottom: 100px;
 
   @media (max-width: $viewport-md) {
     max-width: 100%;
@@ -38,6 +39,8 @@
   ul {
     margin-top: 0.5em;
     padding-left: 0;
+    height: 90%;
+    overflow: auto;
 
     @media (max-width: $viewport-md) {
       display: flex;
```

1. make the state-nav container fixed on the left side, and set a height for it by specifying the `bottom` property.
2. set overflow mode to auto for the ul list and specify its height.

**Comment by schwartzadev** [comment]
Interesting -- thank you for sharing :+1: 

My initial reluctance to do this was that the nav bar took up ~15% of the screen real estate on mobile devices. What would this change look like on mobile? Could you please share some screenshots?

Thanks!

**Comment by swiperthefox** [comment]
Thanks for your response.

I forgot about the mobile devices. Just checked the site on my phone, and
there is no space for the navigation bar for sure.

During that test, I found the "back to top" link, so it only takes two
clicks to switch to another state, it's good enough I think.

I think the state list of the mobile version (the grid) is easier to use
than that of desktop version (the list). So maybe a fixed "jump to" button
on the top right button with a hoverable menu? This requires more changes,
and as I am not familiar with SCSS, I am only attaching a gif as a demo.

Thanks again for creating the project.

Andrew Schwartz <notifications@github.com> 于2020年3月24日周二 下午12:40写道：

**Comment by swiperthefox** [comment]
I sent my last post from email, not sure if the gif is attached. [Here](https://drive.google.com/file/d/1WV1_OwNBgQUDWSRAxodwXuP74iDiGfAu/view?usp=sharing) is the image on google drive.

**Comment by swiperthefox** [comment]
I gave it a try and created pull request #193, which implements the hoverable dropdown menu. So I am going to close this issue.

Thanks.
