### ISSUE TITLE
Data issue report form autofills "State" field from user browser info, not user input

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/website#1591]
On the Data Issue form at https://covidtracking.com/contact/data I noticed when I was testing it that in Firefox for Mac (latest version) the State dropdown changed to North Carolina no matter what state I put in it originally -- it must be grabbing from my browser autofill data. I figured I would wait to see if it seemed as though other submissions had that same error, and I saw some just tonight. They are tagged "Autofill Error in Contact Form" in Front.

**Comment by amandafrench** [comment]
On further testing, I can see that when I use the browser autofill to fill in my name and email address later in the form, it "helpfully" "corrects" the entry in the State dropdown to the state in my address info.

**Comment by kevee** [comment]
@amandafrench should we just disable autofill on the form?

**Comment by amandafrench** [comment]
Yes! It's not an onerous form: people can type their names. Thanks.
