### ISSUE TITLE
Create 3 column sub-section to hold race/ethnicity card data

### ISSUE THREAD

**Issue by kedarjoyner** [COVID19Tracking/website#1597]
**Description**
Create a 3-column section dedicated to the Race/Ethnicity data cards. 

**Requirements**
* Add section header titled `Race & ethnicity data`
* Create placeholder for 3 different columns
* Column 1: Include placeholder 3 links (data quality grade, racial dashboard, visual graphic) 
* Column 2: I include placeholder 2 data cards following branding and visual guidelines of existing cards.

**Design Specs**
https://www.figma.com/file/Y5LMdUaE09HaPrEsn4JiqQ/CRDT-Cards?node-id=289%3A2

**Comment by schwartzadev** [comment]
Implementation:
- [ ] Use `h2` for the section header
