### ISSUE TITLE
Add link to view data as a graphic

### ISSUE THREAD

**Issue by kedarjoyner** [COVID19Tracking/website#1598]
**Description**
Create button that links user to view a particular state's race/ethnicity data as a visual graphic.

**Requirements**
- Bar graph icon left-aligned 
- Arrow icon right-aligned
- Hyperlink takes user to visual graphic of race/ethnicity data for that particular state, which uses an anchor tag. Example for Alabama: https://covidtracking.com/race/infection-and-mortality-data#AL
- Background of button changes color on hover

**Design Specs**
https://www.figma.com/file/Y5LMdUaE09HaPrEsn4JiqQ/CRDT-Cards?node-id=289%3A2

**Comment by schwartzadev** [comment]
Implementation notes:
- [ ] Create card footer component
  - [ ] Include cta arrow (use html arrow)
  - [ ] Destination param
  - [ ] Text content
