### ISSUE TITLE
Add link to racial data dashboard

### ISSUE THREAD

**Issue by kedarjoyner** [COVID19Tracking/website#1599]
**Description**
Create button that links user to view a state's racial data dashboard page

**Requirements**
- Spreadsheet icon left-aligned 
- Arrow icon right-aligned
- Hyperlink takes user to the state's racial data dashboard, which uses an anchor tag. Example for Alabama: https://covidtracking.com/race/dashboard#state-al
- Background of button changes color on hover

**Design Specs**
https://www.figma.com/file/Y5LMdUaE09HaPrEsn4JiqQ/CRDT-Cards?node-id=289%3A2

**Comment by schwartzadev** [comment]
Implementation:
- [ ] Create a component for these cta boxes
  - [ ] Pass an icon path
  - [ ] Text
  - [ ] Link destination

Q: Should the entire box be clickable, or just the text and the arrow?
