### ISSUE TITLE
Add visualization gallery

### ISSUE THREAD

**Issue by hammer** [COVID19Tracking/website#16]
Could include things like Willem’s dope Tableau dashboard and graphics that use our data like this one:
![](https://pbs.twimg.com/media/ES7QrXCXQAAbGqD.jpg)

**Comment by hammer** [comment]
https://twitter.com/yiqinfu/status/1238621836100784128

**Comment by loglow** [comment]
Just created this very simple domain & page: http://www.covidcharts.com/

Right now it's just using Google Sheets, but I'll probably update it to use the JSON API.

**Comment by hammer** [comment]
Thanks @loglow! I’ve invited you to our Slack workspace to discuss how to best connect these sites moving forward.

**Comment by hammer** [comment]
https://covid19dashboards.com/growth-us-states/

**Comment by hammer** [comment]
https://public.tableau.com/profile/peter.james.walker#!/vizhome/shared/ZCDYCJ4TF

**Comment by hammer** [comment]
https://github.com/rbracco/covidcompare

**Comment by chiester** [comment]
https://www.tinpanvalley.com/covid

**Comment by hammer** [comment]
https://github.com/eric-czech/covid-tracking

**Comment by kissane** [comment]
I'm flagging this up to our internal presentation/viz leads who have been working on this for a bit and will soon be rolling something out.

**Comment by tehkaiyu** [comment]
Hi there, I've been playing around with your API and have built a [small dashboard](https://covid.kyh.io) that visualizes the data. You can find the source [here](https://github.com/tehkaiyu/covid-dashboard). Let me know if ya'll need any more help or if you'd like to integrate

**Comment by hammer** [comment]
https://www.politico.com/interactives/2020/coronavirus-testing-by-state-chart-of-new-cases/
