### ISSUE TITLE
Add link to data quality grade

### ISSUE THREAD

**Issue by kedarjoyner** [COVID19Tracking/website#1600]
**Description**
Create button that links user to view information about data quality grading

**Requirements**
- Data grade icon left-aligned that dynamically changes based on grade associated with data
- Arrow icon right-aligned
- Hyperlink takes user to: https://covidtracking.com/about-data/state-grades
- Background of button changes color on hover

**Design Specs**
https://www.figma.com/file/Y5LMdUaE09HaPrEsn4JiqQ/CRDT-Cards?node-id=289%3A2

**Comment by schwartzadev** [comment]
See #1599 for more notes

**Comment by schwartzadev** [comment]
Implementation:
- [ ] Implement this component with the main state grade
- [ ] **Remove the component**

Post-launch:
- [ ] Use CRDT grade in the component, launch
