### ISSUE TITLE
[Card 1] Race & ethnicity cases

### ISSUE THREAD

**Issue by kedarjoyner** [COVID19Tracking/website#1601]
**Description**
Create card to consume and display `Race & ethnicity` cases data

**Requirements**

- ~~Historical data link should take user to...~~ Don't include historical data link
- Display data for all race/ethnicity groups reported for a state
- Data is calculated based on cases per 100,000 people
- If state doesn't report *any* race/ethnicity data, show `Help us get better data` call-to-action. Links user to https://covidtracking.com/race/get-better-data.

**Design Specs** 
https://www.figma.com/file/Y5LMdUaE09HaPrEsn4JiqQ/CRDT-Cards?node-id=290%3A7

**Comment by schwartzadev** [comment]
Implementation notes:
- [ ] Create card footer component
  - [ ] Include cta arrow (use html arrow)
  - [ ] Destination param
  - [ ] Text content
- [ ] Use the same calculated fields as those on the social cards

Q: Should we include this whole `Race & ethnicity data` section on the main `/data` page?
