### ISSUE TITLE
[Card 2] Race & ethnicity deaths

### ISSUE THREAD

**Issue by kedarjoyner** [COVID19Tracking/website#1603]
**Description**
Create card to consume and display a state's Race & ethnicity death data

**Requirements**

- Historical data link should take user to...
- Display data for all race/ethnicity groups reported for a state
- Data is calculated based on deaths per 100,000 people
- If state doesn't report *any* race/ethnicity data, show `Help us get better data` call-to-action. Links user to https://covidtracking.com/race/get-better-data.

**Design Specs**
https://www.figma.com/file/Y5LMdUaE09HaPrEsn4JiqQ/CRDT-Cards?node-id=290%3A7

**Comment by schwartzadev** [comment]
- [ ] Handle cases where there are fewer than 10 deaths per group
