### ISSUE TITLE
Add missing space for civil services citation

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1608]
Looks like we're missing a space between `Source:` and `Civil Services`...let's add it in there!
![image](https://user-images.githubusercontent.com/18607205/99702179-b8bcd500-2a52-11eb-9e9f-1e5f88f64c1b.png)

Edit: On this page: https://covidtracking.com/race/get-better-data

**Comment by ivarvong** [comment]
There seems to be an (unlikely!) collision on the `._9c10` selector.

`.toggle-wrapper` [0] is the first rule to output to this selector, `.detail-text` [1] is the second.

The `display: flex` from [0] causes the existing space [2] to be collapsed for "Source: Civil Services". 

To confirm this, add something like `--mark-conflict: 1` to `.toggle-wrapper` and inspect the computed CSS for the component [2].

The behavior of the component changes when this is fixed, specifically that `text-align: right` [3] will apply above `$viewport-sm`. I'm not sure if that's desirable.

Locally, changing the `cssLoaderOptions` hash length from 4 to 5 fixes the selector collision. [4]

0: https://github.com/COVID19Tracking/website/blob/5a814c7998e7c8dca108a48c3943b10e40acbb58/src/components/common/toggle.module.scss#L24-L27
1: https://github.com/COVID19Tracking/website/blob/3dd92ac6fdb0e4a631d999a7b6242783d78431f5/src/components/common/detail-text.module.scss#L1-L13
2: https://github.com/COVID19Tracking/website/blob/3dd92ac6fdb0e4a631d999a7b6242783d78431f5/src/components/pages/race/get-better-data/state-contact.js#L61
3: https://github.com/COVID19Tracking/website/blob/3dd92ac6fdb0e4a631d999a7b6242783d78431f5/src/components/pages/race/get-better-data/state-contact.module.scss#L2
4: https://github.com/COVID19Tracking/website/blob/master/gatsby-config.js#L62

**Comment by theroyalpekka** [comment]
Am a beginner, able to resolve the problem by changing the styling of the page , is this a good way to solve this issue ?

**Comment by schwartzadev** [comment]
Closed by #1633
