### ISSUE TITLE
Vertically align clock icon and content

### ISSUE THREAD

**Issue by kedarjoyner** [COVID19Tracking/website#1614]
Vertically align both clock icon and its adjacent content.  Placing a `vertical-align: middle` on component's container may fix the issue if the content is wrapped in HTML tags. 

<img width="887" alt="Screen Shot 2020-11-19 at 7 27 48 PM" src="https://user-images.githubusercontent.com/12139428/99744840-0dd20880-2a9e-11eb-8697-9d82733a7291.png">

**Comment by schwartzadev** [comment]
@kedarjoyner I wasn't encountering this issue on FF/Chrome/Edge on Windows, but I added `vertical-align: middle` to the css. If it's not too much trouble, could you please double-check this is working for round two?
