### ISSUE TITLE
charts: Fix last x tick on full-time-series

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#1624]
We hide the last xtick label on charts when looking at the 90-day window if the last date is less than 15 days from the first of the month. But not the full time-series, so:

![image](https://user-images.githubusercontent.com/270536/99908084-4daf1080-2c95-11eb-8fe7-79f99bdcc28c.png)

**Comment by jmelot** [comment]
Hi, new here! I would like to take a look at this if someone isn't already (with the caveat that it may be next weekend before I can make a PR).
