### ISSUE TITLE
Content in col 1 buttons overflows their container around 1080px

### ISSUE THREAD

**Issue by kedarjoyner** [COVID19Tracking/website#1631]
Priority: Low.  Should not delay launch. 

**Screenshot of issue**: 
<img width="1041" alt="Screen Shot 2020-11-23 at 5 56 04 PM" src="https://user-images.githubusercontent.com/12139428/100028950-b2fa2300-2db5-11eb-99a4-0251cc5640f6.png">

**Comment by schwartzadev** [comment]
Thanks for this @kedarjoyner!

What is the expected behavior here? Should the font size be smaller at this sized viewport?
