### ISSUE TITLE
Fix definitions sidebar color/alignment

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1644]
On Chrome, we have a little bit of purple peeking out behind the definitions sidebar scrollbar:

![image](https://user-images.githubusercontent.com/18607205/100561944-70ce5700-3277-11eb-8c65-97d66188253d.png)

Let's style the scrollbar to have the same `#111354` background so this small corner isn't appearing on its own. Since this is not a Firefox issue, we can use the `::-webkit-scrollbar` psuedo element.

**Comment by JackHowa** [comment]
Good find. I'm not sure I totally understand customizing the scrollbar like referenced in the stack link. (I'm usually weary of messing with that.) On page https://covidtracking.com/data, then clicking the little Definition link, it looks like removing the 2rem border ensures the nested scrollbar is full-height (no purple below). 

If we want, I can try to look into replicating the design with the full-height scrollbar. I haven't done cross-browser testing on this but it seems to be working as expected with chrome. 

definition link 
![Screen Shot 2020-12-10 at 12 26 06](https://user-images.githubusercontent.com/5950956/101772072-cb22af80-3ae2-11eb-818c-50f2ecf7a15e.png)

before: 

![Screen Shot 2020-12-10 at 12 28 35](https://user-images.githubusercontent.com/5950956/101772338-25bc0b80-3ae3-11eb-938a-e6f5d8d1c1a7.png)

after: 

![Screen Shot 2020-12-10 at 12 30 43](https://user-images.githubusercontent.com/5950956/101772579-70d61e80-3ae3-11eb-8dfd-703e4b800105.png)
