### ISSUE TITLE
Standardize definitions panel header context

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1668]
When a user visits the definitions panel for a state, they'll see something like this:
![image](https://user-images.githubusercontent.com/18607205/102017640-5ab7a080-3d25-11eb-8083-87af2c7a8f64.png)

...with the header "Definitions."

If they click on an annotation or a warning, the header appears like this:
![image](https://user-images.githubusercontent.com/18607205/102017649-702cca80-3d25-11eb-9931-b3f6005936d5.png)

("[[state name]] Annotations & Warnings")

We should standardize these to either:
* Include the state name for both
* Exclude the state name for both

**Comment by kevee** [comment]
Include the name for both!
