### ISSUE TITLE
Add a desktop "jump to top" button for the racial data dashboard

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#1680]
Right now, there is no way for desktop users on the racial data dashboard to return to the top of the page. Let's add that functionality.

**Comment by chonghorizons** [comment]
![image](https://user-images.githubusercontent.com/36284839/102853782-de345a00-43d5-11eb-9d15-9e78588254c1.png)

I could not reproduce.
It appears like every page has a back to top button. See screenshot.
If the screen is narrow, it shows up just as the arrow without the text.

Given this, can this be closed?

**Comment by schwartzadev** [comment]
That sounds good to me. Let's hold off until the redesign (when hopefully this is no longer an issue!).

Thanks @chonghorizons

**Comment by chonghorizons** [comment]
Thumbs up.

Btw: I am a (not employed) junior dev and I just submitted an application to volunteer with CovidTrackingProject.  Eventually, I guess this will filter to the website team.


 If there is any housekeeping or documentation stuff needed, please let me know how I can be useful! 

In the meantime, I'll keep an eye out on the issue tracker to reproduce errors. I'll also familiarize myself with the code base and the testing.
