### ISSUE TITLE
State Latest Totals | Screen reader | Latest totals is not available when using screen reader

### ISSUE THREAD

**Issue by LaurieSReynolds** [COVID19Tracking/website#1692]
Latest totals for each state is not available when using a screen reader.
State list is in the DOM after the Latest Totals panel.
Currently the state is a link to navigate to a different page

Recommendation

1) Make the latest totals panel hidden for screen readers - aria-hidden="true"
2) The state click should display a modal which contains the latest totals that can be dismissed. This would only be available for screen readers.

**Comment by kevee** [comment]
@LaurieSReynolds - could we
