### ISSUE TITLE
CRDT: Add AS, MP to /race/dashboard

### ISSUE THREAD

**Issue by neeshabeee** [COVID19Tracking/website#1766]
Add American Samoa (AS) and the Northern Mariana Islands (MP) to the dashboard.

Neither have any data available for cases or deaths. 
![image](https://user-images.githubusercontent.com/22971446/105787112-2e518f80-5f33-11eb-94c7-f64106708b70.png)

So the expected result should be the "No data" state:
![image](https://user-images.githubusercontent.com/22971446/105786998-ec284e00-5f32-11eb-8fa7-f1d9c473c973.png)

**Comment by schwartzadev** [comment]
This is done! See: https://covidtracking.com/race/dashboard#state-mp
