### ISSUE TITLE
[Placeholder] CRDT: Add territories to the social cards

### ISSUE THREAD

**Issue by neeshabeee** [COVID19Tracking/website#1767]
Add American Samoa (AS), Guam (GU), Northern Mariana Islands (MP), and the Virgin Islands (VI) to the list of social cards.

These territories will have an empty state, because there is no data to show. **Exact details coming, but we will use the same template as Puerto Rico. Might need to adjust the copy and/or the CTA though**

_What the Puerto Rico template looks like_
![image](https://user-images.githubusercontent.com/22971446/105788167-c734da80-5f34-11eb-82ea-78c0a287716c.png)

**Comment by schwartzadev** [comment]
Tabling this for now.
