### ISSUE TITLE
Update best practices doc

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#178]
We should update this to include our current requests on outcomes. @careeningspace LMK if you're up for taking a crack at it? (If so just make a copy, the public one is locked down.)

https://docs.google.com/document/d/1OyN6_1UeDePwPwKi6UKZB8GwNC7-kSf1-BO2af8kqVA/edit

**Comment by careeningspace** [comment]
I will give it a try in the morning

**Comment by kissane** [comment]
It looks like Alexis is working on it! Now I will coax him into a Github account so he can close his first issue.
