### ISSUE TITLE
Recovered/discharged patients 

### ISSUE THREAD

**Issue by mortenbache** [COVID19Tracking/website#180]
Thank you for this brilliant data set. 
Form Italian data sets I find it extremely useful to track recovered/discharged patients from hospitals, so you can get an overview of the *current* load on the hospitals. Otherwise you just sum up. I know it is not so useful now because no one is being discharged yet, but it will be. 
Another useful stat is "intensive therapy" cases. 
I have made some excel dashboards that show how it can be useful
https://github.com/mortenbache/COVID-19-Excel-dashboards

**Comment by kevee** [comment]
Hi, @mortenbache! I love this idea, not sure where our data team is on it. There's already an issue open with this request, #177, so I added your comment to it and will close this one.
