### ISSUE TITLE
Clarify number of states and territories reporting each figure

### ISSUE THREAD

**Issue by hammer** [COVID19Tracking/website#185]
On our [US historical data](https://covidtracking.com/us-daily/) page we have a column "States & Territories" that reports the number of states and territories from which we collected data on each day. Unfortunately "Hospitalized" counts are not reported by all 56 states and territories. Perhaps we could refactor this display so that, for each figure, we could report the number of states and territories reporting that figure?

**Comment by hammer** [comment]
cc @jdmaresco who is thinking through how we will count and display our new outcomes data.

**Comment by kevee** [comment]
This gets to a bigger question: we really need hard relationships between states, their daily reporting numbers, and the US reporting numbers. Like a snapshot of every date's status per day, including info on what numbers they are reporting.

For example, let's say California changes from press releases to a website for reporting. That should be updated in the notes for the state, but the historic record for California up until that time should have that old note attached to it...

**Comment by kevee** [comment]
An idea below. Although I think we might start to need collapsible cards to really display this information.

![image](https://user-images.githubusercontent.com/270536/78499704-4942e100-7720-11ea-874a-573fa55b3785.png)

**Comment by careeningspace** [comment]
From a sheets perspective - it is pretty easy to dice it up based on what is reported. [See Tab Here](https://docs.google.com/spreadsheets/d/1MvvbHfnjF67GnYUDJJiNYUmGco5KQ9PW0ZRnEP9ndlU/edit#gid=1540959714)

![Screen Shot 2020-04-05 at 11 58 43 AM](https://user-images.githubusercontent.com/43073915/78503489-d4c66d00-7734-11ea-9f47-7cbb225182ea.png)

**Comment by kevee** [comment]
Agreed, we just need to get that information into the API, since the US daily data doesn't expose that information.

**Comment by kevee** [comment]
...also if we're doing something like "Only count states with hospital data," then we also need to differentiate between empty cells (don't report data) and zero (report data, but no one is in the hospital).
