### ISSUE TITLE
Question: can we revert to tables?

### ISSUE THREAD

**Issue by beep** [COVID19Tracking/website#200]
I noticed that we’re using `div`-based markup for most of our `table`s. (I think the change landed in #106.) I’d like to ask if we could revisit that decision, as table-based markup provides a _lot_ of [navigational](https://a11yproject.com/posts/accessible-data-tables/) [affordances](http://www.tsbvi.edu/web/tables/2-tables-jaws.html) to screen readers—announcing when a table has focus, how much content is in it, skipping to (and over) a table, &c.—and to keyboards.

If there’s interest in discussing this further, there’s a bunch of ways to introduce alternate table layouts at different breakpoints, using CSS and/or JS on the client! Two quick examples:

- https://github.com/filamentgroup/tablesaw/ (The column toggle is a pretty 🆒 pattern, I think.)
- https://adrianroselli.com/2017/11/a-responsive-accessible-table.html#ResponsiveViewportWidth

I realize this probably isn’t an easy change, but I think it’d do a lot of good. Happy to discuss more here or in Slack, though!

**Comment by schwartzadev** [comment]
**Support**: That was my doing and in hindsight, it probably wasn't the best call. As one of the people implementing the designs tor V2, I can look more into this. I'm sure that we can implement breakpoints while using `table`.

This certainly seems worthwhile even if it is a difficult modification.

Thanks for bringing this up!

**Comment by beep** [comment]
@schwartzadev Thanks Andrew! Just for the record, I think you did a _stellar_ job with that flex-driven layout. But if there’s anything I can do to help figure out an approach for v2, do let me know; if I can help, I’d love to!

**Comment by schwartzadev** [comment]
Implemented in #221
