### ISSUE TITLE
Add logos to press section

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#206]
- Add logos for the following outlets to the website's "In the press" section: The New Yorker, Slate, NPR, MarketWatch, Ars Technica, CityLab, Yahoo, Business Insider, Gizmodo, ZD Net, CBS, The Wall Street Journal. 

- Add links that are not on the page yet (the blue rows in this spreadsheet). 

- Make NYT logo a big bigger. It feels very small right now and it's one of the most prestigious places we have there.

**Comment by kevee** [comment]
Hi, @julialedur! I don't see the spreadsheet link here - can you add it? Thanks!

**Comment by julialedur** [comment]
Oops, my bad, forgot to link! https://docs.google.com/spreadsheets/d/1-lvGZ3NgVlda4EcF5t_AVFLnBqz-TOl4YZxYH_mJF_4/edit#gid=0

**Comment by schwartzadev** [comment]
Here's a list. I linked svg logos as available on Wikimedia Commons.
- [ ] [The New Yorker](https://commons.wikimedia.org/wiki/File:The_New_Yorker_Logo.svg)
- [ ] Slate - no svg logo on Wikimedia
- [ ] [NPR](https://commons.wikimedia.org/wiki/File:National_Public_Radio_logo.svg) - styled in black and white [like this](https://media.npr.org/assets/img/2016/11/17/nprlogo_blackoutline_custom-78c536fbe4dca66b6cf31cb462af2e3a74f55afb-s800.jpg)
- [ ] MarketWatch - no svg logo on Wikimedia
- [ ] [Ars Technica](https://commons.wikimedia.org/wiki/File:Ars_Technica_logo.svg)
- [ ] CityLab - no svg logo on Wikimedia
- [ ] [Yahoo](https://commons.wikimedia.org/wiki/File:Yahoo!News_Logo.svg)
- [ ] [Business Insider](https://commons.wikimedia.org/wiki/File:Business_Insider_Logo.svg)
- [ ] [Gizmodo](https://commons.wikimedia.org/wiki/File:Gizmodo.svg)
- [ ] ZD Net
- [ ] [CBS](https://commons.wikimedia.org/wiki/File:CBS_logo.svg) or [this one](https://commons.wikimedia.org/wiki/File:CBS_News.svg) (someone should review these...)
- [ ] [The Wall Street Journal](https://commons.wikimedia.org/wiki/File:Wall_Street_Journal.svg)


FYI --- the press links on the homepage auto-update from that spreadsheet. (Based on the rows with `Add to COVID Tracking Project Website? == TRUE`)

**Comment by julialedur** [comment]
thanks! i can review these! not sure about the links though, can you ask on #website?

**Comment by julialedur** [comment]
- for CBS, let's use CSB News cause that's the one on the website
- for the colorful ones, let's make the colored parts black (let me know if you need help with that!) 
- for the ones you couldn't find on wikimedia commons, we can get from the outlet's website or the internet. def not ideal but it's okay

**Comment by schwartzadev** [comment]
Agreed 100% -- I'll work on making the logos black and white now.

Ideally we can find SVGs for the missing ones :crossed_fingers:

**Comment by julialedur** [comment]
I'm uploading all the logos to [this folder ](https://drive.google.com/drive/folders/1rL46Rw9JXsn6YbkmzMnx7PHNlLtnxCcp?usp=sharing). 
Couldn't find Yahoo news! logo. 

We still need to add a few more: 

- [ ] FiveThirtyEight 
- [ ] LA Times
- [ ] ProPublica
- [ ] San Francisco Chronicle
- [ ] CNN 
- [ ] Columbia Journalism Review 

I also updated the spreadsheet with the links and some information. It'd be great if you could help filling out the rest of the info. Thanks!!

**Comment by kissane** [comment]
Leaving this up until we have it implemented in V2
