### ISSUE TITLE
Broken Markdown on Press section in Homepage

### ISSUE THREAD

**Issue by olivierlacan** [COVID19Tracking/website#220]
![image](https://user-images.githubusercontent.com/65950/77778909-20d42c00-7028-11ea-9e47-5d3e5ebce372.png)

**Comment by webmasterkai** [comment]
The `title` field was missing in this particular instance.

The [sheet](https://docs.google.com/spreadsheets/d/1-lvGZ3NgVlda4EcF5t_AVFLnBqz-TOl4YZxYH_mJF_4/edit?usp=sharing) was locked down so only Erin and Jeremia can mark items for publishing on the site.

I added https://github.com/COVID19Tracking/website/commit/c3652fc4c3f86765b59e7ca64079f2f75d427982 to filter out items without title. That triggered a site rebuild and fixed the issue.
