### ISSUE TITLE
How is the total column calculated?

### ISSUE THREAD

**Issue by jamesprescott743** [COVID19Tracking/website#23]
There is either a problem with the Total column in the spreadsheet, or it should be documented better.

I would assume it should be (Pos + Neg + Pending) but that is currently 2083+15170+1152=18405 while the Total is 18311.

On the "US Daily 4pm" tab the totals from 3/4 - 3/9 look good but after that they don't add up.

Last updated: 3/13 18:03 ET
Positive | Negative | Pos + Neg | Pending | Death | Total
2083 | 15170 | 17253 | 1152 | 46 | 18311

**Comment by careeningspace** [comment]
Looks like we had a data error in our sum for MD. Was entered as 17 but should have been 111

**Comment by hammer** [comment]
That's my fault, I tried to carry forward some negatives that had been left out in previous tallies and was not careful enough. Thanks for the fix @careeningspace!

**Comment by kissane** [comment]
Thanks, all, closing this one.
