### ISSUE TITLE
Adding a simple blog

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#236]
I know it's a bit late to slap more things into the V2 site, but it would be lovely to get a blog in so that Alexis doesn't have to tweet 500 times each day. Should be old-school reverse-chron, and it would be nice if we could preview the most recent post from the new homepage, which, of course, is still a bit TKTKTK. (I will try to settle it this afternoon.)

Link in the footer nav is plenty of visibility right now, and we just need markdown and a way to get images in without sending Alexis to Github. Very small team will be using it. Bring on the questions!

**Comment by kevee** [comment]
This should be pretty simple, especially as we move to Gatsby. Some thoughts:

We *can* use Netlify CMS for this, but handling images will cause more technical debt on our side.
We can also use a hosted headless CMS, like Contentful, etc. This does add yet-another-external-service, but it allows us to offload a lot of work.

**Comment by kevee** [comment]
I'm moving forward with Contentful, @kissane you should have an invite to a Contentful space. Here's a preview of the site with the two sample blog posts currently in that space:

https://5e82184b7278cc0008e120e1--goofy-tesla-43452a.netlify.com/blog/

**Comment by webmasterkai** [comment]
I might be a little late, but why are we adding yet another content stream? What image handling do we need that Netlify can't handle?

**Comment by kevee** [comment]
We're live! Closing.
