### ISSUE TITLE
Finalize the way we handle fonts

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#240]
@schwartzadev mentioned this in discussion with @kevee in Slack—I promise @beep and JSM are going to have Thoughts and Feelings on this. Let's get this nailed down once we're in the swing of things on Monday.

**Comment by jasonsantamaria** [comment]
I think I missed the convo in Slack, but am happy to help with thoughts if I can!

**Comment by jasonsantamaria** [comment]
Some areas that need typographic attention:

- [ ] `or` between the hero button and "Learn About the Data" link should be the same size as the button label and text (currently looks larger)
- [ ] Nav text should align vertically to (roughly) the middle of the logo
- [ ] Hero button bg should be `#8CC7F4` and label text should be `#012656`
- [ ] Text link color should be `#575AAD` and I suggest `#8B8DC7` for a hover/active color
- [ ] All of the typography below the hero looks like it will need some spacing (and line-height) help

I'll leave the last one for @tealtan and @beep to weigh in on, I'm not up on the latest content and the staging and comp are different.

**Comment by kevee** [comment]
I'm putting those changes to the homepage into PR #251

**Comment by kevee** [comment]
@jasonsantamaria - Implemented those changes. We don't have `#012656` in our [color pallet ](https://goofy-tesla-43452a.netlify.com/__storybook/?path=/story/colors--main-colors) right now, so I used our darkest "main" color.

**Comment by kevee** [comment]
And the nav alignment is being covered in #254

**Comment by jasonsantamaria** [comment]
> @jasonsantamaria - Implemented those changes. We don't have #012656 in our color pallet right now, so I used our darkest "main" color.

@kevee Apologies! I think we specced out a palette but it may not have gotten into development. I've documented it over here #256

**Comment by kevee** [comment]
New fonts provided by Allen and colors by @jasonsantamaria are merged in gatsbyjs.
