### ISSUE TITLE
New state grades

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#242]
Got to get the new ones that incorporate the outcomes data finished from Alexis and up on the new site

**Comment by schwartzadev** [comment]
I'm game to tackle this on the implementation side. I'll need to touch base with Alexis about the latest updates to the grading system

**Comment by schwartzadev** [comment]
Can we group this in with the state notes, external links, etc.?

Do we have a finalized design for the `states` page and/or the individual `state` pages for presenting that data? I know there were some slack discussions about dropdowns, but I'm not sure where that ended up. @beep @tealtan @ JSM

**Comment by kissane** [comment]
@schwartzadev I believe we do have it for `/data/` but not sure about the individual states. Pretty sure @beep will know.

**Comment by schwartzadev** [comment]
Checking in again -- I'm on this still. I'll probably work on it after the launch tomorrow.
