### ISSUE TITLE
Launch plan for website v2

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#244]
What day/time are we imagining going live? What are the steps and pieces? Who needs to be on deck to get it done and help catch problems?

**Comment by kevee** [comment]
Overall steps:

1. In Netlify, add a branch deploy for `gatsbyjs`
2. Test Netlify CMS in our main repo (the config at `static/admin/config.yml` is pointing at the `gatsbyjs` branch for testing)
3. Change the Netlify CMS config to point to `master`
4. Merge `gatsbyjs` into `master`
5. Change the Netlify build command to `npm run build` (although it's ignored because of a `netlify.toml` file)

**Comment by kissane** [comment]
Thank you! Here are more questions: Who do we need in the room while this happens? @kevee, @webmasterkai, @beep, @schwartzadev, me?

What is the lowest-traffic time of day we can all be here? I can be here anytime in any US time zone.

**Comment by beep** [comment]
I’m very down to help with launch. (I can’t run gatsby locally yet, but I can provide design/UI spot-checkin’ assistance.)

I have a call scheduled from 2–3pm ET tomorrow, but I can move it if that’s the most convenient time for launch. Otherwise, I can make myself available whenever!

**Comment by schwartzadev** [comment]
I am _not_ the devops person on this project (:point_right: @kevee , @webmasterkai ) -- I can sit out that side of things for sure.

That being said, if y'all want me around, I would love to be, I just don't think I would be a major value-added on the implementation side.

Once we choose a time, we should probably put something up on Twitter, and maybe a banner on the site. Food for thought.

**Comment by kissane** [comment]
I mean, I used to always launch at like 3am ET because I ALWAYS fucked it up, but I approve of trying not to fuck it up instead. Do we want to tentatively open a launch window of tomorrow (Tuesday) after the big 4pm (ET) data drop? We'd been talking about "morning" but with the dashboard work to do, I think we'll need the extra hours.

**Comment by beep** [comment]
@kissane 4pm ET (or thereafter) works for me!

**Comment by kissane** [comment]
Noting that the above plans are being reformed in the Slack

**Comment by kissane** [comment]
OK, we're looking at a planned launch for V2 at 12pm ET Tuesday, with @kevee @beep @webmasterkai and me running the various parts of the launch list. That means 10am ET is our go/no-go time—if we have only tiny tiny things left open at 10am, we can move into a final check at 11am ET. If we got things open at 11am ET, we reschedule for evening or (more likely) Wednesday morning.
