### ISSUE TITLE
Contributing Page

### ISSUE THREAD

**Issue by webmasterkai** [COVID19Tracking/website#25]
It would be great to have some words on how a person or small team can contribute to the project.

Some ideas

* How to help collect/record data.
* How to help with website/graphics.
* How to bug public officials to improve/increase reporting of data and boost quality.

**Comment by kissane** [comment]
BTW I'm not ignoring this, we're building the onboarding docs and capacity to actually help people do the work once they arrive.

**Comment by webmasterkai** [comment]
@kevee has also suggested a project-wide contributing/code of conduct/governance document might be order.

**Comment by kissane** [comment]
CORRECT please flag that to Amanda French and Marie Connolly

**Comment by schwartzadev** [comment]
Agreed 100% -- at the very least, some details about how new contributors can get involved and some defined processes would be awesome. (Issue templates, committing to master, etc. etc.)

**Comment by kissane** [comment]
We got an onboarding team that can do both

**Comment by webmasterkai** [comment]
Perhaps we could start with https://www.contributor-covenant.org/version/2/0/code_of_conduct/ for code of conduct.

**Comment by kevee** [comment]
Let's split this up a bit, Code of Conduct and broad contributing/onboarding should be covered under the entire project, but let's focus this issue on just the nuts-and-bolts of how to contribute to the website repo.

I've taken a [first crack at it here](https://docs.google.com/document/d/1pLlbYYX6c1gmfedQ9Q9VkQ3FPAYuTRz1veQ1iAPMdDA/edit?usp=sharing), largely rewritten from a few other open-source projects. Sharing edit access with you both.

**Comment by kevee** [comment]
🎯[Some inspiration](https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md)

**Comment by kevee** [comment]
I opened a [code of conduct issue](https://github.com/COVID19Tracking/issues/issues/52) in the larger "issues" repo.
