### ISSUE TITLE
Update Twitter/social card to match new design

### ISSUE THREAD

**Issue by beep** [COVID19Tracking/website#253]
Per [@hammer’s comment in Slack](https://5e81ee0f8daa4900083bc27f--goofy-tesla-43452a.netlify.com/), we should update the opengraph preview card to match the new design.

(Ping #245)

**Comment by kevee** [comment]
How about just use the logo?

**Comment by jasonsantamaria** [comment]
Yep, I think the logo (maybe on the hero purple with pattern) with the site's hero text either in the image and/or as the site description?
