### ISSUE TITLE
Adjust nav design

### ISSUE THREAD

**Issue by tealtan** [COVID19Tracking/website#254]
This is visual feedback for the amazing nav work coming together for v2!

For Now
----

**Top nav**
- [x] Logo should be 176px wide (that should math out to 50px high)
- [x] The nav items should be vertically centered with the logo, and horizontal spacing should be 30px. I’m not a fan of using vw for the padding since that will vary so much – open to discussion here but since we’re using rem units elsewhere for spacing I’d lean towards following suit. (px is fine too)
- [x] Nav items should be title case
- [ ] The nav left/right padding should go down to 30px around the 1024px wide viewport size (based on eyeballing, feel free to adjust), plus turn into the collapsed nav sooner, maybe around 800px viewport size (again, feel free to adjust)

~~**Header (homepage)**~~
- [x] The background image should start at the top of the page – the background on subpages look solid. (We probably need to adjust where the background image is applied in order to get this effect).
- [x] There should be less space above and below the buttons – 70px above, 140px below on desktop, cut both values in half on mobile.
- [x] The button should be wider (we were aiming for 25% of the centered content container on desktop and 100% on mobile)

~~**Header (subpage without subnav)**~~
- [x] Add spacing above and below page header – 70px above, 35px below on desktop, cut both values in half on mobile.
- [x] The page header should be smaller on mobile (28px converted to rem units)

~~**Header (subpage with subnav)**~~
- [x] Add spacing above and below page header – 70px above, 35px below on desktop, cut both values in half on mobile.
- [x] Once the subnav starts to wrap or collide with the page header on smaller viewports (eyeballing around 1024px wide), let’s move the subnav underneath the page header, keeping the tab style until we get to the mobile viewport size.
- [x] The page header should be smaller on mobile (28px converted to rem units)
The subnav looks great btw! Some tweaking for mobile:
- [x] Font size should be smaller (13px converted to rem units).
- [x] The border radius should be 5px on all viewports.
- [x] The subnav should appear below the page header.
- [x] Not sure if we have this yet, but the subnav should be scrollable horizontally if the viewport is not wide enough. --- ✅ already done (@schwartzadev )

~~**Footer**~~
- [x] The Github, Twitter, RSS links should appear on the right side at larger viewports, like the items in the top nav.
- [x] The links should not have underlines.
- [x] Any spacing or type size adjustments to the top nav should be carried over in the footer.

Thank you all for jamming hard on this! Happy to clarify or discuss anything further, and to review this when ready.

----

For Later (moved by @schwartzadev )
----

**Top nav**
- [ ] Ideally, the collapsed nav should say "Close" when open – not a big deal if we do this later
- [ ] Also ideally, the collapsed nav appears as an overlay (white links on black bg) – let’s tackle this later

**Homepage Hero**
- [ ] Move "or" to the same line as "Learn..." (see [here](https://user-images.githubusercontent.com/18607205/77950522-d9e37200-7285-11ea-9d0d-464b07e8af58.png)) on mobile

**Comment by schwartzadev** [comment]
Closed with #257
