### ISSUE TITLE
Color palette updates

### ISSUE THREAD

**Issue by jasonsantamaria** [COVID19Tracking/website#256]
This is a work in progress that may need to keep evolving as we see it in use, but for the moment this is the latest and greatest. 

_All color ranges listed from darkest to lightest_

**Base palette**

```Plum:
111354
31347A
575AAD
8B8DC7
D1D1E8

Blueberry:
012656
004399
0091EA
8CC7F4
E2F1FC

Slate:
313638
3D4245
4C5559
5B666B
6F7E85
849096
95A0A6
B2BBBF
D0D7DB
EDF1F2
```

**Messages**

```
Info:
5E4F24
FEF9CD

Sync:
264A8C
DDEFFC

Alert:
802509
FEDCD2
```

![Color palette](https://user-images.githubusercontent.com/128280/77942741-11ecb400-728a-11ea-878a-a271ff1dff05.png)

**Comment by kevee** [comment]
Looks like Blueberry's `#8CC7F4` is duped...

**Comment by jasonsantamaria** [comment]
Fixed!
