### ISSUE TITLE
Update footer to match design

### ISSUE THREAD

**Issue by beep** [COVID19Tracking/website#259]
Figured this is on folks’ radar, but just to log it for launch: the footer currently on the dev site is showing my original design for the footer. We should make sure it matches the current spec/layout before launch!

<img width="1440" alt="new footer design for the covid tracking project" src="https://user-images.githubusercontent.com/124493/77962344-6ce1d380-72a9-11ea-846c-21bcefa36ed7.png" />

**Comment by kevee** [comment]
Some of this is covered in #254
