### ISSUE TITLE
"See also" links?

### ISSUE THREAD

**Issue by metasj** [COVID19Tracking/website#26]
For commonly confused domains (covidtracker, coronatracker?), it might be worth having a banner of the form 
 "_for the global arcgis visualization, see plague.com._"

Perhaps this can be merged w/ other discussions of how to link out to existing visualizations, since most of these are quasi-relatime visuals with their own data sources

**Comment by kissane** [comment]
This is smart, I feel like we should link out to the obvious suspects now and sort our full viz plan after, bc there are a bunch of open questions about that part. @metasj could you give me a list of your obvious candidates and I'll grab mine and merge and add them?

**Comment by kevee** [comment]
I get the feeling like this is not needed as the project has grown in size and stature. I'm closing this issue and referencing it in a strategy document for the next version of the site so it's not lost.
