### ISSUE TITLE
Add state population data to the website

### ISSUE THREAD

**Issue by preislerd** [COVID19Tracking/website#260]
As a consumer of the website, when I see the test and outcome numbers, I always ask myself, what is the population we are talking about.  It would be great to have a population number next to the state names, or below the state boxes.  And the same for US total.  Ideally it would be a trusted static data source that provides context for the testing data (like Census data).

I've asked @metasj to look into collecting and adding the data to the repo.

Other thoughts --
1. It should be on the website as described above.
2. It should be available in a public sheet -- probably in the sheet that has "todays" or "current data".
3. It should be available in the API.

**Comment by metasj** [comment]
I added mid-2019 census population counts to the States [worksheet](https://docs.google.com/spreadsheets/d/1MvvbHfnjF67GnYUDJJiNYUmGco5KQ9PW0ZRnEP9ndlU/edit#gid=1208387230); we should be able to easily draw from that into the site.  I'll post the source file to associated-data for safekeeping.
