### ISSUE TITLE
API: Migrate API as a build step before site compiles

### ISSUE THREAD

**Issue by webmasterkai** [COVID19Tracking/website#266]
I think the first Netlify function is probably a web-hook endpoint that fetches the current data for us and states from the sheets and saves it to the repo after some slight processing.

After that we'll add a build step to the website that takes that file and splits it out into a bunch of other files to serve as the basis of the API.

Possible structure:

- /data/current/us.json (replaces /api/us)
- /data/current/us.csv (replaces /api/us.csv)
- /data/current/states.json (replaces /api/states)
- /data/current/states.csv (replaces /api/states.csv)

Other pages that were query args could be like:

- /data/current/state/AK.json (replaces /api/states?state=AK)

We will then update the old Cloudlfare endpoints to act as a simple 301 redirect to the new static file locations based on the request.

**Comment by webmasterkai** [comment]
We are going to move forward with building all json asset/data files at site compile time. The `/functions` dir will have code related to any interactive API code like GraphQL. The `/build` dir will contain code related to building the json files. Both will have dedicated package.json files to maintain dependencies.

I'm now thinking a structure more like:
- /data/us/current.json
- /data/us/daily.json
- /data/states/current.json
- /data/states/daily.json
- /data/state/[state]/current.json
- /data/state/[state]/20200329.json

**Comment by pspeter3** [comment]
Perhaps we want to rename `/build` to `/generate` since `/build` is sometimes used as an output directory?

The structure looks good though wondering if we want `/data/state/:state/:yyyy-mm-dd.json`?

Also do we want `/data/us/:yyy-mm-dd.json`?

**Comment by pspeter3** [comment]
I assume there will also be a CSV equivalent for each of these?

**Comment by pspeter3** [comment]
I would like to propose `/data/:version` as a prefix. That way we can write multiple versions. Unsure how we do this for GraphQL. I think GraphQL has its own scheme for deprecations.

**Comment by pspeter3** [comment]
Based on discussions in Slack, the team thinks that not versioning the API and only appending fields is the easier way to go. This means that the generated data and GraphQL api will follow the same versioning and deprecation scheme.

**Comment by webmasterkai** [comment]
Okay, I'm tired but I think I got most of the code that creates API assets added to the repo https://github.com/COVID19Tracking/website/tree/api-2/build

**Comment by kevee** [comment]
Initial feels is: run npm run [get-api-thing] - then it writes to like _data , then Gatsby builds off of that data, then we just copy _data into /public/api

**Comment by kevee** [comment]
We also need to add some jest tests or something that pulls all the main API endpoints and does some data quality heuristics (number of items in array? object composition?). This would run after the build and before Gatsby runs, so that if the Jest test fails, the build is flagged as failing and we don't break anything.

**Comment by kevee** [comment]
Fixed in #336
