### ISSUE TITLE
Add information on diagnostic sensitivity and specificity

### ISSUE THREAD

**Issue by hammer** [COVID19Tracking/website#27]
Cf this thread https://mobile.twitter.com/LizDNature/status/1238653778745856000

**Comment by hammer** [comment]
Also cf https://mobile.twitter.com/nataliexdean/status/1238518203736903680

**Comment by hammer** [comment]
https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3546052

**Comment by kissane** [comment]
I've started work on this, but I will need a qualified science person to bless what I write, and that will also not happen before this evening. My goal is 1-2 paragraphs that will live on the Methodology page on the website.

**Comment by kissane** [comment]
Hey @hammer I started this here https://docs.google.com/document/d/12jzOzsAoCsXn2uN_zOR3CAydD-YPGr0vQdUPPbgFSbM/edit?usp=sharing

**Comment by kissane** [comment]
Also Kathy Paur is editing this, she's wonderful and has the teaching + bioscience expertise

**Comment by kissane** [comment]
I saw a lot of notes flying in Slack about this, I am hoping we can add either an edit of the mini-explainer I made OR an alternate version sometime Monday.

**Comment by kissane** [comment]
Sooo we stalled out on this. @hammer I think Kathy had some things for you to asnwer, but IDK. Is this request just to put our guess at the accuracy of the current tests in the US onto the site, rather than explaining to non-healthcare journalists/general readers what sensitivity and specificity are? I feel like that information is…super dynamic. Let me know what you're after.

**Comment by kevee** [comment]
@hammer  - this issue has gone stale, do you think this is important, and if so, what's the next step?

**Comment by imart27** [comment]
Can I bump this? Just looking for more accurate info to get in the public eye.

Even less specific than specificity and sensitivity, is the type of test being used and results particular to each tests. Knowing this could seriously help the progress we're making in combating the virus.

I don't know how, in this day and age, our public health system doesn't have the ability/requirement to compile that information and make it available to the general public.
