### ISSUE TITLE
Update Slack and Twitter branding

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#279]

**Comment by schwartzadev** [comment]
Not sure if this goes here, but the font on the current URL image (the one that shows up when you paste the URL into slack -- I don't know the name of this?) is not the preferred one for the project. I think it is just generic sans-serif. Probably a zero priority issue.

**Comment by kissane** [comment]
Wait I should not close this until I actually DO this on Twitter dot com.

**Comment by kevee** [comment]
Done in twitter!
