### ISSUE TITLE
Take me to the (very plain) data -- link

### ISSUE THREAD

**Issue by Dsmith-Tucson** [COVID19Tracking/website#28]
The "Take Me to the Data" link goes to the raw spreadsheets, not the fancy /notes/ display that's linked from the footer.

**Comment by kissane** [comment]
We shouldn't remove the link to raw but the data page is probably now good enough to add a link to it, yeah. Let me look at this.

**Comment by webmasterkai** [comment]
Proposed solution in PR #31

**Comment by kissane** [comment]
OK, now we have pretty data, spreadsheet, and API up top. Closing this for real now.
