### ISSUE TITLE
Update front page viz thumbnails

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#280]
As discussed on [Slack](https://covid-tracking.slack.com/archives/C010N48RY73/p1585668517267200?thread_ts=1585593301.094100&cid=C010N48RY73), let's take out map with dark background because it looks unbalanced. 
Let's do, from left to right: NYT chart, Politico's map and WSJ chart. Here's a screenshot and links: 

![thumbs](https://user-images.githubusercontent.com/39416238/78047335-36a66180-7346-11ea-8071-1b4f7e4d5847.jpg)

https://www.nytimes.com/interactive/2020/03/17/us/coronavirus-testing-data.html 

https://www.wsj.com/articles/how-the-cdcs-restrictive-testing-guidelines-hid-the-coronavirus-epidemic-11584882001 

https://www.politico.com/interactives/2020/coronavirus-testing-by-state-chart-of-new-cases/

**Comment by schwartzadev** [comment]
#283 will close this
