### ISSUE TITLE
Mobile: logos, nav, and background

### ISSUE THREAD

**Issue by friej715** [COVID19Tracking/website#287]
(Rolling these three into one since they seem pretty small--let me know if you want 'em broken up more!)

Tested on my iPhone 6S's Safari. Maybe small enough to get in for #267?

- [x] Press logos are not centered on page.
- [x] Mobile nav gets cut off on Most Recent Data page (again, iPhone 6S, fwiw)
- [ ] Tiny white line to the right side (probably due to background tiling)

![Image from iOS (1)](https://user-images.githubusercontent.com/1028403/78068473-75e4aa80-7366-11ea-999b-12cf47ddabb5.png)
![Image from iOS](https://user-images.githubusercontent.com/1028403/78068478-78470480-7366-11ea-8f7b-ee2d7c2e277b.png)

**Comment by friej715** [comment]
Maybe too small to worry about, but the background size now jumps based on whether the menu is open.

![RPReplay_Final1585684536 2020-03-31 15_56_28](https://user-images.githubusercontent.com/1028403/78069528-433bb180-7368-11ea-90a6-52b4e5735004.gif)

**Comment by schwartzadev** [comment]
These are great -- thank you!

>  Mobile nav gets cut off on Most Recent Data page (again, iPhone 6S, fwiw)

I'm going to check this one off -- this is by design

**Comment by schwartzadev** [comment]
It looks like by now (8a638d8c75a32dc515f72ef71d0d4cd883341881 on `gatsbyjs`), the alignment issue is fixed. I'm not 100% sure where it happened, but hey :man_shrugging: Here it is on (simulated) iPhone 6, iOS 11:
![image](https://user-images.githubusercontent.com/18607205/78086284-b64e2380-737a-11ea-82fc-b4a8f0867f75.png)

**Comment by schwartzadev** [comment]
I can't seem to emulate the issue with the background tiling. @friej715 is there a chance that you could see if other sites seem to have similar behavior on that device?

It could be useful to narrow down the issue to that particular device, if possible.

Thank you :raised_hands:

**Comment by friej715** [comment]
You mean the white line thing @schwartzadev? It seems to be gone now 👍

**Comment by schwartzadev** [comment]
Awesome!
