### ISSUE TITLE
Post launch: repository access control, issue templates

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#306]
We're all a ton of professional, dedicated, detail-oriented, can-do people. 😇 But sometimes I forget which remote my Git is pointing to, and that 👻scares me. Post launch I'd like to do some house cleaning:

- Implement branch protection rules for `master`
- Add a `staging` branch that is enabled as a branch deploy in `Netlify`
- Evaluate how to prevent staging PRs from leaking environment variables - probably a Github action that greps for like "ENV_NAME" changes
- Make a formal (I mean, like not tooooo formal 👔) process for deploying from `staging` to `master`
- Re-evaluate Github access controls. Adding people who contribute to the org is totes fine, but we need to just clamp it 🗜 down a bit
- Add Github Issue templates (look [at what Gatsby does!](https://github.com/gatsbyjs/gatsby/issues/new/choose)) - we get a lot of issues that need to be re-reouted. This should help.

**Comment by schwartzadev** [comment]
Yes, yes, yes! I'm on board with all of these.

> Make a formal (I mean, like not tooooo formal :necktie:) process for deploying from staging to master

I would be in favor of one other person doing a code review on any changes to master -- that's my 2c :+1: 

I'm going to branch off on the issue templates -- I've been thinking about that one for a bit, too.

**Comment by schwartzadev** [comment]
@kevee where are we on these items?

Does this look right?

- Implement branch protection rules for `master`
- Add a `staging` branch that is enabled as a branch deploy in `Netlify`
- ~~Evaluate how to prevent staging PRs from leaking environment variables - probably a Github action that greps for like "ENV_NAME" changes~~
- ~~Make a formal (I mean, like not tooooo formal 👔) process for deploying from `staging` to `master`~~
- ~~Re-evaluate Github access controls. Adding people who contribute to the org is totes fine, but we need to just clamp it 🗜 down a bit~~
- ~~Add Github Issue templates (look [at what Gatsby does!](https://github.com/gatsbyjs/gatsby/issues/new/choose)) - we get a lot of issues that need to be re-reouted. This should help.~~

**Comment by kevee** [comment]
Closing, we have branch protection and we're going to see if that works enough before introducing a staging branch for now.
