### ISSUE TITLE
Slightly weird alignment on homepage

### ISSUE THREAD

**Issue by friej715** [COVID19Tracking/website#313]
Noticed on my iPhone 6S, Safari. Visible to varying degrees on different Chrome window sizes.

![IMG_1641](https://user-images.githubusercontent.com/1028403/78161210-1d1f1b80-7413-11ea-97cb-b10e3412e14f.jpg)

**Comment by beep** [comment]
It looks like each item is a flexbox’d div, with an inner div styling the bullet. Switching over to lists and background images might simplify things a bit. (Or, if the `ul` switch isn’t an option, background images.)

**Comment by beep** [comment]
(All that said, the _super_ quick fix would be something like `flex: 0 0 30px` on the icons)

**Comment by kevee** [comment]
Fixed!
