### ISSUE TITLE
Outdated Residents out of state FAQ section

### ISSUE THREAD

**Issue by olivierlacan** [COVID19Tracking/website#315]
This paragraph is outdated and needs to be amended or removed: 

![image](https://user-images.githubusercontent.com/65950/78162905-90c22800-7415-11ea-825e-0ea510e56405.png)

> For example, Florida reports “FL resident diagnosed & isolated out of state.” In this case, we exclude this from our positive case count, because the individual is not isolated in the state.

We may have done this in the past but what Florida now reports as Total Tests is (currently) equal to Total PUIs (Patients Under Investigation) which includes these three categories: Residents, Non-residents, Residents out of state. 

We *could* remove residents out of state but that would not really be worth or time for the potential confusion it brings because of how low those resident out of state counts actually are (at least for Florida): 

![image](https://user-images.githubusercontent.com/65950/78163065-cff07900-7415-11ea-9d27-0fe745294e48.png)

**Comment by kevee** [comment]
@olivierlacan  - do you suggest we just remove this sentence from the FAQ?

**Comment by kevee** [comment]
Removed content in Contentful.
