### ISSUE TITLE
Tiny typo in FAQ about U.S. Daily

### ISSUE THREAD

**Issue by olivierlacan** [COVID19Tracking/website#316]
We're missing a space after the anchor link and I can't find this page in the codebase so I'm guessing it's hosted somewhere else: 

![image](https://user-images.githubusercontent.com/65950/78163466-6c1a8000-7416-11ea-993b-67aa06eb7cbd.png)

**Comment by kevee** [comment]
Fixed in Contentful. Should be live sooon.
