### ISSUE TITLE
Feature: implement responsive table pattern

### ISSUE THREAD

**Issue by beep** [COVID19Tracking/website#317]
Currently, we’re overflowing tables once they’re too wide for their container. Which is great! But _ideally_, we’d have some sort of responsive table solution that manages table adaptation a little more gracefully across viewports. (This will be especially important once the outcomes data lands.)

*Historical note*: @schwartzadev implemented [tablesaw](https://github.com/filamentgroup/tablesaw/) in https://github.com/COVID19Tracking/website/pull/221, and found we got hit with some surprising but [serious performance slowdowns on our table-heavy pages](https://github.com/COVID19Tracking/website/pull/221#issuecomment-606154097). I’m not sure if this is an issue with tablesaw, gatsby, or some combination of the two.)

**Comment by beep** [comment]
Personally, I think that as long as our solution maintains a tabular structure _as much as is appropriate_, then we’re in good shape. (Like, if we need to render DLs on smaller screens, awesome—but if we have the room for tables, we should use them.)

**Comment by preislerd** [comment]
I felt like the previous **mobile experience** of a stacked table per state fitting in my screen (at least in portrait mode) was significantly better.  However if I switch to landscape everything looks good.  Just not my preferred mobile web page browsing experience.

**Comment by olivierlacan** [comment]
I would agree with @preislerd. The header-to-content width ratio of some of our tables doesn't really make sense in portrait mode especially with a table column like States Tracked (which I think could arguably be changed to something less intrusive maybe) which ends up pushing far more relevant information off to overflow land. 

![IMG_3610](https://user-images.githubusercontent.com/65950/78210461-4756f480-7478-11ea-9dca-11587e8ea712.PNG)

This performance issue in #221 seems odd. I don't think even 60 tables should cause a 30 second paint but I could be wrong. @beep if you need any help tomorrow to setup Gatsby to profile somethings locally let me know.

**Comment by schwartzadev** [comment]
Agreed with both of y'all -- the current solution is...not great. Maybe I
had other performance issues with tablesaw -- I encourage y'all to explore
its performance as well.

For what it's worth, @kevee noticed that tablesaw was also not deploying
properly -- I'm sure Kevin can speak about this more but I think it was an
issue with deprecated DOM manipulation? Regardless, I think gatsby build
was having trouble running.

I think we may need different solutions for different tables: the summary
tables have different dimensions and communicate different information than
the historical tables do. The priorities for mobile are likely different
between those two.

In the interim, I would support re-ordering the table columns in the table
Olivier shared. I don't think the number of states tracked is more
important than the # of positive and negative cases.

Also for that same table, maybe we could freeze the dates column and then
scroll the rest?

**Comment by kevee** [comment]
Tablesaw was a little fragile within a React environment, but if you all have specs I'm sure we can easily rebuild that functionality with some React state stuff. Other possibilities?

 - For some tables, provide minimal information, and allow linking to a separate page with more info that we can display without a table. This is less desirable when you want to quickly compare rows, I guess.
 - Make table rows "expandable" in mobile - you see three items and click to see more data on the row you are interested in?

**Comment by kevee** [comment]
Other idea: the "summary" is just a single row, you don't need a table at all. You can use flex columns, headers, and DL:

![image](https://user-images.githubusercontent.com/270536/78371557-2258a380-7596-11ea-8d6d-2f4f8c5ae9c8.png)

**Comment by kevee** [comment]
@beep & @schwartzadev - Since we are adding outcomes data too, the history tables are getting crazy wide, so I took a crack at a responsive design keeping the table structure the same, but using flex, etc. This was a quick hack, so definitely needs to be cleaned up.

I defined certain cells as "required," then made the other cells hidden (we eventually should do this so tables operate the same in screen readers, but I just used display: none for now) until a button is clicked. This can easily be made accessible, and degrade sans JS by applying a class to the table using javascript that makes all this work.

I **still** think we need to start paring down the history tables and linking to a page per date though, as they are already getting overwhelming.

See it in action in the history table here: https://5e89d7edf4663f00069e2630--goofy-tesla-43452a.netlify.com/data/state/rhode-island

![image](https://user-images.githubusercontent.com/270536/78499216-57433280-771d-11ea-8b9f-810befa07858.png)

**Comment by kevee** [comment]
Also related to #185 - we are going to need to add more and more columns as we get more data. That is a good thing, but I think we'll eventually need some options to control column displays.

![image](https://user-images.githubusercontent.com/270536/78500478-a50f6900-7724-11ea-93a1-3c19a6e5eab8.png)

**Comment by jasonlcrane** [comment]
I know I'm an outsider here, but I like where you were going with the "summary" example above, and with the history tables idea. The data points in those super-wide tables are not all directly related to each other, or aren't being compared with each other, so I was playing around with an idea like this. Happy to help if I can.
<img width="494" alt="Screen Shot 2020-04-06 at 10 34 58 AM" src="https://user-images.githubusercontent.com/297528/78577234-64caec00-77f3-11ea-9b66-eaee4e55f6c5.png">

**Comment by toddparker** [comment]
Since these are only one row, we can probably just omit tablesaw and add the markup for the stacked view in the starting markup for each table to avoid needing any JS. Rough sketch but this shows using a H3 for each sub-section and spans for the TH content. Sorry for the hacky CSS -

https://jsbin.com/pewiluk/31/edit

**Comment by toddparker** [comment]
For responsive tables, I think the stack mode is best when you're not comparing rows so it's good for the state detail pages. Fo the overview (all states), I think you want to compare across rows and do some sorting so we might want different approaches for these views.

I made a second example showing how we could handle a single, large table with lots fo columns and rows. This table uses standard tablesaw features such as sorting (on second header row), grouped headers, auto-hiding of columns based on priority, dropdown to pick which columns to see, minimap of which columns you are seeing of the total. This might be a good way to show the state overview in a compact grid. If the columns don't fit, there is side scrolling.

https://jsbin.com/zaxuhoz/edit

**Comment by kevee** [comment]
This is **super important**, so I closed and merged it into #457.
