### ISSUE TITLE
Should there be an escape hatch link on the footer logo? 

### ISSUE THREAD

**Issue by olivierlacan** [COVID19Tracking/website#318]
![image](https://user-images.githubusercontent.com/65950/78163978-14304900-7417-11ea-8b19-b13841578ba4.png)

Not a strong opinion but it would help in a "go back to top and back home" sort of way. Seems odd to see a mirror of the top of the site logo with no hyperlink. I don't feel strongly about this so feel free to insta-close with "this on purpose, friend". 😄

**Comment by beep** [comment]
Whoops, missed this when I was drafting https://github.com/COVID19Tracking/website/issues/319. _Agreed_ that this should be there, @olivierlacan—thanks for flagging this!

(I know this issue came first, but: do you mind if I close this to keep the discussion with the other footer enhancements?)

**Comment by olivierlacan** [comment]
Of course!

**Comment by beep** [comment]
Thanks, @olivierlacan! And sorry for the dupe on my end—really appreciate you catchin’ this.
