### ISSUE TITLE
Footer refinements

### ISSUE THREAD

**Issue by beep** [COVID19Tracking/website#319]
A few design-related items, comparing the current footer to [the design spec](https://www.dropbox.com/s/41azsi92oh724m6/covidrefresh%20-%202020%200330%20EM.sketch?dl=0) (Also screenshotted below!):

- [x] - Ensure the bottom/top padding on the footer is equivalent. (That is, the content should be vertically centered.)
- [x] - Links should be underlined.
- [x] - The focus state is currently a little hard to read.

Content questions!

- [x] - We should have a “Back to top” link! (Also, per the design, it should be the only bolded link in the footer.)

- Question: do we still have an RSS feed? Can/should we link to it here? - NOPE!

![Footer](https://user-images.githubusercontent.com/124493/78164308-9456ae80-7417-11ea-9297-bc4d02672692.png)

**Comment by kevee** [comment]
I think the deploy preview looks close, please let me know if anything else needs fixing

**Comment by beep** [comment]
@kevee Okay _real_ basic question, sorry: where’s the deploy preview? (Not seeing one on https://github.com/COVID19Tracking/website/pull/323)

**Comment by kevee** [comment]
@beep - it's that unhelpful "Details" link that shows up next to "Deploy preview ready"

https://deploy-preview-323--upbeat-lovelace-3e9fff.netlify.com/

**Comment by beep** [comment]
@kevee Yeah, no, sorry: the entire section of PR checks was missing for me yesterday. But! They’re back now! And things look great 👍

**Comment by kevee** [comment]
Cool, merging!
