### ISSUE TITLE
Twitter/Website Card Ideas

### ISSUE THREAD

**Issue by webmasterkai** [COVID19Tracking/website#32]
<img width="1161" alt="Screenshot 2020-03-14 23 57 29" src="https://user-images.githubusercontent.com/969456/76708296-1af75600-66cc-11ea-9a3f-0d87da65d166.png">
<img width="520" alt="Screenshot 2020-03-14 23 55 21" src="https://user-images.githubusercontent.com/969456/76708299-1c288300-66cc-11ea-82e1-fb1f4a2b1e0f.png">
<img width="523" alt="Screenshot 2020-03-14 23 55 16" src="https://user-images.githubusercontent.com/969456/76708300-1c288300-66cc-11ea-90b7-b2dc579d7805.png">
<img width="548" alt="Screenshot 2020-03-14 23 55 09" src="https://user-images.githubusercontent.com/969456/76708302-2ea2bc80-66cc-11ea-994a-d8849807b7eb.png">
<img width="530" alt="Screenshot 2020-03-14 23 55 27" src="https://user-images.githubusercontent.com/969456/76708311-382c2480-66cc-11ea-8d95-256e7059f278.png">
<img width="702" alt="Screenshot 2020-03-14 23 54 57" src="https://user-images.githubusercontent.com/969456/76708325-51cd6c00-66cc-11ea-81a8-a57d3bf01974.png">

**Comment by kissane** [comment]
Thanks, @webmasterkai, I would like to get one or more designers to bless our type/image guidelines before we proceed with any more design work.

**Comment by webmasterkai** [comment]
Copy paste from Project identity doc
> - No stock photos, no virus photos, no photos
> - Keep it all extremely simple, reduce visual noise
> - Black and white and grayscale, def no bright colors at this time
> - Screenshots of spreadsheet are okay until we have something else

**Comment by kissane** [comment]
BTW, we have @beep with us half-time this week to help integrate design changes from elsewhere, finish the design system our original anonymous designer started, and get our loose ends tucked in.

**Comment by kissane** [comment]
I believe this is pending next week's design review, but @beep LMK if this is a separate thread and I'll get someone on it!

**Comment by beep** [comment]
@kissane No worries, I’m already tracking it as part of the bigger design review!

**Comment by kissane** [comment]
@beep Blessings, gonna close this for now.
