### ISSUE TITLE
People are missing the links to states on the big /data page

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#325]
I feel like we have a dropdown comped in at some point? We're getting sad tweets about missing these links from mobile users.

**Comment by schwartzadev** [comment]
Which links? 🤔 Here's what I'm seeing on mobile:

![image](https://user-images.githubusercontent.com/18607205/78194178-ab0dfd00-7439-11ea-83ea-4ac9ad6948c0.png)

**Comment by kissane** [comment]
Sorry, the quick links so people don't have to scroll forever. Someone objected to them and we nixed them, but I'm getting a lot of tweets and DMs. We had a dropdown suggested at some point to replace them?

**Comment by schwartzadev** [comment]
Ah yes -- the navigation. Silly me. :man_facepalming:  I'll throw something together for now, but @beep @tealtan @jasonsantamaria maybe you could design something beautiful for this down the line?

**Comment by kevee** [comment]
There's a dropdown in the sketch file that looks like a regular select element - I'd like to use something like [Reach's combobox](https://reacttraining.com/reach-ui/combobox) because it's got great a11y features

**Comment by schwartzadev** [comment]
Oooh Kevin that looks great -- are you thinking we use combobox to:then jump to the selected state (i.e. a user inputs the state name/abbreviation and then clicks on the result) or that we would filter based on the combobox result (i.e. a user inputs "New" and all results disappear except for New York, New Jersey, etc.)?

In the meantime, I just pushed #342  -- Kevin, if you're on board, please merge it for the interim 👍

**Comment by kevee** [comment]
I think option 1 - I'm merging your PR in a bit.

**Comment by beep** [comment]
> There's a dropdown in the sketch file that looks like a regular select element - I'd like to use something like Reach's combobox because it's got great a11y features

Sounds good. I’m not familiar with combobox; what’s the experience like if JS fails to load?

**Comment by schwartzadev** [comment]
...or if you don't load JS intentionally 😉

**Comment by beep** [comment]
(I knew I liked you, @schwartzadev 😉)

**Comment by kevee** [comment]
We can use the current select list that @schwartzadev built, hide it with a style in a `<noscript>` tag - the combobox component could degrade to a select element, but that would be useless without JS anyhow because you can't monitor events.

**Comment by beep** [comment]
> hide it with a style in a <noscript> tag

I think that’ll work if JS is actively disabled, but not if there’s some other condition that prevents JS from executing, right?

> the combobox component could degrade to a select element, but that would be useless without JS anyhow because you can't monitor events.

True! I guess I’d assumed the list of states would just be a list, and then styled in its `enhanced` state with a bit of overflow scroll. (Perhaps with that slick collapsible element pattern you’d showed?)

Sorry to be bringing so many questions to this! (I tend to be [pretty conservative](https://www.filamentgroup.com/lab/enhancing-optimistically.html) when designing stuff like this, heh.)

**Comment by kevee** [comment]
> I think that’ll work if JS is actively disabled, but not if there’s some other condition that prevents JS from executing, right?

True, I'll see what I can do to fix that in the PR.

**Comment by kevee** [comment]
Fixed in #391
