### ISSUE TITLE
List last update time per state, on the overview page

### ISSUE THREAD

**Issue by metasj** [COVID19Tracking/website#326]
As a site visitor, when I look at  https://covidtracking.com/data
I want to know when the data for each state was last updated (and an estimate of when it will _next_ update, if there's a daily tempo).  That could be lised alongside the table.  

Ex:
- Last update M/DD HH:MM, usually updates [at|around] HH [am|pm]

**Comment by schwartzadev** [comment]
Ooh -- the suggestion of when the state typically updates is a fascinating one. I think that we have that data somewhere, but I'm not sure if it's public. @webmasterkai maybe can you speak to that?

**Comment by kevee** [comment]
This is an issue being discussed at higher level - once we get state daily metadata this should be good to go.
