### ISSUE TITLE
add date to map state tooltip

### ISSUE THREAD

**Issue by goleary** [COVID19Tracking/website#327]
"another thing we should probably add to the toolip is date in case the reader stops the slider and starts hovering over stuff. politico did it in a nice way" - @julialedur 

![image](https://user-images.githubusercontent.com/16123225/78178107-f7dedd00-7413-11ea-8d42-c75e02827ce6.png)

**Comment by julialedur** [comment]
here's a sketch of the tooltip with date. I also underlined the variables with their respective colors so it's easier to identify them in the table 
![sketch-map](https://user-images.githubusercontent.com/39416238/78180608-05569000-7431-11ea-9dbb-689abe3859e3.jpg)

**Comment by goleary** [comment]
this has been done but it looks like there's a bug where it reports dec 31 for all tooltip dates. I'll look into this

**Comment by goleary** [comment]
fixed in `dashboard-gatsby`
