### ISSUE TITLE
change colors of map button 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#328]
let's make the selected button with white background and black text and stroke. it's cleaner this way 

<img width="392" alt="Screen Shot 2020-04-01 at 3 55 13 PM" src="https://user-images.githubusercontent.com/39416238/78180738-320aa780-7431-11ea-9575-58c1810d5713.png">

**Comment by kevee** [comment]
@goleary  & @julialedur  - Quick heads up on colors:

We actually have [official color swatches](https://covid19tracking.github.io/website-docs/?path=/story/colors--main-colors).

Those were unfortunately not selected with the idea of graphs/maps etc. in mind. I'd suggest that you reach out to @jasonsantamaria. Come up with a color swatch and we can add them in!

And then to use them in your code, you can do this:

In Javascript (like graphs and such):
```javascript
import colors from '../scss/colors.scss'

const amazingChartBackground = colors.secondaryDark
```

In SCSS:
```scss
@import '../colors.scss'

.awesome-chart {
  background: $color-secondary-dark;
}
```

**Comment by julialedur** [comment]
Hey Kevin! 
Thanks for the heads up! 
Will talk to Jason about it :)

**Comment by goleary** [comment]
the original issue is resolved. @julialedur perhaps you should open a new one to start using the swatches once #440 is done.
