### ISSUE TITLE
change labels to million [melba]

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#330]
now that we've reached one million tests, let's change labels for the chart below to million so they're not too long (eg 0.2, 0.4, ... 1 million)

<img width="594" alt="Screen Shot 2020-04-01 at 11 53 17 AM" src="https://user-images.githubusercontent.com/39416238/78181811-f7097380-7432-11ea-9b9a-9ab43b8a830b.png">

**Comment by julialedur** [comment]
also for new website: add legend, x-axis values and "Get this data from our API" as above

**Comment by friej715** [comment]
Something like this? (Using "million" still seems to be too long, at least in the build I have...) If yes I can make a PR.

![image](https://user-images.githubusercontent.com/1028403/78731699-6b01bb00-790e-11ea-88b1-f93b5cc5365f.png)

**Comment by julialedur** [comment]
almost! should be: [0, 0.5, 1, 1.5, 2, 2.5M] 
you can remove the "M" from all values except the highest

**Comment by gitjeff05** [comment]
Can this be closed? I am seeing it in the current preview.

**Comment by goleary** [comment]
sure, although I'm seeing a problem with how it's displayed. I'll open a new issue for it.
