### ISSUE TITLE
adjust page layout 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#331]
go back to text-graphic-text-graphic layout and organize content like in [mockups](https://covid-tracking.slack.com/archives/C01089TFL5Q/p1585615748038900)

**Comment by kevee** [comment]
Hello! This issue looks stale and may have been already resolved. Please close it if that is the case.

If your issue is *still* not resolved, leave a comment to update us on that so we know!

**Comment by julialedur** [comment]
hey! 
the layout will still change with the new text/headers etc. 
i'll open another issue once we have the final text, which is being edited [here](https://docs.google.com/document/d/1Gssfv1KLOa5fzeSmFWJqJmRMgQp3kXLvwaO7popsWOA/edit#).
