### ISSUE TITLE
update stay-at-home orders on small multiples  

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#333]
more states imposed stay-at-home orders, which are updated in this [spreadsheet](https://docs.google.com/spreadsheets/d/1mD_NhlJR1fM2Pv_pY8YixUrX2p2F8rAE0xPTtsTJOiM/edit#gid=0). we need to add those to the small multiples and also add a note at the bottom: 

Note: Only statewide stay-at-home orders were considered. The dates indicate when the order went into effect.

**Comment by kevee** [comment]
@julialedur - was this fixed in #431?

**Comment by kevee** [comment]
Ah the PR says it fixed this issue. I'm closing for now, feel free to reopen.

**Comment by julialedur** [comment]
hey @kevee! 
this was fixed, but since then more states issued stay-at-home orders, so the graphic isn't updated.
