### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#339]
Kevin kicked this off in #306 but I think this warrants its own issue. Below are my suggestions for issue templates:

This repo:
* **Design issue**: something is wrong with the aesthetic of the website
  * Explain what the issue is (I :heart: screenshots here)
  * Explain (if you know) what could be done to resolve this issue
* **Content issue**: something is wrong with the content of the website
  * Explain what the issue is
  * Document the issue (what [is|is not] happening that should [be|not be] happening?)
* Some way to redirect would-be issue-posters to the main issue repo for data-related or org-related issues

[COVID19Tracking/issues](https://github.com/COVID19Tracking/issues/):
* **Data update issue**: data is not updating properly / a data source changed
  * I would _love_ to enforce prefixes on issues like: `<2-letter state code>: <issue title>`
  * Document the issue
  * **Organization-wide issue**: these are rare, but would probably be discussion topics, overarching changes, etc.
  * Some way to communicate what should be an issue (i.e. data is not updating) and what should _not_ be an issue (i.e. here's my cool new project that uses your data)

Consider this a starting point -- I'd love to hear more suggestions about this!

Tagging people who seem to interface with these issues: @julia326 @careeningspace @kevee :raised_hands:

**Comment by careeningspace** [comment]
I thought that was how it was supposed to be?

**Comment by kevee** [comment]
We can make an issue template that links to a separate repo or docs as well.

**Comment by kevee** [comment]
Added issue templates.
