### ISSUE TITLE
adjust legend of choropleth 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#349]
let's use these colors for the choropleth, so that the yellow we're using across the page for positive tests matches the map scale: 

<img width="349" alt="Screen Shot 2020-04-01 at 9 52 43 PM" src="https://user-images.githubusercontent.com/39416238/78202865-6bf4a180-7463-11ea-99b2-dd478ae65ff1.png">

here are the hex codes: 
#FCF9EB
#FBE8A9
#F6CE7A
#F3B05D
#E2894E
#C66B3E
#924F34
#753C2D

let's also make the buttons font-size a bit smaller and add "map" after choropleth 

let's delete "per million residents" from the choropleth legend and add it here instead: 

<img width="538" alt="Screen Shot 2020-04-02 at 12 57 18 AM" src="https://user-images.githubusercontent.com/39416238/78212180-fe556f00-747c-11ea-942c-2f2f891afb80.png">

I'm opening another issue for dropdown styling

**Comment by goleary** [comment]
@julialedur we got feedback on slack from several people that have no idea what 'choropleth' means. they suggested using 'state map' as the text for the toggle. do you have any ideas for more user friendly names to put in that?

Also are you satisfied with the colors present for 'deaths' & 'total test'?

**Comment by julialedur** [comment]
yeah, i guess that makes sense! let's talk about it tomorrow on slack :) 
i talked to jason about the colors today and he's gonna give us new hex codes for the gray and purple scales. orangy is still this one: 

#FCF9EB
#FBE8A9
#F6CE7A
#F3B05D
#E2894E
#C66B3E
#924F34
#753C2D

**Comment by vijaysharwar** [comment]
I can work on these issues.

**Comment by vijaysharwar** [comment]
@julialedur PR opened for fixes https://github.com/COVID19Tracking/website/pull/445

Let me know if there are new hex codes for the grey and purple schemes. Can add to this PR, or break into separate issue if you are still deciding on new colors. Same if "choropleth" term needs to be changed.

**Comment by vijaysharwar** [comment]
@julialedur PR merged https://github.com/COVID19Tracking/website/pull/445 by @jeremiak. But let me know about those other potential changes.

**Comment by julialedur** [comment]
hey @vijaysharwar and @goleary! 
we got new colors from Jason today: 

*main colors*

purple (total tests): #575AAD
orange (positive tests): #FFAD4A
gray (deaths): #4C5559 


*scales*

Honey:
#6E2F1F
#924F34
#C66B3E
#E2894E
#FFAD4A
#F6CE7A
#FBE8A9
#FCF9EB

Plum:
#111354
#31347A
#575AAD
#6164BA
#8B8DC7
#B6B7DB
#D1D1E8
#F2F2FF

Gray: 
#3D4245
#4C5559
#5B666B
#6F7E85
#849096
#95A0A6
#B2BBBF
#D0D7DB

**Comment by vijaysharwar** [comment]
@julialedur will update the other colors now.

**Comment by vijaysharwar** [comment]
@julialedur @jeremiak updated in https://github.com/COVID19Tracking/website/pull/450

**Comment by julialedur** [comment]
can we update the gray scale to the new one? 

Slate:
#313638
#4C5153
#676B6D
#828688
#9CA1A2
#B7BCBD
#D2D6D7
#EDF1F2

thanks!

**Comment by goldfarb** [comment]
@julialedur @jeremiak @goleary updated the grays in [#514](https://github.com/COVID19Tracking/website/pull/514)
