### ISSUE TITLE
Make more obvious /states/daily is the count at 16:00 ET

### ISSUE THREAD

**Issue by chiester** [COVID19Tracking/website#35]
The API is reporting 642 positive cases in WA, but the /data page says 769 positive cases.

**Comment by hammer** [comment]
paging @webmasterkai

**Comment by webmasterkai** [comment]
The API is reporting 769 positive cases. 
<img width="531" alt="Screen Shot 2020-03-15 at 10 54 18 PM" src="https://user-images.githubusercontent.com/969456/76719372-03da5780-6710-11ea-9054-4a4de5da76ad.png">

**Comment by chiester** [comment]
My apologies, I wasn't clear which api. /api/states/daily is reporting 642 positive cases. 

<img width="866" alt="Screen Shot 2020-03-15 at 11 14 14 PM" src="https://user-images.githubusercontent.com/3964828/76720297-cdeaa280-6712-11ea-8c3d-7421ea0f3aae.png">

**Comment by webmasterkai** [comment]
Ah, I should have checked to see if that's where your number came from. The /data page says "Last updated: 3/15 18:00 ET" and the /api/states/daily is a snapshot at 1600 ET. We should probably make that more obvious.

**Comment by kissane** [comment]
@hammer Can we just add this information to the tab name or will that break everything?

**Comment by hammer** [comment]
This is actually an issue with the REST API URL structure and not the sheet, thank goodness.

**Comment by kissane** [comment]
We've had some reporters confused about the sheet as well, but maybe our new documentation will help with that! I'll leave the API bit for @webmasterkai

**Comment by webmasterkai** [comment]
A property has been added to the /api/sates/daily called `dateChecked` that includes the time. For example `"dateChecked: "2020-03-16T20:00:00Z"`.
