### ISSUE TITLE
choropleth dropdown style 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#351]
let's style the dropdown to match the page design better. 
was thinking of something like this: 

<img width="355" alt="Screen Shot 2020-04-02 at 1 05 37 AM" src="https://user-images.githubusercontent.com/39416238/78212957-44133700-747f-11ea-8aed-020080776237.png">

<img width="515" alt="Screen Shot 2020-04-02 at 1 06 41 AM" src="https://user-images.githubusercontent.com/39416238/78212977-4e353580-747f-11ea-8220-361e9fca5054.png">

don't forget to include "per one million people" between the number and the slider

**Comment by nselikoff** [comment]
Custom styling of dropdowns opens up a can of worms in terms of accessibility as you have to break away from the standard `<select>` HTML. If styling in this case is important I'd recommend we consider a library for the select as there's a lot that goes into getting it right. Two that I turned up:

* https://reacttraining.com/reach-ui/listbox/
* https://github.com/downshift-js/downshift

Another possibility is to reconsider the UI/UX, depending on how many items may end up being in the list of options (e.g. a multi-button toggle).

**Comment by kevee** [comment]
@julialedur - is this issue closed?

**Comment by julialedur** [comment]
we can close it for now!
