### ISSUE TITLE
change hover over style on both maps

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#352]
right now our states turn gray when we hover over them. 
this is totally fine, except when we get to the choropleth, so suddenly the gray from the hover is getting in the way of the color encoding. 
so I suggest we only change the stroke around the state to black on mouseover. it's also easier to see which state you're looking at when thee shape is highlighted. Reuters did it well on [this](http://graphics.reuters.com/HEALTH-CORONAVIRUS-USA/0100B5K8423/index.html) story: 

<img width="335" alt="Screen Shot 2020-04-02 at 1 18 38 AM" src="https://user-images.githubusercontent.com/39416238/78213343-65c0ee00-7480-11ea-95bd-ba3f4f3296cc.png">

**Comment by julialedur** [comment]
<img width="120" alt="Screen Shot 2020-04-07 at 3 13 15 PM" src="https://user-images.githubusercontent.com/39416238/78710030-ac7c7100-78e2-11ea-9c11-71549997263c.png">

it looks like some of the gray map lines are on top of the black

**Comment by nselikoff** [comment]
Taking a look at this now. The ordering issue should be fixable with `d3.select(this).raise()` (https://riptutorial.com/d3-js/example/18029/svg--the-drawing-order).

**Comment by nselikoff** [comment]
Actually I don't think this will work, as there's no `this` inside the onMouseEnter callback [here](https://github.com/COVID19Tracking/website/blob/dashboard-gatsby/src/pages/dashboard/charts/_Map.js#L207). I'm new to integrating d3 and React, so I'm not sure what the best approach is here.

**Comment by goleary** [comment]
I wonder if we could use a transparent border that is replaced by a black one on hover? although I'm guessing we may see no lines between states using this method.

Another idea:
From what I understand svg elements appear in the order they are encountered, so we could use another path with a black/gray stroke and transparent fill below (in code) all of the other paths that is added on hover and removed on exit.

**Comment by nselikoff** [comment]
Thanks for your thoughts @goleary; helped me think about it a bit differently and fix it!
