### ISSUE TITLE
change tooltip table style 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#353]
I suggest adding colored underlines to the variables on the table so it's easier to read from a visual perspective. we can also get rid of that gray background (sorry, that was a bad idea!) like this: 

<img width="606" alt="Screen Shot 2020-04-02 at 1 32 22 AM" src="https://user-images.githubusercontent.com/39416238/78213985-1c719e00-7482-11ea-8b4c-d1a4b9334f0b.png">

let's also take the font of the table a bit down, so there's a visual hierarchy (state name is bigger than table info) 

also, it looks like there's a right margin on the tooltip now:

<img width="47" alt="Screen Shot 2020-04-02 at 1 35 37 AM" src="https://user-images.githubusercontent.com/39416238/78214080-50e55a00-7482-11ea-9465-02217b6c811f.png">

**Comment by julialedur** [comment]
we need to add some margin around this: 

<img width="274" alt="Screen Shot 2020-04-07 at 3 13 50 PM" src="https://user-images.githubusercontent.com/39416238/78709888-6cb58980-78e2-11ea-9cea-6044b6ac83ff.png">

**Comment by friej715** [comment]
Holler if this looks good and I'll make a PR. 
![image](https://user-images.githubusercontent.com/1028403/78740169-0b160f00-7924-11ea-8327-e0884dfc642e.png)

**Comment by friej715** [comment]
Oh, never mind, saw the PR above.

**Comment by jeremiak** [comment]
Thanks though @friej715 !!

**Comment by nselikoff** [comment]
Sorry @friej715 wires crossed
