### ISSUE TITLE
standardize language on all graphics 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#354]
I noticed we're using "positive tests" in some places and "confirmed cases" in others (like on the choropleth dropdown and  bubble map legend) 
same thing for "total tests" and "tests conducted"

let's be consistent and only use "**total tests**" and "**positive tests**" for all graphics

**Comment by julialedur** [comment]
just a reminder that this issue is still pending

**Comment by julialedur** [comment]
let's also get rid of the capital letters on the choropleth dropdown 
so "deaths" instead of "Deaths"

**Comment by jeremiak** [comment]
I'll pick this one up

**Comment by julialedur** [comment]
<img width="274" alt="Screen Shot 2020-04-11 at 2 53 01 PM" src="https://user-images.githubusercontent.com/39416238/79052381-27f06200-7c04-11ea-96cb-557eab81b044.png">

- looks like second words are still capitalized 
- should be "positive tests" instead of "positive cases"
