### ISSUE TITLE
make maps bigger 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#355]
your maps are so beautiful and incredible and i think we should make them like 30% bigger on the page. 
let them shine! ❇️ 
plus it will also be easier to see the states on the east coast that are covered by bubbles

**Comment by julialedur** [comment]
anyone working on this? @jeremiak @goleary @vijaysharwar @melbee

**Comment by goldfarb** [comment]
I've resized the map, do we want to have a smaller version for mobile?

**Comment by julialedur** [comment]
cool! looks great 🎉 
I think @goleary is working on the [mobile version](https://github.com/COVID19Tracking/website/issues/444).
