### ISSUE TITLE
add tooltips to all charts 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#357]
let's add tooltips to our charts!! ❇️ 

please follow this style: 

for charts that only show one variable 
<img width="177" alt="Screen Shot 2020-04-02 at 2 35 27 AM" src="https://user-images.githubusercontent.com/39416238/78217788-b1789500-748a-11ea-875c-4226dbdade0a.png">

for charts that show more than one variable 
<img width="198" alt="Screen Shot 2020-04-02 at 2 35 21 AM" src="https://user-images.githubusercontent.com/39416238/78217797-b63d4900-748a-11ea-8a25-17d74f20e08a.png">

**Comment by vijaysharwar** [comment]
I am available to help with `Visualization` issues. But it's not clear from the [website docs](https://covid19tracking.github.io/website-docs/) how this code is being managed.

Looks like they're only in feature branches for now, yet to be merged to `master`?

https://github.com/COVID19Tracking/website/tree/dashboard-gatsby-map
https://github.com/COVID19Tracking/website/tree/dashboard-gatsby-area-chart

cc @kevee

**Comment by melbee** [comment]
@vijaysharwar I am in progress on this specific issue but could use help on a different D3 axis issue. 

Regarding the codebase, currently all the visualization code is in the Dashboard branch, not in master, but the code in Dashboard branch is als getting migrated to Gatsby in a couple of other branches by @jeremiak @goleary

cc @jeremiak @goleary @julia326

**Comment by vijaysharwar** [comment]
@melbee hit me; which issue?

**Comment by kevee** [comment]
@vijaysharwar - We have some guidance in the [CONTRIBUTING](https://github.com/COVID19Tracking/website/blob/master/CONTRIBUTING.md) docs, but haven't finished specific docs on branching. For now, try to maintain separate feature branches.

**Comment by vijaysharwar** [comment]
@kevee 👍 Yup, I read those docs. My question was more about where the visualization stuffs lived, since I couldn't anything relating to these `Visualization` issues in `master`.

As per @melbee's comment above, looks like maybe I'd need to branch from one of these?

https://github.com/COVID19Tracking/website/tree/dashboard-gatsby
https://github.com/COVID19Tracking/website/tree/dashboard

**Comment by kevee** [comment]
Gotcha. I think they're doing work on the `dashboard-gatsby` branch, but I haven't been working on any of the visualization branches lately.

**Comment by vijaysharwar** [comment]
@goleary I see that you're updating [dashboard-gatsby-map](https://github.com/COVID19Tracking/website/commits/dashboard-gatsby-map) actively. Is that the best place to contribute? And if so, any particular issue you could use help with? cc @melbee

**Comment by goleary** [comment]
hey @vijaysharwar we need to get our dashboard branch to a stable point before I can throw issues your wa. We're in the process of migrating it from pure d3/js to react/gatsby with d3. I'm hoping we'll be there later today or tomorrow. There are definitely issues you could help with at that point so I'll make sure to circle back once it's ready for you.

**Comment by goleary** [comment]
@vijaysharwar all of our code is merged and *relatively* stable within `dashboard-gatsby`. Feel free to look through the issues and pick up anything labeled 'Visualization' and submit a pr to the `dashboard-gatsby` branch.

**Comment by jeremiak** [comment]
Hey @vijaysharwar - if you're up for it, mind tackling #349 or #430? Either of them should be branched off `dashboard-gatsby`

**Comment by julialedur** [comment]
is anyone working on this?

**Comment by vijaysharwar** [comment]
Seems like @melbee is? https://github.com/COVID19Tracking/website/issues/357#issuecomment-609473124

**Comment by julialedur** [comment]
looks like she was running into issues. 
@melbee holler if you need help with this?

**Comment by melbee** [comment]
Ah, I was helping someone else with some issues they were having. Regarding this issue for tooltips I am no longer working on this since the tooltips I was working on were for our original implementation using britecharts (I didn’t realize we were using D3 until after I started the britecharts tooltips so now the tooltips need to be rewritten / implemented for D3). Right now I am migrating horizontal bar charts to d3 so if someone can pick this up please do!

**Comment by melbee** [comment]
@vijaysharwar please let me know if you ended up starting on this one for the D3 implementation. thanks!

**Comment by vijaysharwar** [comment]
@melbee I have not, sorry. Been working on other issues. Will post here if I have time to pick it up.

**Comment by melbee** [comment]
got it - i'm going to remove myself as the assignee from this issue since I won't be able to work on this today and don't want to block if someone else can take it cc: @julialedur

**Comment by julialedur** [comment]
@vijaysharwar @AaronMullan @goldfarb could one of you pick this up today?

**Comment by AaronMullan** [comment]
I think I can look at this in a couple hours if nobody else is on it yet.

**Comment by AaronMullan** [comment]
OK this was more complicated than I had anticipated.  I had guessed the tooltip was something built in to D3 or was an npm package I could easily feed props to.  On closer inspection it seems Gabe built the Tooltip.  It's going to take me a minute to figure out how to build similar tooltips for the other chart types that will let us make them look consistent with what we have for the map.

**Comment by kevee** [comment]
@julialedur - is this issue closed?

**Comment by vijaysharwar** [comment]
@kevee there's a draft PR from @goleary here https://github.com/COVID19Tracking/website/pull/642

**Comment by goleary** [comment]
got a couple of things to wrap up before we close this
