### ISSUE TITLE
Process for approval of PRs with data changes

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#359]
Because data *is* what we do, and because I screwed up and used the wrong API field, let's implement a process (to be documented in the CONTRIBUTING.md) file:

PRs that touch the display of data, whether UI or sourcing of data from the API, should:

Use the 'Needs data approval' label
Be assigned to a data team member - right now, @jdmaresco 
Be approved by the data team member

**Comment by schwartzadev** [comment]
Yes! Great call.

We should be clear about what "touching data" means...Here are some corner cases off the top of my head:

* If I reformat a table that has data in it, does that need review?
   * ... What if I reformat only in SCSS?
   * ...What if I reformat the table component?
* If I refactor (a component that includes a table) into (a parent component) and (a table component), would that need review?
* Would review be required if I add columns to an existing data table?

Just some food for thought :ramen: :thinking: ... 

Also if/when we implement this, we should have at least two people who can be reviewers for contingency.
