### ISSUE TITLE
Tab navigation issues

### ISSUE THREAD

**Issue by gitjeff05** [COVID19Tracking/website#361]
When navigating to the [Get the Data](https://covidtracking.com/data/) page, there are a couple of issues with the navigation:

1.) The tab "State by State" should be active when the page loads.
2.) Clicking on the tab "Methodology" takes the user away from this section. This is counter to expected tab behavior and different from how all the other tabs on this site work.

**Comment by kevee** [comment]
We reordered all the nav, is this issue resolved?

**Comment by vijaysharwar** [comment]
Issued PR https://github.com/COVID19Tracking/website/pull/412 to fix item 1, the active tab states. Item 2 no longer seems to be an issue, as there is no "Methodology" tab in the current content.
