### ISSUE TITLE
Github Lighthouse Checks Failing

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#368]
**Describe the bug**
The [Lighthouse checks](https://github.com/COVID19Tracking/website/actions?query=workflow%3A.github%2Fworkflows%2Flighthouse.yml) _always_ fail. We should either:

* remove this from GH Actions
* update this so it actually checks things

**Comment by kevee** [comment]
Agreed, I had removed it f64f17fd8d311383074d2f9766b09a5001114bae

Going to see why it's still running, it could be PRs based on master branches that are unmerged from upstream?
