### ISSUE TITLE
Arizona data isn't complete

### ISSUE THREAD

**Issue by mentalplex** [COVID19Tracking/website#37]
See https://www.azdhs.gov/preparedness/epidemiology-disease-control/infectious-disease-epidemiology/index.php#novel-coronavirus-home

The tracker is only reporting state lab results, despite commercial lab results being reported on the state website. As of now, AZDHS reports 18 positive, not 12

**Comment by careeningspace** [comment]
Thank you for your vigilance! That data will be included in the next data push shortly
