### ISSUE TITLE
Displaying screenshots -- Input Requested

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#379]
Currently, the way we handle sharing screenshots on the historical tables is pretty messy. I would love some design input about ways to clean it up.

![image](https://user-images.githubusercontent.com/18607205/78308933-04902d80-7507-11ea-888c-ceec0489f060.png)

**Comment by kevee** [comment]
My feels is that with the new outcomes data coming on board that we should have a separate "screenshots" page ---

OR, going crazy here:

How about we have the main /data/states/[state] page be an overview: show current status, a list of critical data (like tests/positive/deaths/recovered) for each day, and then you can click a link to that day which takes you to `/data/state/[state]/[date]` where we will have room to show all the data for that state for that day, along with little screenshot previews and whatever else we want.

**Comment by beep** [comment]
> then you can click a link to that day which takes you to /data/state/[state]/[date] where we will have room to show all the data for that state for that day, along with little screenshot previews and whatever else we want.

I am _super_ into this idea.

**Comment by kevee** [comment]
This is **super important**, so I closed and merged it into #457.
