### ISSUE TITLE
GraphQL endpoint includes null values for many properties

### ISSUE THREAD

**Issue by brambow** [COVID19Tracking/website#383]
Hi,

Some of the data fields in the graphql endpoint seem to be returning nulls, but the REST endpoints are returning values

GRAPHQL
![image](https://user-images.githubusercontent.com/6227786/77765659-f3ca4e00-7014-11ea-9ecd-8d69c4b88a11.png)

REST
![image](https://user-images.githubusercontent.com/6227786/77765794-28d6a080-7015-11ea-8b99-23c9ba3f2d8d.png)

**Comment by webmasterkai** [comment]
Moving to the website repo where we have moved much of the API code.
