### ISSUE TITLE
API: Update docs for latest version of API

### ISSUE THREAD

**Issue by webmasterkai** [COVID19Tracking/website#385]
Would be great to have some more formal API documentation. Also need to update things for the latest version with path changes.
Should probably note the API history in CSV is available here https://github.com/COVID19Tracking/covid-tracking-data

**Comment by friej715** [comment]
Started to work on this [here](https://app.swaggerhub.com/apis/janelastname/COVID-endpoints/1.0). (Would it make sense to store an exported version of the yaml in the repo?)

**Comment by kevee** [comment]
Merged issue #397 into this as well and assigned to @friej715 - Here's the takeaway:

Are `date` and `dateChecked` trying to represent the same data (YES)? I wasn't sure. `dateChecked` is documented as ISO 8601 date of the time we last visited their website. While date is not documented I assume it is the day for which historical data is computed.
