### ISSUE TITLE
Refactor SCSS files

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#390]
In our great haste, we have a few SCSS files that are spreading global classes around. Let's refactor these to:

- Wrap pages/components in more classes - We can just apply more classes and always have each .scss file scoped to that class. We're most of the way this direction
- Use [SCSS modules](https://www.gatsbyjs.org/docs/css-modules/) - **Pro:** This will *force* us to use modules. **Con:** Harder for folks to just jump in
- **Styled components in Emotion** - **Pro:** Um, I like it? **Con:** Hard for new devs to jump in

**Comment by beep** [comment]
Oh man, I’m glad you logged this. @tealtan and I were chatting a bit about our style architecture, and making sure the front-end’s as inviting/accessible as possible for new contributors to jump in.

**Comment by kevee** [comment]
Right, I we could just start by saying "all modules/pages shalt be wrapped in a class" and then refactor the scss we have...

**Comment by tealtan** [comment]
👋🏼 Yay!

I think the last option is probably too high a barrier for folks, but I actually am somewhat in favor of using SCSS modules here, at the cost of a bigger refactor:

- Continues to use SCSS, which is going to be friendly for contributors
- Enforces style isolation, which lets us test a bit more easily in Storybook etc
- Creates a bit of a learning curve in requiring people to write `className={containerStyles.container}` rather than `className='container'` in the markup, but this is simple enough to follow I hope?

If folks are split between option 1 or 2, it could be worth trying both and then comparing? What do you all think?

**Comment by beep** [comment]
@tealtan I like everything you just said. Honestly, I’m fine with option 2, but would be more than comfortable getting some speculative branches running for 1 and 2 if we’d like to test them both.

**Comment by kevee** [comment]
Here's a sample of what would have to happen with one page:

**Option 1:**
https://github.com/kevee/Covid19Tracking-website/commit/9e0226f027ef6cdd455d685f7ee88c3be16d1214
 - All pages declare a `page--something` class name to a layout, and wrap their SCSS files in that class
- All components declare a `component--something` class and wrap their SCSS files

**Option 2:**
- Everything needs to be a class (no tag selectors, unless they are nested)
- You can use this method **and** what we have side-by-side
https://github.com/kevee/Covid19Tracking-website/commit/7f7973db6e789369433c28c6ba8836154d796299

**Comment by tealtan** [comment]
Awesome, thank you! Both options look about the same to me, so unless others object, let’s go with option 2?

**Comment by beep** [comment]
Yeah, option 2 looks like the winner to me! Thanks, @kevee!

(Out of curiosity, could we [expose human-readable class names](https://www.gatsbyjs.org/docs/css-modules/#enabling-user-stylesheets-with-a-stable-class-name)? Would love to be able to support that.)

**Comment by kevee** [comment]
OK I'll have a PR tomorrow for this, and double plus yes to human readable class names

**Comment by kevee** [comment]
Notes for myself:

- [ ] Snapshot site so we see if any layout changes
- [ ] [Use stable class names](https://www.gatsbyjs.org/docs/css-modules/#enabling-user-stylesheets-with-a-stable-class-name)
- [ ] Document stable class names & CSS modules in contributing doc
- [ ] Change SCSS files to `name.module.scss`
- [ ] Refactor SCSS/imports
- [ ] Compare snapshot
