### ISSUE TITLE
Add footnote to nationwide data summary when we add outcomes metrics to /data

### ISSUE THREAD

**Issue by jdmaresco** [COVID19Tracking/website#392]
Please see conversation here:
https://covid-tracking.slack.com/archives/C010N48RY73/p1585922697020100

We report current and cumulative numbers provided by states, supplemented by trusted press sources. Because some states only report “Current” numbers, the nationwide “Current” numbers can be higher than that of the reported “Cumulative” totals. We know, of course, that the true cumulative numbers are much higher, but we can only report the numbers we have access to. We are actively working with states to request that they expand their reporting.

**Comment by kevee** [comment]
I added this as a snippet to Contentful.
