### ISSUE TITLE
On website (/api), links under GraphQL behaving strangely

### ISSUE THREAD

**Issue by friej715** [COVID19Tracking/website#395]
These links:
![image](https://user-images.githubusercontent.com/1028403/78394931-855c3180-75ba-11ea-8aa9-bbbc65a3724c.png)

Playground says server cannot be reached: 
![image](https://user-images.githubusercontent.com/1028403/78395002-a6248700-75ba-11ea-94dc-96d5271d708b.png)

Graphql throws an error (related to #383?):
![image](https://user-images.githubusercontent.com/1028403/78395025-b177b280-75ba-11ea-82ca-1fc28009e7cd.png)

**Comment by webmasterkai** [comment]
Some work has been started https://github.com/COVID19Tracking/website/pull/343 We need someone to finish this up and get it migrated to Netlify

**Comment by metasj** [comment]
Until this is working, perhaps replace those links with the text "If you would like a GraphQL endpoint, leave us feedback on [this issue](https://github.com/COVID19Tracking/website/issues/395)".
