### ISSUE TITLE
DNS is still weird

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#4]
Most people are seeing the website at http://covidtracking.com/ but some are not and the HTTPS is still borked

**Comment by kissane** [comment]
Informal poll of about 15 international and US folks has everyone seeing the website, but I know at least one person on our team isn't.

**Comment by hammer** [comment]
Just wanted to note that my issues have resolved for no apparent reason.

**Comment by lucasgonze** [comment]
I am now getting two issues:

1. http://covidtracking.com redirects to the Google Sheets URI
2. HTTPS still broken 

I will work on these

**Comment by lucasgonze** [comment]
The plain old HTTP server is related to DNS server. It wasn't happening for me until I came home from work. Switching DNS server to 1.1.1.1 fixes it. Using Tor (which moves DNS resolution to the exit node) fixes it.

**Comment by lucasgonze** [comment]
Screenshot of the TLS error.

![Capture d’écran 2020-03-11 à 18 36 56](https://user-images.githubusercontent.com/111581/76478975-863ce180-63c7-11ea-9cb2-71e541d0cf44.png)

**Comment by Wilto** [comment]
Hey, just a heads-up: there’s nothing we can do to speed this process up, but any changes we make may _delay_ the DNS propagation—I think we just have to wait this one out.

**Comment by Wilto** [comment]
Also, I think a form of caching is a factor: if you saw it broke, you’re likely going to keep seeing it broke longer than someone hitting the site anew.

**Comment by lucasgonze** [comment]
Discourse ticket:
https://community.netlify.com/t/unable-to-get-a-lets-encrypt-cert-because-dns-verification-is-failing/10469

**Comment by webmasterkai** [comment]
The SSL certificate was updated and DNS is working correctly now.
