### ISSUE TITLE
fix(design): Tighten header line heights

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#415]
We need to redo line heights for headers, especially H2 in the body has way too much leading between lines. I think this is a typography.js config fix.

![image](https://user-images.githubusercontent.com/270536/78499433-b190c300-771e-11ea-8149-9312dc506c9b.png)

**Comment by vijaysharwar** [comment]
I can work on this.

**Comment by vijaysharwar** [comment]
@kevee PR: https://github.com/COVID19Tracking/website/pull/418
