### ISSUE TITLE
Provide links and/or more inclusive "visualization gallery"

### ISSUE THREAD

**Issue by nealmcb** [COVID19Tracking/website#421]
_Please let us know the page you are talking about, and your content suggestions!_

The home page (https://covidtracking.com/) shows 3 visualizations "From the visualization gallery". I love that "gallery" idea, implying that there are more and that they are organized somehow. But it doesn't define this "gallery", or provide a nexus for efforts to expand on visualizations.

#91 is now closed, but I don't see a link from the website to either the local project and its visualizations that seems most relevant ([COVID19Tracking/covid-tracking-dash](http://bit.ly/covid-tracking-dash), or to many of the other visualizations referenced there (which might be suitable for a "gallery").

After some more poking around, I guess this is the gallery, but it doesn't include the word "gallery" and I don't see any links to it: https://covidtracking.com/visualizations.

I also just saw another log/log approach that I like: [Covid Trends by  Aatish Bhatia](https://aatishb.com/covidtrends/) which uses the John's Hopkins data. It is described in this lovely educational video:
*  [How To Tell If We're Beating COVID\-19 \- YouTube](https://youtu.be/54XLXg4fYsc)
so it might be nice to add that or a link to it.

**Comment by nealmcb** [comment]
OK, I dug out some more of the history of this at #71. At the tail end of the PR, the web page link to the list of visualalizations was removed, pending some sort of "broader approval'.
I think it merits a link from the home page.

**Comment by kevee** [comment]
Hi, @nealmcb - the presentation team is very close to an actual visuzation dashboard within the website, that should be live (*caveat emptor*) soon. That visualization list is something we don't link to yet, I'm flagging this is a content issue so we can first see where it fits in the IA.

**Comment by nealmcb** [comment]
Now I want to find and update the actual Data Visualizations (used to be visualizations.md), but can't find that or the text in it in the whole website repo.
What am I missing?

**Comment by nealmcb** [comment]
Thanks for the update, @kevee. Who/where is the "presentation team"? I'm not seeing that anywhere near https://covidtracking.com/about-project

**Comment by kevee** [comment]
Website content is in Contentful now.

The presentation and visualization folks are working in this branch - https://github.com/COVID19Tracking/website/tree/dashboard-gatsby . We currently don't list team membership on the website, but that's a good idea for down the road. You can see all the amazing visualization the team comes up with on our twitter account.

**Comment by nealmcb** [comment]
Interesting - thanks. For easy reference, twitter account is at https://twitter.com/COVID19Tracking

OK, I found this background info:
 *  [Launch plan for website v2 · Issue #244 · COVID19Tracking/website](https://github.com/COVID19Tracking/website/issues/244)

So how do we submit PRs on the content?

**Comment by kissane** [comment]
I would suggest holding off until the visualization work actually launches before submitting PRs dealing with it, @nealmcb. That will likely be in the next week, maybe in the ext few days. Some of our work is visible here in the repo but most of the design/viz decisions are being made by a dedicated team working together to get their visualization/dashboard work ready for launch. Once that happens, I'm sure they'll be happy to evaluate feedback!

**Comment by kevee** [comment]
The viz team is launching the new dashboard, so we are closing this for now.

**Comment by nealmcb** [comment]
Thanks again folks for all your work on this.
FWIW, in order to help people track status and progress and find ways to contribute, I think it is helpful to either keep unresolved issues open, or link to related issues or pull requests where updates can be tracked. I see that the branch referred to above is still active, but doesn't have e.g. a WIP pull request to track, which might be helpful.

**Comment by nealmcb** [comment]
Does anyone have an update on visualization work, updating links etc? Has activity moved to a different branch? The last commit to https://github.com/COVID19Tracking/website/tree/dashboard-gatsby was 8 days ago.

Hmm - I also now see this: [Visualization Guide \| The COVID Tracking Project](https://covidtracking.com/about-data/visualization-guide), but I also still see [Data Visualizations](https://covidtracking.com/visualizations). Should those be merged? And should the text about the gallery on the home page become a link directly to one of them?
