### ISSUE TITLE
Data tables too wide for moble.

### ISSUE THREAD

**Issue by tomByrer** [COVID19Tracking/website#426]
The results tables seem to have a horizontal scrollbar on mobile.  (default `overflow: scroll;`?)
Not a big deal, though I think chunking the state data into groups by section (see orange box in picture) & letting each section float down as the screen narrows is a easy fix in `src\components\pages\data\state-*.js`.

I thought about hacking it myself, since I know React, but I don't know Emotion's API.

I don't think the [daily page](https://covidtracking.com/data/us-daily) is worth the extra hassle, unless someone knows a great React component, or you're OK with using a different plugin made for "responsive tables".  But my vote is for letting someone else to build a separate site using your API.

![covid19](https://user-images.githubusercontent.com/1308419/78662007-4b7a7c00-7895-11ea-8e75-180621360586.jpg)

**Comment by jasonlcrane** [comment]
Hi Tom, thanks for the contribution. There is a good discussion going on about this over in this issue: #317 

I don't have the ability but I recommend we close this in favor of that one.

**Comment by kevee** [comment]
This is **super important**, so I closed and merged it into #457.
