### ISSUE TITLE
weird blue box on button click

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#429]
A weird blue box show up whenever you click buttons on the page: 

<img width="1266" alt="Screen Shot 2020-04-07 at 3 17 00 PM" src="https://user-images.githubusercontent.com/39416238/78710253-02511900-78e3-11ea-8419-c78d9af7b54f.png">

**Comment by goleary** [comment]
I think this is probably imposed by global styles for the entire website. It should however only cover the visible toggle instead of the whole line.

**Comment by AaronMullan** [comment]
Hold on, pull request coming.

**Comment by AaronMullan** [comment]
PR is in.
