### ISSUE TITLE
Color palette updates for dataviz

### ISSUE THREAD

**Issue by jasonsantamaria** [COVID19Tracking/website#440]
Let us know what the design issue is. Screenshots are helpful!

Júlia Ledur asked if we could broaden out our purple palette and bring it together with a warm spectrum they are using. So I did!

Here is a list of the latest set of colors and a screenshot below that. All of the purples are the same, I just added three new tones in the middle and lighter end. `Honey` is the warm palette they were already using, so I figured we could adopt and document that too.

```

Plum:
#111354
#31347A
#575AAD
#6164BA
#8B8DC7
#B6B7DB
#D1D1E8
#F2F2FF

Honey:
#6E2F1F
#924F34
#C66B3E
#E2894E
#FFAD4A
#F6CE7A
#FBE8A9
#FCF9EB

Blueberry:
#012656
#004399
#0091EA
#8CC7F4
#E2F1FC

Slate:
#313638
#3D4245
#4C5559
#5B666B
#6F7E85
#849096
#95A0A6
#B2BBBF
#D0D7DB
#EDF1F2
```

![Color palette Redux](https://user-images.githubusercontent.com/128280/78797333-8f4cae80-7985-11ea-93ec-e24d1fd9df14.png)

**Comment by beep** [comment]
(Grabbing this ’cause I’ve got a little time this afternoon, and @kevee asked if anyone could jump in!)

**Comment by beep** [comment]
@jasonsantamaria This landed in #447—let us know if things look okay to you? Happy to take another pass as needed!

**Comment by jasonsantamaria** [comment]
@beep Thank you! I have an additional suggestion for color naming if you want another one to consider. I've had good luck with using the same convention as CSS font-weight decorations (400, 600, 900, etc)  to allow for some space to expand. 

So instead of `$color-plum-1` you would do `$color-plum-100`, then `$color-plum-200`, `$color-plum-300`, and so on. That way later if you need to introduce an additional step somewhere in the middle, you could do `$color-plum-250` and not have to renumber everything.

In the I've also done naming based on color mixes, which help to actually describe the color too: 

```
$plum: #6a0432; // BASE
$plum-light-80: mix($white, $plum, 80%); // #e1cdd6
$plum-light-60: mix($white, $plum, 60%); // #c39bad
$plum-light-40: mix($white, $plum, 40%); // #a66884
$plum-light-20: mix($white, $plum, 20%); // #88365b
$plum-dark-20: mix($black, $plum, 20%); // #550328
$plum-dark-40: mix($black, $plum, 40%); // #40021e
```

I love this approach because it actually gives you an idea of what the color might look like (assuming you are familiar with the base color). I know our palette isn't formed by Sass color mixes, but the naming convention (including `dark` or `light` and a percentage) would potentially still work.

Just some food for thought!

**Comment by jasonsantamaria** [comment]
(And forgive me if these are techniques you know about or have discounted in the past, I never know how everyone likes to do stuff!)

**Comment by beep** [comment]
> So instead of $color-plum-1 you would do $color-plum-100, then $color-plum-200, $color-plum-300, and so on. That way later if you need to introduce an additional step somewhere in the middle, you could do $color-plum-250 and not have to renumber everything.

I have seen many variable naming schemes, but not this particular one! I dig it, Jason. I just opened #460, and will sort this out!

(I might treat the lower numbers as higher weights—e.g., `$color-plum-1` would be `$color-plum-800`—since I’d assume darker colors would correlate to a “heavier” weight. Does that track for you?)

> I love this approach because it actually gives you an idea of what the color might look like (assuming you are familiar with the base color). I know our palette isn't formed by Sass color mixes, but the naming convention (including dark or light and a percentage) would potentially still work.

I will think a bit more about this suggestion! I really like it, but I _also_ really like the appeal of scaling the variable names along a single axis. HMM gonna think about this one

Semi-related: this discussion is making me think that since we’ve got a decent number of hues in play, could/should we develop some guidelines on which colors are appropriate to use, and when?

**Comment by beep** [comment]
@jasonsantamaria Just opened up https://github.com/COVID19Tracking/website/pull/461, if you’d care to cast your gimlet eye ’pon it! hashtag colors hashtag names hashtag woo

**Comment by jasonsantamaria** [comment]
> (I might treat the lower numbers as higher weights—e.g., $color-plum-1 would be $color-plum-800—since I’d assume darker colors would correlate to a “heavier” weight. Does that track for you?)

Totally!

> I will think a bit more about this suggestion! I really like it, but I also really like the appeal of scaling the variable names along a single axis. HMM gonna think about this one

Yep, I get you. I was trying to figure out a way to also describe the color to someone well enough so that they wouldn't need to also see it. But. Yeah, that's tough. :D
