### ISSUE TITLE
add first and last date to slider 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#441]
let's annotate the first and last date on the slider (keeping in mind that the last date should update automatically everyday). something like this: 

<img width="1062" alt="Screen Shot 2020-04-08 at 10 52 22 AM" src="https://user-images.githubusercontent.com/39416238/78803684-4862b700-798d-11ea-9ddf-5a9704c898c1.png">

**Comment by writenorman** [comment]
looking into it now.

**Comment by writenorman** [comment]
please see PR #448

**Comment by gitjeff05** [comment]
Can this be closed?

**Comment by jeremiak** [comment]
Yup!
