### ISSUE TITLE
Dashboard map layouts break on small screens

### ISSUE THREAD

**Issue by vijaysharwar** [COVID19Tracking/website#444]
The styling and layout of both the bubble and choropleth maps are not mobile/small screen friendly.

<img width="376" alt="Bubble map: small screen layout issues" src="https://user-images.githubusercontent.com/63169602/78815002-997aa700-799d-11ea-8be3-3c6cb435d281.png">

<img width="375" alt="Choropleth map: small screen layout issues" src="https://user-images.githubusercontent.com/63169602/78815008-9c759780-799d-11ea-8c05-0ed11766a8f1.png">

Recommend fixing:
- Responsive scaling/overflow offscreen
- Overlapping UIs and text

**Comment by goleary** [comment]
i'm working on this

**Comment by goleary** [comment]
working on this one
