### ISSUE TITLE
Design refinements for the big ol text pages

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#452]
We have several long scrolly text pages that could use some love—they're looking real wiiiiide in big windows and just a little bit rougher in general than the data sections we asked the design team to focus on for the relaunch. I'd love to have some design attention and CSS nudges to get these shined up sometime. <3

Examples:

https://covidtracking.com/why-it-matters
https://covidtracking.com/help
https://covidtracking.com/about-data

**Comment by kevee** [comment]
How about we wrap content pages in our ["narrow" container](https://covid19tracking.github.io/website-docs/?path=/story/layout--container-narrow)?

**Comment by jasonlcrane** [comment]
I added a PR to use the narrow container. Any feedback is much appreciated.

**Comment by beep** [comment]
@kissane Happy to take a crack at this tomorrow if they’re still unclaimed!

**Comment by beep** [comment]
Here’s [a quick pass on what our text-heavy pages might look like](https://www.figma.com/file/fKUKsYMNw3NLSyIEOI1HKc/v2-refresh?node-id=0%3A14). And here’s a screenshot, if you’d prefer!

<img width="1440" alt="Content page" src="https://user-images.githubusercontent.com/124493/79138034-cd7d1000-7d81-11ea-9442-6a8a329edd04.png">

This mockup’s got two different subhed levels, numbered and bulleted list treatments, as well as a fair bit of body copy. Let me know if you’d like anything else included! But the main things here are:

- A baseline text size of 22px on widescreen, with a 1.5 line height.
- The content well’s width is capped at ~42rem.

Also, as I think @jasonlcrane noted on #474, it’d be _great_ to get a bit more spacing above and below the content area, just to create a bit more separation from the header & footer.

What do you folks think?

**Comment by beep** [comment]
(Edited https://github.com/COVID19Tracking/website/issues/452#issuecomment-612976070, as I goofed when exporting the mockup. #goofs)

**Comment by kissane** [comment]
Faaaaabulous ty @beep!

**Comment by kissane** [comment]
> Also, as I think @jasonlcrane noted on #474, it’d be great to get a bit more spacing above and below the content area, just to create a bit more separation from the header & footer.

Yes please

**Comment by toddparker** [comment]
~ chef kiss ~

**Comment by schwartzadev** [comment]
I can tackle this today or tomorrow!

**Comment by kevee** [comment]
Fixed in #535
