### ISSUE TITLE
Isolate SummaryTable CSS

### ISSUE THREAD

**Issue by nselikoff** [COVID19Tracking/website#453]
The CSS for the `SummaryTable` component doesn't seem to be scoped just to that component, so it can bleed into styling of other tables (see https://github.com/COVID19Tracking/website/blob/master/src/scss/components/common/summary-table.scss and https://github.com/COVID19Tracking/website/blob/master/src/components/common/summary-table.js). 

I noticed this when working on #435.

**Comment by kevee** [comment]
Fixed in #427
