### ISSUE TITLE
"In the press" page is broken

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#464]
There's a page not found error on https://covidtracking.com/about/in-the-press  

<img width="1438" alt="Screen Shot 2020-04-09 at 2 55 12 PM" src="https://user-images.githubusercontent.com/39416238/78930446-2131e580-7a72-11ea-830b-15793ef9925d.png">

**Comment by kevee** [comment]
It moved! https://covidtracking.com/about-project/in-the-press

Fixing now.
