### ISSUE TITLE
Redux slate gray palette

### ISSUE THREAD

**Issue by jasonsantamaria** [COVID19Tracking/website#465]
The data folks are having some trouble getting enough contrast across the `slate` palette (as mentioned in #450). It's the only color that has 10 steps, and I'm thinking we should bring it in line with the others at 8 steps. That will make sure we have a little more contrast that they need for choropleth maps.

I'm not sure how many of the existing  `slate` colors are in use, so this may or may not be hairy to change. I'm happy to consult translating any gray use over. I imagine the potential problem areas will be any at the very light or very dark ends of the spectrum. 

The new `slate` range would be:

```

Slate:
#313638
#4C5153
#676B6D
#828688
#9CA1A2
#B7BCBD
#D2D6D7
#EDF1F2
```

![Color palette Redux](https://user-images.githubusercontent.com/128280/78930698-88e83080-7a72-11ea-8c22-b5d67ceedda0.png)

**Comment by beep** [comment]
I’ll take a look at this, and see if I can work the changes into #461. Thanks, @jasonsantamaria!

**Comment by beep** [comment]
Addressed in https://github.com/COVID19Tracking/website/pull/461! Would love your feedback if you’d care to add any, @jasonsantamaria. (Weirdly, I can’t add you as a reviewer. HM)

**Comment by kevee** [comment]
He wasn't in our Github org. Invited!

**Comment by beep** [comment]
a-HA. Thanks, @kevee!
