### ISSUE TITLE
Refactor color defs in _Map.js?

### ISSUE THREAD

**Issue by beep** [COVID19Tracking/website#469]
Per a discussion with @vijaysharwar over at https://github.com/COVID19Tracking/website/pull/461#issuecomment-611721183, [the color definitions in _Map.js](https://github.com/vijaysharwar/website/blob/8acf4584440d302b0dac9b1b4577599d932ae6d4/src/pages/dashboard/charts/_Map.js#L61-L92) could be refactored to [reference colors.scss directly](https://github.com/COVID19Tracking/website/blob/master/src/stories/2-components/03-Colors.stories.js#L2).

**Comment by vijaysharwar** [comment]
@beep I think this has been implemented in `master` [_Map.js](https://github.com/COVID19Tracking/website/blob/50690338037d5a0042595f4f3a82e87481709bff/src/pages/about-data/visualization-guide/charts/_Map.js#L22). Can probably close.

**Comment by beep** [comment]
Nice, @vijaysharwar! Thanks for the heads-up! Closing.
