### ISSUE TITLE
Tests per day column in table

### ISSUE THREAD

**Issue by raj594** [COVID19Tracking/website#471]
Can y'all add a column in the table that lists the total tests performed on each day?  This will provide useful context to consumers of the data on your website as it more easily allows them to gauge the influence of the number of tests per day on the trajectory of total confirmed/active cases.

<img width="1282" alt="Screen Shot 2020-04-09 at 8 47 55 PM" src="https://user-images.githubusercontent.com/29382575/78954979-6d494e00-7aa3-11ea-8db2-c52edda9be26.png">

**Comment by schwartzadev** [comment]
I'm on board to add this -- it seems like a logical addition to me.

**Comment by raj594** [comment]
Could probably drop the states tracked column since it seems to have reached the maximum number?  Is there more than 56 "states"?

**Comment by raj594** [comment]
I also saw that you guys are considering other table libraries in another issue.  Might be able to put some of this data in tooltips, so for example if I hover over "Total Tests" in today's row it could show amount of new tests today.  Same with positive/negative/deaths.

**Comment by raj594** [comment]
Oh nice, just saw you already opened a PR.  Good shit.
