### ISSUE TITLE
Tooltip tables aren't styled anymore

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#477]
Tooltip tables lost styling and alignment. What it looks like now: 

![image (8)](https://user-images.githubusercontent.com/39416238/79004154-277f9a80-7b22-11ea-8480-1dd3214cfe4d.png)

What it should look like: 

<img width="606" alt="Screen Shot 2020-04-02 at 1 32 22 AM" src="https://user-images.githubusercontent.com/39416238/79004232-54cc4880-7b22-11ea-82fa-1089d4571133.png">

Slack chat:
re: the table regression, it could have to do with this: https://github.com/COVID19Tracking/website/issues/453 - there was some bleed-over between styles for the SummaryTable component used elsewhere in the site. Looks like that's been fixed now so some of the styles that were previously unintentionally inherited may need to be duplicated to the styles in src/pages/dashboard/charts/map.scss

**Comment by nselikoff** [comment]
Taking a look at this now.
