### ISSUE TITLE
see all data from [state abbreviation]

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#478]
- let's replace the name of the state in "See all data from [state]" with the **"Data from [abbreviation of the state]"** (Get rid of "See all"). right now it's breaking it into two lines: 

<img width="1198" alt="Screen Shot 2020-04-10 at 1 17 43 PM" src="https://user-images.githubusercontent.com/39416238/79009655-045ae800-7b2e-11ea-949b-3039c9bb739a.png">

- le'ts also make the font a bit smaller 

@AaronMullan could you take care of this one?

**Comment by AaronMullan** [comment]
<img width="168" alt="Screen Shot 2020-04-10 at 1 41 34 PM" src="https://user-images.githubusercontent.com/50382381/79021713-20ac5400-7b31-11ea-8a65-340a6ea9544f.png">

Should the font of the link still be smaller?

**Comment by julialedur** [comment]
this is good! let's make the titles (state names in bold) a tad bigger, so there's a hierarchy

**Comment by AaronMullan** [comment]
Here's the current version (12px) and also 14 and 16px versions for comparison.  Do you like either 14 or 16?

![12px (current)](https://user-images.githubusercontent.com/50382381/79030497-1ea4be00-7b4e-11ea-920a-5a10972efd68.png)
![14px](https://user-images.githubusercontent.com/50382381/79030499-1f3d5480-7b4e-11ea-959a-43fce296a436.png)
![16px](https://user-images.githubusercontent.com/50382381/79030501-1f3d5480-7b4e-11ea-94cc-41dca3905d68.png)

**Comment by julialedur** [comment]
14 is great! thanks, @AaronMullan! :)

**Comment by AaronMullan** [comment]
Updated the PR to have the titles be 14px.
