### ISSUE TITLE
Add toggle for "tests per capita" on sm multiples 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#479]
hey @vijaysharwar, 
could you add that toggle button for tests per capita on the sm multiples like we talked about yesterday? 

please follow style of the map buttons: 

<img width="286" alt="Screen Shot 2020-04-10 at 1 25 53 PM" src="https://user-images.githubusercontent.com/39416238/79009963-d1fdba80-7b2e-11ea-81c7-1a16790d9dd0.png">

we'll have "Total tests" and "Test per capita"

**Comment by vijaysharwar** [comment]
Yep, I can work on this.

**Comment by julialedur** [comment]
thank you! :)

**Comment by vijaysharwar** [comment]
Anyone know why there are two different data files with population?

- [/src/data/visualization/state-populations.json](https://github.com/COVID19Tracking/website/blob/e3d26eb07d2c30e385f1a6c47ae2279aa8ccabcb/src/data/visualization/state-populations.json) used in [_MapContainer.js#L10](https://github.com/COVID19Tracking/website/blob/e3d26eb07d2c30e385f1a6c47ae2279aa8ccabcb/src/pages/dashboard/_MapContainer.js#L10)
- [/src/pages/dashboard/data/_state-populations.js](https://github.com/COVID19Tracking/website/blob/e3d26eb07d2c30e385f1a6c47ae2279aa8ccabcb/src/pages/dashboard/data/_state-populations.js) used in [_Map.js#L9](https://github.com/COVID19Tracking/website/blob/e3d26eb07d2c30e385f1a6c47ae2279aa8ccabcb/src/pages/dashboard/charts/_Map.js#L9)

Which is correct and/or should be used to normalize these state testing charts per capita? @goleary @jeremiak?

**Comment by goleary** [comment]
the first one `/src/data/visualization/state-populations.json` is correct. If you could remove the other one and update the import that would be awesome!

**Comment by vijaysharwar** [comment]
@goleary mind making that a separate cleanup task/issue, to keep scope of this concise?

Next issue is some of the territories don't have populations in the JS data set, namely:

- Guam
- Virgin Islands
- Marshall Islands
- American Samoa

For the time being, I can create a local hash map in [_StateCumulativeTestsContainer.js](https://github.com/COVID19Tracking/website/blob/dashboard-gatsby/src/pages/dashboard/_StateCumulativeTestsContainer.js) for these missing values, but it's a little brittle. Thoughts @goleary?

Another observation: "Marshall Islands" is mapped to the [state code "MP"](https://github.com/COVID19Tracking/website/blob/dashboard-gatsby/src/pages/dashboard/_utils.js#L45), but that code is for the entirety of the [Northern Mariana Islands](https://en.wikipedia.org/wiki/Northern_Mariana_Islands). Do we want population of that territory, or just the Marshall Islands? Thoughts @julialedur?

**Comment by julialedur** [comment]
it looks like we track [data for the entire territory](https://covidtracking.com/data), so let's go with the total population of Northern Mariana Islands. we should also change the title on the sm multiples.

**Comment by vijaysharwar** [comment]
@julialedur using "Northern Mariana Islands" doesn't fit on one line:

<img width="524" alt="Screen Shot 2020-04-10 at 5 27 14 PM" src="https://user-images.githubusercontent.com/63169602/79024339-9ffd5000-7b50-11ea-97b7-ffc658f14463.png">

Can we abbreviate? "N. Mariana Islands"?

**Comment by vijaysharwar** [comment]
See PR above. Two recommendations for @julialedur to consider:

- Abbreviate "Northern Mariana Islands" to fit on one line as per comment above
- New text for the "See all" links. It's very repetitive/wordy. Perhaps use state code, and truncate to "See all XX data". Or a link/caret icon like "> all XX data"

**Comment by vijaysharwar** [comment]
Looks like the second item is being tackled via https://github.com/COVID19Tracking/website/pull/493/files.
