### ISSUE TITLE
Missing end-tags? - Parsing Errors on a Few Tables Using Google Apps Script

### ISSUE THREAD

**Issue by weatherman0516** [COVID19Tracking/website#480]
Please check your html code for the following state level tables: Connecticut , Delaware, Florida, Oregon, Rhode Island, and South Dakota. I get the below error only for those main data tables using Google Apps Script.

![err](https://user-images.githubusercontent.com/63274008/78625578-71cef600-785a-11ea-9d99-9d7243616f02.PNG)

The issue should be able to be replicated using:
```
var html = UrlFetchApp.fetch();
var page = html.getContextText();
var data = XmlService.parse(page);
```

**Comment by kevee** [comment]
This is an issue with markdown parsers, because it generates non-closed <br> tabs.

If you are trying to use apps script to get our data, please just go [ahead and use our handy apis!](https://covidtracking.com/api)
