### ISSUE TITLE
death chart collapsible and side by side 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#483]
- let's make the horizontal death chart collapsible like in the [old version ](https://deploy-preview-136--upbeat-lovelace-3e9fff.netlify.com/dashboard/)

- let's also use all the previous styles (like right-align state names)

- bars should be #4C5559

- labels should be #828688 

- grids should be #9CA1A2 and 0.7 

when you're done with that, could you position the two death charts side by side? thanks!

**Comment by melbee** [comment]
@julia326 I applied all the changes from the bullet points in this PR. 

for the final request "when you're done with that, could you position the two death charts side by side? thanks!", can we create a new separate issue for that and for all final layout and styling updates after all core functionality and charts are added? 

I think this will help reduce conflicts, duplicate work and make sure we apply final updates in consistent way at once across all components

**Comment by julia326** [comment]
Hi @melbee! I think you probably mean to tag @julialedur (on this and related visualization github issues)?
