### ISSUE TITLE
style map slider 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#485]
let's tweak the slider style a bit and: 

- remove the gradient
- make slider fill #EDF1F2 and stroke #B7BCBD and thin 
- make circle fill #ffffff and stroke #000000 

it will look like this: 

<img width="537" alt="Screen Shot 2020-04-10 at 2 01 47 PM" src="https://user-images.githubusercontent.com/39416238/79012387-2c4d4a00-7b34-11ea-8c39-c1211aa6c37e.png">

**Comment by nselikoff** [comment]
I'll take this one
