### ISSUE TITLE
make sm multiples collapsible on mobile 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#487]
@vijaysharwar could you tackle this one? 

sort of like this: 

<img width="532" alt="Screen Shot 2020-04-10 at 2 11 53 PM" src="https://user-images.githubusercontent.com/39416238/79012832-44719900-7b35-11ea-80ed-0f65de407c8f.png">

"Show all states" and "Show less states"

**Comment by vijaysharwar** [comment]
@julialedur how many state charts should be shown in the collapsed view? Or, thinking responsively, how many rows might be the better question. Current layout:

- < 480px: 2 charts per row
- 480-799px: 4 charts per row
- 800-1199px: 5 charts per row
- 1200px and above: 7 charts per row

**Comment by julialedur** [comment]
i think it should be how many rows fit on the screen without scrolling. 

so:
< 480px: 3 rows
480-799px: 4 rows
800-1199px: 4 rows
1200px and above: feel like it doesn't need to be collapsible?

**Comment by vijaysharwar** [comment]
@julialedur this issue is done and can be closed! 🚀
