### ISSUE TITLE
add note, source and bylines at the bottom 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#488]
please refer to [old dashboard](https://deploy-preview-136--upbeat-lovelace-3e9fff.netlify.com/dashboard/) and add those elements. 

Note should be updated to: 

**Notes:** We derive the total value by adding together the positive and negative value for each state. This is to account for differences in how states reporting pending tests; California has been inconsistent in its timing of reporting. We used faster updating sources until April 1, when we standardized on [California's new data dashboards](https://public.tableau.com/views/COVID-19PublicDashboard/Covid-19Public?:embed=y&:display_count=no&:showVizHome=no). This led to a drop in cases and deaths, as the state’s data lags some other sources.

Bylines will be updated with everyone's names later

**Comment by AaronMullan** [comment]
PR incoming
