### ISSUE TITLE
Typography conflicts with CSS

### ISSUE THREAD

**Issue by vijaysharwar** [COVID19Tracking/website#490]
I'm trying to style some smaller text in the state cumulative tests, but am finding it impossible to override the global line-height that is set on the shorthand `font` attribute and `html` root element by [Typography](https://github.com/COVID19Tracking/website/blob/master/src/utilities/typography.js#L22). I think that [typography library](https://www.npmjs.com/package/typography) is better suited to sites that don't need a lot of granular control.

In the dashboard, at least, I think we need to be able to style elements in a more modular/traditional way, and Typography is getting in the way:

<img width="1920" alt="Screen Shot 2020-04-10 at 2 14 01 PM" src="https://user-images.githubusercontent.com/63169602/79013315-77685c80-7b36-11ea-9d2d-6a232abf7d49.png">

Recommendations:
- Remove Typography
- Create global SCSS styles to handle baseline typographic styling on root level elements
- Cleanup/refactor how styles are applied across the site (moving SCSS files out of the `/pages` directory for starters)

**Comment by kevee** [comment]
This is not a bug, it is by design.

Typography applies rules to the HTML element so it's easy to override. We decided to move SCSS files into the pages directory because we want modular components proximate to their styles #427. This is [considered best practice](https://www.gatsbyjs.org/docs/css-modules/) for Gatsby and CSS modules.

To fix this specific issue, I would suggest applying a class to charts, any line height you set on top of that will override what we have site-wide.

**Comment by vijaysharwar** [comment]
@kevee Thanks for the response :)

I tried applying overrides as you describe, but couldn't get it to work. `line-height` as an attribute on a class is ignored, because the setting on `html` with the `font` shorthand attribute takes precedence.

Even when I tried making an overly super specific rule, like:

```
html .my-class {
  font: 12px/1.5 'sans-serif';
}
```

I was unable to successfully override Typography, and I'm not sure why. Possibly scoping, or how Typography JS is injected to the page. Even if that worked, I'd need to copy all the shorthand font values, which seems brittle. If you (or someone else) has time, please try and let me know if you figure out a way?

RE keeping the SCSS files in `/pages`, while it _is_ best practice to have scoped CSS modules linked to components, I believe they should be outside of that directory. Reason being that Gatsby examines `/pages` to specifically map JS files to site routes and URL paths. Feels anti-patterny.

If you look at the [example site](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-css-modules/src) linked in the best practice doc you linked, they have two parallel directories for `/pages` and `/styles`.

¯\\_(ツ)_/¯

**Comment by kevee** [comment]
Right, some css are still in pages because some pages have specific design needs. Those will make it to components later. 

So for the line-height issue, this worked fine:

```css
.small-multiples-chart {
    line-height: 1rem;
}
```
![image](https://user-images.githubusercontent.com/270536/79020846-f1551180-7b47-11ea-99d3-a63b72a2422c.png)

**Comment by vijaysharwar** [comment]
@kevee ah, I didn't think to use `rem` units. Usually `line-height` is simply be a multiplier, just a number. This works now, I suppose. Will implement during work on https://github.com/COVID19Tracking/website/issues/479.
