### ISSUE TITLE
Feature request: Volunteer Credits page form 

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/website#496]
Please let us know the page you are talking about, and your content suggestions!

About the Project at https://covidtracking.com/about-project has a list of contributors at the bottom -- currently that is updated manually from a Google Sheet. We'd like it to be an easier process than that: @kissane suggested that the existing code for press links could be reused for this purpose. Volunteers do need to be able to opt in to the credits, so no mass harvesting without permission, but other than that I have no specs.

**Comment by amandafrench** [comment]
However I do have OPINIONS, one of which is maybe that should be a whole Separate Page now that our community is groooooowing. kthxbye

**Comment by kevee** [comment]
I'm thinking we can use the Slack API to just read all our volunteers from Slack. How about "if you join the channel #put-me-on-the-website you will be automatically added?

**Comment by kissane** [comment]
You know, I…do not hate that.

**Comment by kissane** [comment]
Whatever is easier for volunteers to do, which it seems like Slack channel is probably easier.

**Comment by amandafrench** [comment]
Man, I feel like I should hate the proliferation of Slack channels more than I do, but they are damn useful.

**Comment by amandafrench** [comment]
Would that method allow people to put not just their names but also their links?

**Comment by kevee** [comment]
We could just use their profile info from Slack.

**Comment by kevee** [comment]
I did a very short search and here's some thoughts:

There's already a few plugins to pull slack users into Gatsby. The technical part should be easy.

We can add new profile fields for public website, public name, and public team membership. 

They can add themselves to the public website through either:
Users join a special channel
Or
They just select a "make me public" custom field in their profile.

The latter is easy to explain, the former lets us administer membership more easily, since folks can be removed from the channel or added if needed by admins

**Comment by muamichali** [comment]
I am going to work on this! Starting with a test slack instance until I have it down. Will invite you @amandafrench  and @kissane for testing soon.

**Comment by kevee** [comment]
Quick note: This will require creating a new API integration with `users:read` scope.

**Comment by kevee** [comment]
**Crazy idea # 4722**: In the past, I've always tried list numbers of volunteers to illustrate engagement & impact. What if we had this page lede with "We have [x number] volunteers, [y number] of whom have been active in the past week. Here are some of those:"

**Comment by amandafrench** [comment]
I'd love that! Have been reporting Slack members & guests in #status from the Slack member directory. Be great if you have some way of measuring "active" volunteers too (e.g., who has posted anything in Slack in the past week).

**Comment by kevee** [comment]
I've setup the three new fields, and sent @muamichali the API keys.

**Comment by kevee** [comment]
@muamichali has all the volunteer stuff from Slack done. Great job! Now let's get this into a working volunteer page. Steps:

- [ ] Create a new page at `/src/pages/about-project/volunteers.js`
- [ ] Add the Contentful snippet with the slug `volunteer-preamble` to the top. Check out the [Contact page for an example](https://github.com/COVID19Tracking/website/blob/master/src/pages/contact.js) of querying for the snippet on the bottom, then injecting it's HTML on top.
- [ ] Add a plugin config for the volunteer file to `gatsby-config.js` under `plugins`:

```javascript
...stuff
{
      resolve: 'gatsby-source-covid-tracking-api',
      options: {
        file: './_data/v1/volunteers.json',
        type: 'CovidVolunteers',
      },
    },
...stuff
```

- [ ] Add a query to pull all the volunteers ordered by name and put them in a simple unordered list under the snippet.
- [ ] Let's give that unordered list a nice `column-count: 3` and see if it looks better. Then we can get design input

**Comment by kevee** [comment]
Closing per #647 

Great work, @muamichali !
