### ISSUE TITLE
Remove screenshots of Western Samoa page from American Samoa 

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/website#499]
Please let us know the page you are talking about, and your content suggestions!

From 3/16 to 3/26 we used the wrong page for American Samoa: we used a page for Western Samoa, which is its own country and not a US territory. On https://covidtracking.com/data/state/american-samoa the first *correct* screenshot is from Fri March 27 7:02pm. 

We also need to fix our historical data, of course, and I will file an issue about that and link it here.

**Comment by amandafrench** [comment]
See issue to correct historical data at https://github.com/COVID19Tracking/issues/issues/178

**Comment by kevee** [comment]
Is this a thing that needs to be fixed in our data sources, or do you need the website to override the API data?

**Comment by amandafrench** [comment]
The data sources are all fixed now (I hope), but it's just the earlier screenshots of the wrong website that I think should be removed. Note what we've done in related issue https://github.com/COVID19Tracking/issues/issues/178 which hero @careeningspace just closed.
