### ISSUE TITLE
make CDC charts smaller and centered

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#503]
<img width="1270" alt="Screen Shot 2020-04-11 at 2 56 51 PM" src="https://user-images.githubusercontent.com/39416238/79052459-b238c600-7c04-11ea-8f28-b208fb00601a.png">

- let's make these first two charts 40% smaller on the page
- not so far apart 
- and centered on the page

**Comment by goldfarb** [comment]
- I'm going to work on this -
