### ISSUE TITLE
Screenshot ordering on state pages

### ISSUE THREAD

**Issue by hammer** [COVID19Tracking/website#507]
What is the logic for the ordering of times in the "Screenshot" column on state pages? [SC](https://covidtracking.com/data/state/south-carolina), for example, has "6:14 pm 12:15 pm 6:14 am 12:15 am" for April 11. These times don't appear to be ordered lexicographically or chronologically. It would be nice to order them chronologically.

**Comment by kevee** [comment]
There is no order! I'll fix that.

**Comment by kevee** [comment]
Here's a [preview of the SC page](https://deploy-preview-509--upbeat-lovelace-3e9fff.netlify.com/data/state/south-carolina). Looks good:

![image](https://user-images.githubusercontent.com/270536/79066706-22d4f680-7c88-11ea-838a-a0091871f54f.png)
