### ISSUE TITLE
Redirect performance - unnecessary 301?

### ISSUE THREAD

**Issue by scottjehl** [COVID19Tracking/website#519]
Hi there. There's an odd 301 redirect on some pages that seems to occur on every load. It ends up delaying page rendering by up to 2 seconds on an average mobile phone. It looks like it's there to add a trailing slash and then remove it... but I'm not sure. I can see it in WebPageTest waterfalls so it's clearly not just a clientside issue.

I'm not sure if it's intentional, but if that 301 could be dropped, the page could render almost 2 seconds earlier on 3G.

![](https://user-images.githubusercontent.com/214783/79026446-7d6a3780-7b4e-11ea-9fab-8fd938de64df.png)
https://www.webpagetest.org/result/200410_W2_b611f61d9b39e6b1023b60001f0f3c65/2/details/#waterfall_view_step1

**Comment by kevee** [comment]
This was related to the addition of `gatsby-plugin-remove-trailing-slashes` - I'll do a PR later today for testing.

**Comment by scottjehl** [comment]
Sounds good. Maybe a canonical meta tag would get what you need for SEO there without the url cleanup. That idea came from @hankchizljaw

**Comment by hankchizljaw** [comment]
Yeh what I was getting at was say you have `http://example.com/my-page` and you wanted to enforce trailing slashes, you could have:

```html
<link rel="canonical" href="http://example.com/my-page/">
```

**Comment by kevee** [comment]
So here's a deploy preview. Now we have the opposite issue:

https://deploy-preview-525--upbeat-lovelace-3e9fff.netlify.com/data
redirects to:
https://deploy-preview-525--upbeat-lovelace-3e9fff.netlify.com/data/

I am calling this issue on hold for now until we can do testing in a separate Netlify app.

**Comment by scottjehl** [comment]
Interesting. Sounds good. I think that might be a reasonable enough fix if the links on the site go to that trailing-slash version. As long as the site links to the eventual url you want it to resolve to, I'd think that'll essentially avoid the redirect.
