### ISSUE TITLE
X axis labels get cut off on bar chart

### ISSUE THREAD

**Issue by jeremiak** [COVID19Tracking/website#531]
The x axis labels are getting cut off on the right hand side, we should make sure that no axis labels are getting cut off on the charts. Its preferable to label an axis point that is further from the end of the data domain.

<img width="497" alt="Screen Shot 2020-04-14 at 1 15 39 PM" src="https://user-images.githubusercontent.com/780941/79254109-3c299e80-7e52-11ea-9250-b7a6ece3ba9f.png">

**Comment by vijaysharwar** [comment]
I'm working on this alongside https://github.com/COVID19Tracking/website/issues/530.

**Comment by vijaysharwar** [comment]
@julialedur this is resolved via #552, can close this Issue.
