### ISSUE TITLE
Vertical bar chart too wide for the page on mobile

### ISSUE THREAD

**Issue by jeremiak** [COVID19Tracking/website#532]
The vertical bar chart showing state level deaths is too wide and doesn't wrap on smaller displays. This leads to a horizontal scroll. Let's make the chart wrap into the single column layout we use for phones.

<img width="434" alt="Screen Shot 2020-04-14 at 1 18 37 PM" src="https://user-images.githubusercontent.com/780941/79254329-932f7380-7e52-11ea-9dc0-547e4f41f34c.png">
<img width="422" alt="Screen Shot 2020-04-14 at 1 18 42 PM" src="https://user-images.githubusercontent.com/780941/79254331-93c80a00-7e52-11ea-9fa4-289259c48321.png">

**Comment by goleary** [comment]
i can take a stab at this.
