### ISSUE TITLE
Area chart is way too big

### ISSUE THREAD

**Issue by jeremiak** [COVID19Tracking/website#533]
The area chart we use under the heading of "Positive tests and total tests in the US" is far too big for the page, making it hard to read. Let's make the width consistent with our other charts.

As you can see in the screenshot, I can't get the whole chart in a single shot.
<img width="1401" alt="Screen Shot 2020-04-14 at 1 20 51 PM" src="https://user-images.githubusercontent.com/780941/79254568-eb667580-7e52-11ea-94a5-b32640056d35.png">

**Comment by goldfarb** [comment]
-- I'll give this a shot --
