### ISSUE TITLE
"per million people on map" is misleading

### ISSUE THREAD

**Issue by goleary** [COVID19Tracking/website#534]
@julialedur 
This makes it look like the US has 23k deaths per million people.

![image](https://user-images.githubusercontent.com/16123225/79259258-43947c00-7e41-11ea-8343-b32cea8a3c30.png)

The number presented here is absolute.  Options:
- make the number per capita
- move the text elsewhere (maybe that's accounted for in what you and @jeremiak have been discussing)

**Comment by hsitz** [comment]
I would add that data display in general should have 'per capita' items.   I've noticed that there're are a lot of poor comparisons being made between states (and countries) from people comparing only raw numbers.  Per capita data is a much better way to compare.

How, for example, am I to compare the statistics for Nebraska to those for Kentucky?  Nebraska has less than half as many people, so their raw numbers would be less than half of Kentucky even if they were identical per capita.  Many people lack a good feeling for the population of different states, and even if you have a good feeling you have to constantly do the 'per capita' estimates in your head to do proper comparisons.

**Comment by goleary** [comment]
go this
