### ISSUE TITLE
data for cases by counties available?

### ISSUE THREAD

**Issue by WeileiZeng** [COVID19Tracking/website#54]
Is data for cases by counties in US available?

I am looking for data for Riverside counties at CA. I can manually read from their announce website, but just wondering if there are any existed data source?

Thanks!

**Comment by kissane** [comment]
Hi @WeileiZeng, I would send you to the Los Angeles Times for their data on CA counties, for now https://www.latimes.com/projects/california-coronavirus-cases-tracking-outbreak/

**Comment by WeileiZeng** [comment]
Thank you very much!
