### ISSUE TITLE
IA / Nav edits - prepare for blog launch 

### ISSUE THREAD

**Issue by sarawb** [COVID19Tracking/website#541]
It's time to launch the blog! 

Opening this issue to document decisions made on Slack with @kissane and @schwartzadev. 

**Before we launch**
- Blog styling is mostly good to go, ideally we'll get #535 reviewed and merged in before we launch (this is in process). 
- @kissane is confirming final content for first blog post and setting up in Contentful. We won't make the blog live on the site till we have a first post up. 

**Launch process** 
- Lock Netlify builds
- Tinker with staging 
- Update the global nav on GH to 1) remove How You Can Help from main nav and 2) Add blog instead 
- Move How You Can Help page to About the Project section using Contentful subnavs 
- Add 301 redirect from /help to /about-project/help 
- Deploy from staging

**Comment by schwartzadev** [comment]
Looks great! Thanks for porting this all here. #548 will be the step to move the _global_ nav when we're ready to go.

**Comment by schwartzadev** [comment]
I'm just adding a more detailed launch process here:

Launch Process
-----

1. Lock Netlify builds
2. Merge #548 to adjust the global nav and add redirect from `/help` to `/about/help`
3. Update Contentful
  a. Replace dummy blog post content with real blog post content
  b. Adjust How You Can Help page
    i. Change Slug to `/about/help`
    ii. Change Navigation Group to `About the project`
4. Deploy from staging
5. Unlock Netlify

**Comment by schwartzadev** [comment]
Live @ https://covidtracking.com/blog/ :tada:
