### ISSUE TITLE
buttons still turn blue on click 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#542]
this weird thing is still happening when you click buttons: 

<img width="314" alt="Screen Shot 2020-04-14 at 3 48 40 PM" src="https://user-images.githubusercontent.com/39416238/79269105-e5c85a00-7e69-11ea-82c7-683f81e17e52.png">

<img width="201" alt="Screen Shot 2020-04-14 at 4 06 00 PM" src="https://user-images.githubusercontent.com/39416238/79269109-e660f080-7e69-11ea-9ee8-f7d18a151007.png">

**Comment by goleary** [comment]
we removed this a while back but it created an accessibility issue so we readded it.

elsewhere on the site has a similar effect:
![image](https://user-images.githubusercontent.com/16123225/79271197-42207f00-7e54-11ea-9931-1b0086aaca1d.png)

Do we want to replicate this style in the dashboard?

**Comment by julialedur** [comment]
yes! was just about to comment this here! let's do the dashed border in #D0D7DB? 
so it's not conflicting with our colors

**Comment by AaronMullan** [comment]
I'll start on this one.

**Comment by AaronMullan** [comment]
I don't see that dashed border on focus elsewhere on the site?

**Comment by julialedur** [comment]
it's on the homepage buttons too! 

<img width="261" alt="Screen Shot 2020-04-14 at 4 48 25 PM" src="https://user-images.githubusercontent.com/39416238/79278910-cc7bd980-7e7a-11ea-96dc-dd3eb9ecc7ba.png">

**Comment by AaronMullan** [comment]
So weird, I don't see it!

**Comment by AaronMullan** [comment]
<img width="255" alt="Screen Shot 2020-04-14 at 3 10 28 PM" src="https://user-images.githubusercontent.com/50382381/79279100-1d330880-7e62-11ea-88a7-31f4f02a6230.png">

**Comment by julialedur** [comment]
that's weird! did you click it?

**Comment by AaronMullan** [comment]
OK I think I understand.  It shows up on focus, not hover.  That color looks black to me, though, right?

**Comment by schwartzadev** [comment]
Just hopping in here! I think the color is `#012656` for the "Get the Data" button on the homepage.

**Comment by AaronMullan** [comment]
Thanks, schwarzadev.  I think you are correct.  Are we supposed to refer to that as $color-blueberry-1?

But maybe on the dashboard it should be D0D7DB  aka $color-slate-9?

**Comment by AaronMullan** [comment]
I put in PR #553

**Comment by julialedur** [comment]
thanks!

**Comment by AaronMullan** [comment]
![Screen Shot 2020-04-14 at 4 05 20 PM](https://user-images.githubusercontent.com/50382381/79282330-c5989b00-7e69-11ea-8239-26e989edde6a.png)

**Comment by vijaysharwar** [comment]
This should be fixed by https://github.com/COVID19Tracking/website/pull/589. I think it's a dupe of https://github.com/COVID19Tracking/website/issues/564 at this point.
