### ISSUE TITLE
make date follow map slider cursor 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#545]
- let's delete the big date at the top 
- let's make the date follow the slider circle on the map, like this: 

<img width="535" alt="Screen Shot 2020-04-14 at 4 18 09 PM" src="https://user-images.githubusercontent.com/39416238/79270189-a995f900-7e6b-11ea-8282-2bfdc3f72c82.png">

it's a good solution for the weird alignment of first and last date we have right now

**Comment by goleary** [comment]
this seems like this shouldn't be a blocker for us shipping.

**Comment by julialedur** [comment]
sure, we can change this later! but then let's just delete the dates below the slider, that alignment is confusing

**Comment by goleary** [comment]
really? i'd be more confused without any dates shown.

I can adjust the padding on the left data to more center align it with the beginning of the slider.
![image](https://user-images.githubusercontent.com/16123225/79277893-86fde300-7e5f-11ea-8bf2-b3182534926e.png)

**Comment by julialedur** [comment]
okay, sounds good! 
let's center-align the dates with datapoints then? so april date is also center aligned?

**Comment by goleary** [comment]
![image](https://user-images.githubusercontent.com/16123225/79287419-976e8780-7e78-11ea-97dc-c52427b40cf0.png)
done for now. Going to remove this from the project since the further refinement doesn't block deployment

**Comment by kevee** [comment]
@goleary - Should this issue be closed?
