### ISSUE TITLE
gray scale on map is the old one 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#546]
the Slate color scale on the deaths map is still the old one. 

should be this: 
#313638
#4C5153
#676B6D
#828688
#9CA1A2
#B7BCBD
#D2D6D7
#EDF1F2

**Comment by goleary** [comment]
it's pulling the colors from `/src/scss/colors.scss`.

I think this is a function of no one ever pulling the updates from master into this branch.
Once we merge from master these colors will update.

**Comment by julialedur** [comment]
got it!
