### ISSUE TITLE
Missing documentation for some API fields on https://covidtracking.com/api

### ISSUE THREAD

**Issue by julia326** [COVID19Tracking/website#555]
There are some fields that have been confusing folks, especially the cumulative/current ICU/vent/hospitalization counts. Some of these have been hidden from the website (e.g. from US Daily) but we're still serving them in the API and they're not documented  on https://covidtracking.com/api.

(These fields are more urgent than others, but it would be great to make sure we document every API field we serve on our /api page)

**Comment by gitjeff05** [comment]
I could be mistaken, but I believe these statistics are no longer tracked:

> States are currently reporting two fundamentally unlike statistics: current hospital/ICU admissions and cumulative hospitalizations/ICU admissions. Across the country, this reporting is also sparse. In short: it is impossible to assemble anything resembling the real statistics for hospitalizations, ICU admissions, or ventilator usage across the United States. As a result, we will no longer provide national-level summary hospitalizations, ICU admissions, or ventilator usage statistics on our site. 

https://covidtracking.com/data

Perhaps a "deprecated" link under each endpoint on the API page that expands to show all deprecated stats would clear up confusion.

**Comment by muamichali** [comment]
Tagging @friej715 so you can update the Swagger documentation with these fields if they are not already there https://github.com/COVID19Tracking/website/pull/517

**Comment by kevee** [comment]
Fixed in #517
