### ISSUE TITLE
bars should be purple on CDC charts 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#562]
let's change the color of the bars on these two charts to #575AAD
 
<img width="682" alt="Screen Shot 2020-04-15 at 11 10 18 AM" src="https://user-images.githubusercontent.com/39416238/79353992-ced94480-7f09-11ea-9209-0b3521af9f0d.png">

**Comment by vijaysharwar** [comment]
I'm working on this.

**Comment by vijaysharwar** [comment]
Actually, this looks like it has already been fixed in `master` via https://github.com/COVID19Tracking/website/commit/c7ebb9a7ac7cf89be5b287353c5e3501fe165a6c. @goleary good to close this issue?

**Comment by goleary** [comment]
should be but something didn't take...it's still black on master.

**Comment by vijaysharwar** [comment]
@goleary when I pull down `master` locally, though, they're purple as expected. So you mean something isn't taking on _deployment_ of `master`? Very odd...

**Comment by vijaysharwar** [comment]
The `fill` attribute should be filled in at the React component rendering level, so this isn't even a matter of botched CSS or something.

Here's what I have inspecting locally:

<img width="1601" alt="Screen Shot 2020-04-16 at 12 19 49 PM" src="https://user-images.githubusercontent.com/63169602/79480877-b423d000-7fdc-11ea-9e69-915979a89630.png">

Whereas here's what's currently on https://covidtracking.com/dashboard

<img width="1628" alt="Screen Shot 2020-04-16 at 12 20 58 PM" src="https://user-images.githubusercontent.com/63169602/79480942-cef64480-7fdc-11ea-8884-b795b0dec5db.png">

Note the missing `fill` attribute, but that's set explicitly in the JS here, so I don't see how it's possible for it to be missing:

https://github.com/COVID19Tracking/website/blob/09df03ed92897cbb64ddc4d6dc5ddf93e4e1d522/src/pages/dashboard/_CDCComparisonContainer.js#L122

Unless the deployed code itself was stale somehow. Can we test a Netlify preview deployment from latest commit in `master`?

**Comment by goleary** [comment]
sometimes I see a difference in what is shown using `gatsby develop` and the end result of `gatsby build`.

This is due to build process not being able to execute all JS for some reason.  I got around this for the map by putting the colors in .scss instead of in JS.

**Comment by goleary** [comment]
tackling this
