### ISSUE TITLE
changes to US death charts 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#563]
<img width="463" alt="Screen Shot 2020-04-15 at 11 09 02 AM" src="https://user-images.githubusercontent.com/39416238/79354143-03e59700-7f0a-11ea-8108-37e94c2c4f4f.png">

- bars on this chart should be #4C5559 
- let's change it to **daily new deaths** instead of cumulative

**Comment by goldfarb** [comment]
- I'll work on this -
