### ISSUE TITLE
not all buttons are styled the same on focus

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#564]
please make sure all buttons on the page are styled the same on focus. these ones are different right now: 

<img width="131" alt="Screen Shot 2020-04-15 at 11 16 16 AM" src="https://user-images.githubusercontent.com/39416238/79354796-dea55880-7f0a-11ea-9d73-10b874c37785.png">

<img width="229" alt="Screen Shot 2020-04-15 at 11 04 58 AM" src="https://user-images.githubusercontent.com/39416238/79354815-e402a300-7f0a-11ea-839f-363d6de6dbc4.png">

also, there's something weird happening when you click the state name on the sm multiple:

<img width="178" alt="Screen Shot 2020-04-15 at 11 16 00 AM" src="https://user-images.githubusercontent.com/39416238/79354903-009edb00-7f0b-11ea-833f-6aa313a895c3.png">

buttons should follow this style:
<img width="279" alt="Screen Shot 2020-04-15 at 11 20 00 AM" src="https://user-images.githubusercontent.com/39416238/79355027-288e3e80-7f0b-11ea-81b9-92b4449658ba.png"> 

state links should follow this style:
<img width="211" alt="Screen Shot 2020-04-15 at 11 20 36 AM" src="https://user-images.githubusercontent.com/39416238/79355066-35ab2d80-7f0b-11ea-828d-0c39de7a669e.png">

**Comment by AaronMullan** [comment]
I will start on this now.  I will target the specific divs which contain the buttons, as well as links.

**Comment by vijaysharwar** [comment]
@AaronMullan I actually just started on this...

**Comment by vijaysharwar** [comment]
I'm thinking now that we're merged to `master`, it might best be handled by editing `global.scss`.

**Comment by AaronMullan** [comment]
OK I'll look for another issue.

**Comment by vijaysharwar** [comment]
PR opened, but probably needs review from the wider website team since global styles have been updated.

**Comment by kevee** [comment]
Closing per #589
