### ISSUE TITLE
labels on death chart don't align with lines 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#566]
<img width="426" alt="Screen Shot 2020-04-15 at 11 36 26 AM" src="https://user-images.githubusercontent.com/39416238/79356962-6e4c0680-7f0d-11ea-9b95-1e4f988117d2.png">

- we need to align labels with grid lines 
- let's also do 0, 2, 4, 6, 8, 10,000 for labels (only put ,000 in last label). we don't use "k" based on our style guide

**Comment by vijaysharwar** [comment]
@julialedur the x-axis labels are better aligned (centered on the vertical lines) via https://github.com/COVID19Tracking/website/pull/594.

<img width="410" alt="Screen Shot 2020-04-15 at 7 40 35 PM" src="https://user-images.githubusercontent.com/63169602/79399349-1a631100-7f51-11ea-9864-45868abb18a6.png">

**Comment by kevee** [comment]
Closing per #594
