### ISSUE TITLE
cute "M" for all labels except last 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#567]
on this chart, let's only leave the last "M", in "3M" 

<img width="643" alt="Screen Shot 2020-04-15 at 11 43 06 AM" src="https://user-images.githubusercontent.com/39416238/79357654-51fc9980-7f0e-11ea-8a28-8da8f45b7102.png">

**Comment by AaronMullan** [comment]
Currently the chart is showing in 500k increments.  Should the M's still be removed? 

<img width="562" alt="Screen Shot 2020-04-16 at 1 18 31 PM" src="https://user-images.githubusercontent.com/50382381/79502826-0832b280-7fe5-11ea-8d4b-322c93da0131.png">

**Comment by julialedur** [comment]
i don't think you have the latest version, @AaronMullan 
it should look like this: 

<img width="579" alt="Screen Shot 2020-04-16 at 3 30 21 PM" src="https://user-images.githubusercontent.com/39416238/79503382-11c91400-7fff-11ea-837a-b4750a9e939a.png">

**Comment by vijaysharwar** [comment]
Working on this.
