### ISSUE TITLE
subhead and headers styles 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#569]
**Subhead** 
- use these styles for subhead: 
<img width="167" alt="Screen Shot 2020-04-15 at 11 46 33 AM" src="https://user-images.githubusercontent.com/39416238/79358205-ecf57380-7f0e-11ea-9ede-ca999b6b9a6e.png">

- add margin-top: 50px; to first paragraph after subhead 
<img width="1069" alt="Screen Shot 2020-04-15 at 11 46 07 AM" src="https://user-images.githubusercontent.com/39416238/79358115-d6e7b300-7f0e-11ea-9a53-6c964161ee9f.png">

**Graphic titles** 
apply text-transform: uppercase; and font-size: 16px; to all graphic titles like "TOTAL DEATHS BY STATES". 
for "CDC" and "THE COVID TRACKING PROJECT" subheaders in the first chart do font-size: 13px;

**Guidelines titles**
For all tips, like "Choose colors carefully." do font-size: 13px;

**Notes** 
apply font-size: 14px; and color: #676B6D; to all notes, *s, and to notes, source and byline at the bottom of the page

**Comment by goldfarb** [comment]
-- I'll work on this --
