### ISSUE TITLE
Refresh software page

### ISSUE THREAD

**Issue by hammer** [COVID19Tracking/website#57]
We've got a lot of new repos now; perhaps @zachlipton or @julia326 could try to write up descriptions of all of them for the https://covidtracking.com/software page?

**Comment by kissane** [comment]
I added some things this morning on https://covidtracking.com/software/ and am now accepting links to other things that either

# make our work more useful (R wrapper, etc)
# use and extend our data in great ways

Not all that stuff will live on "Software & Credits" always, but it's a start. Drop em here please.

**Comment by zachlipton** [comment]
Yes! One of my short-term goals is to just take an inventory of what stuff we even have and what we're building, and getting a presentable version of that onto the website would be great.

**Comment by kissane** [comment]
@zachlipton, let's touch base on this tomorrow?

**Comment by julia326** [comment]
@kissane take a look at https://docs.google.com/document/d/1m42MrNORpe2PB5mMMa7naUG4XKx3qO7JzGsAnfvE36s/edit# - would the repo descriptions at the top of the doc be usable for this, or are you looking for more high/low-level?

**Comment by kissane** [comment]
@julia326 This is PERFECT thank you!

**Comment by olivierlacan** [comment]
Do we still use the Netlify CMS? It looks to me like we're exclusively using the [11ty static site generator](https://www.11ty.dev/) at this point. Maybe this is outdated.

**Comment by kissane** [comment]
@olivierlacan We still use the CMS as well for the billion editorial changes thoughout the day, I'll add the generator.

**Comment by kissane** [comment]
Ding ding done https://covidtracking.com/software/
