### ISSUE TITLE
Streamline dashboard chart styles

### ISSUE THREAD

**Issue by vijaysharwar** [COVID19Tracking/website#571]
Each of the chart sections on the dashboard use different CSS classes and styles. The location of styles is also not consistent. For example, some charts use classes set in [dashboard.scss](https://github.com/COVID19Tracking/website/blob/d4d6def2a9754bdff0ef1a4e44a3998834dd94de/src/pages/dashboard/dashboard.scss) while others have their own partial SCSS files, like [state-cumulative-deaths-container.scss](https://github.com/COVID19Tracking/website/blob/d4d6def2a9754bdff0ef1a4e44a3998834dd94de/src/pages/dashboard/state-cumulative-deaths-container.scss), or [charts/area-chart.scss](https://github.com/COVID19Tracking/website/blob/dashboard-gatsby/src/pages/dashboard/charts/area-chart.scss).

For all charts:

- Daily new tests in the US
- Positive tests and total tests in the US
- Total deaths in the US
- Total Deaths By States
- Cumulative tests by state

...we should come up with a single, modular system of styles and classes. Goals:

- [x] Consistency across all charts, both within charts themselves and parent containers for layout
- [X] Reduction in CSS bloat
- [x] `viewBox` only (no width and height attributes) on all `<svg>` elements to allow scaling and responsiveness across all breakpoints
- [x] Refined layout on smaller screens
- [X] Replacement of local/inline styling in JS component files in favor of reusable classes, such as y-axis stroke colors in [_AreaChart.js](https://github.com/COVID19Tracking/website/blob/d4d6def2a9754bdff0ef1a4e44a3998834dd94de/src/pages/dashboard/charts/_AreaChart.js#L60) and [_BarChart.js](https://github.com/COVID19Tracking/website/blob/d4d6def2a9754bdff0ef1a4e44a3998834dd94de/src/pages/dashboard/charts/_BarChart.js#L73)
- [ ] All chart classes moved to module SCSS file

**Comment by goleary** [comment]
I think the first step of this can be converting from using local/inline styling to use (s)css modules like is done within the rest of the repo.

I'm going to start by updating the chart components which I have already moved to `/src/components/charts` to use modules.

**Comment by vijaysharwar** [comment]
Some initial work has been done in https://github.com/COVID19Tracking/website/pull/594, where I've consolidated styles for `AreaChart`, `BarChart`, and `HorizontalBarChart` into a single `charts.module.scss` module.

Would still like to see better layout classes/styling, plus fully relying on `viewBox` only on all SVGs.

**Comment by vijaysharwar** [comment]
PR #618 takes care of a lot of the layout consistency issues and introduces a `dashboard.module.scss` file. To wrap this up, need to finish porting the remaining classes to this module file.

**Comment by vijaysharwar** [comment]
@goleary if closing this, should we make another issue to finish off the refactor of dashboard/map classes to `dashboard.module.scss`? See the last checklist item: "All chart classes moved to module SCSS file".
