### ISSUE TITLE
alignment of chart headers 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#573]
let's align our chart headers to charts. here's how it should look like: 

<img width="665" alt="Screen Shot 2020-04-15 at 12 05 01 PM" src="https://user-images.githubusercontent.com/39416238/79360030-59717200-7f11-11ea-81c4-b2e8bdfc6c4b.png">

<img width="467" alt="Screen Shot 2020-04-15 at 12 05 50 PM" src="https://user-images.githubusercontent.com/39416238/79360114-773ed700-7f11-11ea-9266-b91e30821c39.png">

<img width="910" alt="Screen Shot 2020-04-15 at 12 07 26 PM" src="https://user-images.githubusercontent.com/39416238/79360283-b0774700-7f11-11ea-8780-e81e6cc0df04.png">

and let's also remove the text-center and add  margin-top: 20px; for the map * note, so it looks like this:
<img width="1001" alt="Screen Shot 2020-04-15 at 12 09 16 PM" src="https://user-images.githubusercontent.com/39416238/79360539-14017480-7f12-11ea-9cac-d8ac3524fa1f.png">

**Comment by vijaysharwar** [comment]
Working on this.
