### ISSUE TITLE
text edits 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#576]
here are the text edits we need to make: 

- Close the space here in “it ’s” (“Because COVID-19 testing and reporting are inconsistent among states, it ’s easy to misinterpret the data.“)

- Delete mid-page header (“On this page, you will find …“) and change previous sentence to "If you plan to display data from the COVID Tracking Project yourself, please closely follow these design and visualization guidelines"

- Cut “sort of” here: “This functions as a sort of targeted social distancing technique and can help slow the outbreak.” I also suggest swapping this paragraph with the previous one. (to follow structure of other tips)

- Cut this paragraph: "By comparing the positive tests to the total tests in each state, we can get a sense of how widespread a state’s testing regime might be (though always remember to consider population densities vary wildly across the country) and if the number of positive tests is tracking roughly against the total number of tests. If it is, then we might consider that the state isn’t necessarily just getting new infections every day but that they’re also giving more tests." (second graf under "Be mindful when comparing states"

- Adjust name in small multiples: “US Virgin Islands” (instead of Virgin Islands)

- fix apostrophe code here: "This reduces the **data&apso;s** power and the reader's comprehension." 

- Update link in John Burn-Murdoch’s name to: https://twitter.com/janinegibson/status/1244519429825802240

- Link out to FactCheck.org: factcheck.org/2020/04/social-media-posts-make-baseless-claim-on-covid-19-death-toll/

- Remove links from byline names

**Comment by kissane** [comment]
I propose this stripped-down version of the intro text that punts the larger project of explaining the data-reporting failings of the CDC to our Why It Matters page so we can get folks dug into your visualizations sooner. (And also it's nice to have a single place for the CDC complaining so we can easily keep it up to date on their latest moves.)

> **Explore visualizations from the COVID Tracking Project dataset and tips to help you present the data clearly and accurately.**
> 
> Complete, up-to-date testing and outcomes data is essential to a successful public health response to the US COVID-19 outbreak, but that data [is not being published by the Centers for Disease Control and Prevention (CDC)](https://covidtracking.com/why-it-matters) or any other governmental entity.
> 
> The COVID Tracking Project exists to help fill that gap. We collect the best available testing and patient-outcomes data from every US state and territory and the District of Columbia, with full daily updates to the entire dataset.

**Comment by kissane** [comment]
Note that when we revise to the above intro, we should strike this standalone disclaimer which I've wrapped into our big all-purpose disclaimer.

> Note: Numbers undercount the full extent of COVID-19 because of the lack of widespread testing and lags in state reporting.
