### ISSUE TITLE
remove periods from months on the page

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#577]
we need to remove the period in all months to match our [style guide](https://docs.google.com/document/u/5/d/1fi_v-Bs5R3a8e3mqFe9Lz7C_LYAF49FI3KMsS1h-nqw/edit#). 
so instead of "Mar. 27", let's do "Mar 27"

(don't forget the map tooltip!)

**Comment by AaronMullan** [comment]
I will do this at 2:30 Pacific today if it's not done before.

**Comment by AaronMullan** [comment]
Oh wait I think it was super easy.  PR #612
