### ISSUE TITLE
use html codes for quotes, apostrophes and dashes 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#579]
let's use these html codes: 

open and close quotes
&#8220;     &#8221;

single quotes
&#8216; &#8217;

em dash
&mdash;

should be an easy fix with find and replace! 😉

**Comment by goldfarb** [comment]
I'll work on this - should be easy, but also need to be careful not to replace ' and " as escape characters -

**Comment by jeremiak** [comment]
This was closed by #584.
