### ISSUE TITLE
align map legend with toggle 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#581]
let's bring the legend up a little bit so it aligns with the toggle on the right and also adds some breathing space between legend and map

<img width="1260" alt="Screen Shot 2020-04-15 at 1 33 36 PM" src="https://user-images.githubusercontent.com/39416238/79368681-ca1e8b80-7f1d-11ea-81f0-84c6f6a36459.png">

**Comment by nselikoff** [comment]
I'll work on this one @julialedur
