### ISSUE TITLE
add light-gray bg to small multiple svgs 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#585]
let's do background: #EDF1F2; for the small multiples svgs, like this: 

<img width="1012" alt="Screen Shot 2020-04-15 at 2 45 36 PM" src="https://user-images.githubusercontent.com/39416238/79376776-a7de3b00-7f28-11ea-85c2-f9b7bdb90165.png">

this solves the problem @tealtan pointed out, that the previous layout was throwing off sense of alignment, especially because of the black lines

**Comment by AaronMullan** [comment]
Working out some margin/border issues.

![Screen Shot 2020-04-15 at 4 40 02 PM](https://user-images.githubusercontent.com/50382381/79399284-cb5cb200-7f37-11ea-84f8-1e35a3ad5750.png)

**Comment by julialedur** [comment]
i think if you just apply it to the svg it works!

**Comment by AaronMullan** [comment]
Aha, it does!  Sorry, was on a call, PR coming.
