### ISSUE TITLE
Date and time formatting, "Last updated" language

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#588]
We now have a style guide which outlines requirements for UI, including clear langauge and consistent date formatting. Date format tokens are [Luxon's format](https://moment.github.io/luxon/docs/manual/formatting.html#table-of-tokens). Let us:

- [x] Change the words "Last synced with our spreadsheet:" to "Last updated from our data:"
- [x] Change the format of the last synced to `h:mm a` and lower cased: `6:34 am ET`
- [x] Change date and time stamps in data tables to `ccc LLL d yyyy h:mm a ET`: `Mon Apr 13 2020 03:00 am ET` - this is in the `FormatDate` component.

**Comment by schwartzadev** [comment]
>  Change date and time stamps in data tables to ccc LLL d yyyy h:mm a ET: Mon Apr 13 2020 03:00 am ET - this is in the FormatDate component.

Which dates are you referring to?

I'm seeing:
* The ones in the historical tables
* The `Last updated` values
* The `Last synced with our spreadsheet` values

**Comment by kevee** [comment]
The ones in the historical tables - I think you can just change the default format in `/src/components/common/format`
