### ISSUE TITLE
Usability audit/fixing, page by page

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#59]
We've patchworked up a pretty solid set of items on this site, but after I finish adding some quick documentation this morning, we definitely need to go through and do some usability and feature design stuff. This is the GH home for that.

**Comment by lucasgonze** [comment]
First question: what are the core functions of the home page? What is it intended to accomplish?

An example question: why do we have press links there?

**Comment by lucasgonze** [comment]
Work in progress on a site review:
https://docs.google.com/document/d/1rC63f7sytZgcb89WHJh6sxvWdVQ_bBHUVRC70edoQQM/edit?usp=sharing

This document is to review all the current components of the site. It will list the pages. For each page it will list the sections. For each section it will list the business purpose.

**Comment by kissane** [comment]
Sidenote that we need to be able to re-order the footer nav which is currently semi-alpha and also just eeeeeee nav.

**Comment by kissane** [comment]
@lucasgonze Hey Lucas, ping me when you have work to put eyes on for this? Tx!

**Comment by lucasgonze** [comment]
Good progress on the sitemap, which is a prerequisite to requirements: 

https://docs.google.com/document/d/1rC63f7sytZgcb89WHJh6sxvWdVQ_bBHUVRC70edoQQM/edit#heading=h.fyk2vnfphf6j

**Comment by lucasgonze** [comment]
The site functional review is complete. This is basically a sitemap, formatted as a document rather than a graph. 

The Website Users/Goals review is a closely related document:
https://docs.google.com/document/d/1nMydLa_Ckj9MDyu6ooGRKeZx5OeAbI1q7lzDUKEr6rw/edit

**Comment by lucasgonze** [comment]
The next step is to finish the Website Users/Goals review (https://docs.google.com/document/d/1nMydLa_Ckj9MDyu6ooGRKeZx5OeAbI1q7lzDUKEr6rw/edit). 

Then we can refactor the overall set of pages and the content of each page.

**Comment by lucasgonze** [comment]
Completed. Next step is 
https://docs.google.com/document/d/1NPypuNap-yFaOpzd2SKkXbI9GnkzI5QOsozLACSBuww/edit
