### ISSUE TITLE
Global nav edits

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#590]
Heeeey it's time to do more crimes in the global nav to make homes for new things coming in. Here is what we have for this evening:

1. Rename Get the Data --> **Our Data**
2. Rename About the Data --> **How to Use It**
3. Replace Data API with new item: **Why It Matters**
4. Rename About the Project --> **About Us**
5. Keep as is: **Blog**

@kevee or @schwartzadev, may I leave this in your hands? Once that's done I need to head into Contentful and do more musical chairs in the subnavs.

**Comment by schwartzadev** [comment]
Food for thought: if we're changing `Get the Data` to `Our Data` on the nav, do we want to change it in the big blue homepage button as well?
