### ISSUE TITLE
bubble legend style 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#593]
- let's also change this legend to match our labels: 

<img width="221" alt="Screen Shot 2020-04-15 at 11 17 13 AM" src="https://user-images.githubusercontent.com/39416238/79356349-d0f0d280-7f0c-11ea-9502-dcf8da1527d6.png">

use #828688 for labels and make them 15px 
let's also align them left and if possible add a bit of margin bottom so they're not on top of the dashed line 

<img width="204" alt="Screen Shot 2020-04-15 at 11 32 15 AM" src="https://user-images.githubusercontent.com/39416238/79356466-009fda80-7f0d-11ea-8388-9588e3c844b0.png">
(this is not aligned and doesn't have margin, is just a color and size example)

**Comment by goleary** [comment]
I can take care of this
