### ISSUE TITLE
API stats for sparse data

### ISSUE THREAD

**Issue by gitjeff05** [COVID19Tracking/website#598]
Since [some state level statistics are sparse](https://covidtracking.com/data) (e.g., current hospital/ICU admissions/ventilator), Some insights into the data that is captured and provided through the API would be helpful. Reading issue #555 made me think about this as it is somewhat related.

Using the sparse fields `hospitalizedCurrently` and `hospitalizedCumulative` as an example, the following stats could be used:

#### Out of 56 states/territories reporting:

- **52** (93%) contain a **cumulative** or **current** hospitalization metric
- **49** (88%) contain a **cumulative** or **current** hospitalization metric updated in the last 24 hrs
- **19** (34%) contain both **cumulative** and **current** hospitalization metrics (16 have updated in last 24 hrs)

There are probably better ways to show/describe this. The same should be done for ICU/Ventilator data.

**Comment by schwartzadev** [comment]
I _really_ like this idea, and I would suggest adding this type of info to the [us-totals](https://covidtracking.com/data/us-daily) page.

One concern that comes to mind is the "x hrs ago" format...I don't think our current build system would support that without client JS. Regardless, I think this type of info is important and I'm sure we can figure something out.

**Comment by gitjeff05** [comment]
Thanks for the feedback @schwartzadev. I think we could probably just use the "date" field from our API instead of "updated x hrs ago." This part _could_ live on us-totals, however the relevant stats are no longer included in the US API, only states. I was thinking of putting it on the [Our Data](https://covidtracking.com/data). Maybe under the caveats:

> States are currently reporting two fundamentally unlike statistics...

Also, including a table for reference in case anyone is interested. Blue rows contain both metrics and are current. Orange rows show that at least one metric is out of date.

![Cumulative/Current Hospitalizations Table](https://user-images.githubusercontent.com/548922/79488074-2c8f8e80-7fe7-11ea-9130-b9552c88c8f5.png)
