### ISSUE TITLE
Audit dashboard for semantic HTML

### ISSUE THREAD

**Issue by vijaysharwar** [COVID19Tracking/website#605]
In at least some cases, we are using `<p>` tags instead of `<h*>` tags in the dashboard. Now that the entire page is constructed, we should thoroughly review and set proper heading levels for better SEO and page-wide consistency.

We can also consider:

- Making better use of semantic `<section>` and `<header>` tags for the various page sections
- Using `<aside>` for things like legends and footnotes
- Introducing a page `<header>` within `<main>` to include the intro paragraph
- Possibly add a `<nav>` to the new `<header>` with a table of contents (local anchor links to sections on the page)

**Comment by jrubenoff** [comment]
Looked over the markup this morning and wrote a few thoughts below.

Don't feel super strongly about anything here, so feel free to disagree!

### Headers

Here's a rough proposal for header structure:

- `h2`: Section headers. (Currently `div.tips-section-title`)
- `h3`: Chart names. (These would stay the same.)
- `h4`: Chart labels. (Examples: the `h2` date in the map chart, or the state names in the "Cumulative Tests By State" chart.)

### Footnotes

So I'm assuming we ideally want the footnote associated with the element it describes.

For footnotes that describe text content, like a label, it seems like there's an established pattern we can use: bidirectionally linking between it and the element.

![link-footnotes](https://user-images.githubusercontent.com/1328849/80015069-115ccd00-8486-11ea-9d8a-e2606873b34a.gif)

But that won't work for footnotes which describe an interactive element, like the "tests per capita" UI toggle. In these instances, maybe we could include the footnote's text within the element's title attribute.

### Other suggestions

We might want to:

- Mark up dates with the `<time datetime="*">` element, letting us specify the full, non-abbreviated date.
- Consider a `<figure>` / `<figcaption>` pattern for the charts not tied to a specific piece of content, like the "Daily New Tests" chart.

**Comment by vijaysharwar** [comment]
@jrubenoff I have also been thinking about how to improve the footnotes! Your proposal sounds good, and is probably worth a dedicated GitHub issue. It'll help with both SEO and a11y. But one tricky party is we're footnoting within the tooltips, which aren't currently clickable (they move with the mouse/hover state, at least in the area charts).
