### ISSUE TITLE
"Want to get involved? Help us get better data" link on homepage is a 404

### ISSUE THREAD

**Issue by scottmcdaniel** [COVID19Tracking/website#606]
Hello. On the homepage, the text in the subject line is supposed to link to https://covidtracking.com/help, but it leads to a 404.

I think it needs to link to https://covidtracking.com/about-project/help (which was probably supposed to be /help).

![screenshot_656](https://user-images.githubusercontent.com/1933230/79493131-066dec80-7fef-11ea-942c-b5dd8fa89fca.png)

**Comment by kevee** [comment]
Thanks for pointing that out, @scottmcdaniel, we're on it!
