### ISSUE TITLE
line-height of notes/byline section 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#609]
there's a lot of space in the notes/byline section of the page. 
i suggest changing to something like this: 

<img width="1119" alt="Screen Shot 2020-04-16 at 3 23 52 PM" src="https://user-images.githubusercontent.com/39416238/79497866-6a47e380-7ff6-11ea-9dce-56a03da665bb.png">

i did:
- margin-bottom: 0; for all the text of that section
- added a margin-top: 50x; to "Notes" so there's a bit more separation between sections 
- margin-top: 40px; to "graphics and development..." 

(adjust values for mobile!)

**Comment by nselikoff** [comment]
@julialedur PR is ready and includes screen shots for desktop and mobile
