### ISSUE TITLE
Some anomalies in state daily API data

### ISSUE THREAD

**Issue by loglow** [COVID19Tracking/website#61]
There are some anomalies in the data from:
https://covidtracking.com/api/states/daily

Might be an API problem, since some vars aren't showing up at all:
- MA 3/10 is missing all values except 'positive'
- PA 3/10 is missing all values except 'positive'
- VA 3/10 is missing all values except 'positive' and 'negative'

Might be a data problem, since nulls are being reported amid very few other nulls:
- AL 3/7 is reporting 'null' for positive (should be 0)
- CT 3/7 is reporting 'null' for positive (should be 0 or 1)
- ND 3/11 is reporting 'null' for positive (should be 0 or 1)
- WV 3/11 is reporting 'null' for positive (should be 0)

Finally, the 'total' testing value for MD 3/12 is just bizarre and most likely incorrect. The sequence surrounding that value (12) looks like: ... 78, 95, 103, 12, 111, 120, 125 ... See what I mean?

I've been told that since 'pending' is reported as part of 'total' that means that the cumulative state test totals will sometimes decline (jump down) over time, which is the case for a handful of states, but MD 3/12 is the only situation (to my eyes) that looks more like an error.

**Comment by hammer** [comment]
Those 3/10 missing totals definitely seem like a bug, as does MD on 3/12. Thanks for catching them!

Those nulls for positives are likely due to my choice to not put 0 when the state was not reporting anything. Many states were slow to put out any data at all, and I wanted to distinguish that case from an explicit 0.

**Comment by loglow** [comment]
The reason I highlighted those nulls is because they're the **only** 4 'positive' nulls in the entire (!) dataset, and they're also all surrounded by either 0s or 1s on either side.

**Comment by hammer** [comment]
Okay fair enough we should definitely pull forward the previous day’s value in each of those cases then.

**Comment by careeningspace** [comment]
Here is the original Total data missing for PA, VA, MA:
![Screen Shot 2020-03-18 at 11 58 47 PM](https://user-images.githubusercontent.com/43073915/77030403-d2ae9100-6974-11ea-8a06-a68362c7373b.png)

Here it is fixedfor PA, VA, MA:
![Screen Shot 2020-03-18 at 11 59 34 PM](https://user-images.githubusercontent.com/43073915/77030380-c75b6580-6974-11ea-86c2-6b4f193706d8.png)

For the other data points that just have nulls:
![Screen Shot 2020-03-19 at 12 03 27 AM](https://user-images.githubusercontent.com/43073915/77030639-a5aeae00-6975-11ea-8926-064bb88d3dc3.png)
![Screen Shot 2020-03-19 at 12 03 59 AM](https://user-images.githubusercontent.com/43073915/77030640-a5aeae00-6975-11ea-842e-1ef2856a3331.png)
![Screen Shot 2020-03-19 at 12 04 37 AM](https://user-images.githubusercontent.com/43073915/77030641-a6474480-6975-11ea-8c2c-650d93018a93.png)
![Screen Shot 2020-03-19 at 12 05 05 AM](https://user-images.githubusercontent.com/43073915/77030643-a6474480-6975-11ea-900f-a15adf719948.png)
