### ISSUE TITLE
N. Mariana Islands in sm multiples 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#620]
let's change Northern Mariana Islands to "N. Mariana Islands" in the sm multiples, so it doesn't break into two lines

also, let's use state abbreviations (NY, CA, etc) on sm screens to solve that problem. 

<img width="475" alt="Screen Shot 2020-04-16 at 6 01 15 PM" src="https://user-images.githubusercontent.com/39416238/79511852-1648f900-800e-11ea-840d-f99f36757a0d.png">

**Comment by vijaysharwar** [comment]
Working on this now.
