### ISSUE TITLE
use same x-axis for all sm multiples

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#622]
we need to use the same date range on the x-axis on the small multiple charts. 

@vijaysharwar: "We’ll need to calculate a shared extent across all states in _StateCumulativeTestsContainer.js and pass it to all AreaCharts ."

**Comment by vijaysharwar** [comment]
I can work on this.

**Comment by AaronMullan** [comment]
Well I have a simple solution for it, but usually Vijay has a more elegant one!  PR $#623

**Comment by vijaysharwar** [comment]
I don't know if it's "elegant", but https://github.com/COVID19Tracking/website/pull/625 fixes this by passing a shared `extent` to all small multiple `AreaCharts`. We derive the value by checking all dates for all states. The benefit here is if some states dates don't match towards the most recent end of the scale, the charts will still have equivalent x-axes.
