### ISSUE TITLE
site design iteration 3/19 

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#63]
Hiya let's knock out some fixes. I got this from Júlia Ledur:

Website suggestions: 

- [x] Don’t think the headers should be underline as they are already bold and colored (“Home”, “US Daily” and “States”). I would probably keep them black too.
- [x] ~The COVID Tracking Project in the nav bar should be bigger. Right now the hierarchy is a bit odd. Also the COVID Tracking Project logo should be somewhere in the nav bar at the top~ Agreed but moved to next week's design refresh. 
- [x] Putting “Best Practices for Data Release” before the press section makes more sense to me? 
- [x] ~I feel like we’re missing a “download data” button at the top of the “most recent data” page. That would then take the reader to the “Initial basic API & csv downloads” page~ added text links for now, moving button to the NEXT list 
- [x] ~We should standardize the abbreviation for United States to U.S. (AP style) across the website and graphics. Right now, we have both "US" and "U.S." in the first sentence of the homepage~  other way around sorry, we're stuck with it for now

**Comment by kissane** [comment]
@beep Once we have color-change hex codes is that a thing I can give to you? Likewise maybe the uhhh visual hierarchy stuff? This is def interim sketchy stuff, lmk if that gets in the way of larger design passes or anything

**Comment by kissane** [comment]
Got hexes

button: #4A5F85
button hover: #3D4F70
links and headers: #607A9C
hover links: #4A5F85
hover headers: #7391B0

**Comment by beep** [comment]
i’m gonna use them hexes

(thank you, erin and júlia! more soon.)

**Comment by beep** [comment]
(Oh and this definitely doesn’t get in the way of the larger design pass! These are easy, easy fixes, and we should make ’em.)

**Comment by kissane** [comment]
We are going to standardize on "US" rather than "U.S." because that's how it is in the Spreadsheet tab names, which we are never changing until it's safe to got outdoors.

**Comment by beep** [comment]
On reread, one thought on this item:

> Also the COVID Tracking Project logo should be somewhere in the nav bar at the top

I _completely_ agree, but I’d suggest we punt on this until next week. I’d like us to get a proper lockup in place, and it’ll be easier to do that as part of the larger pass.

**Comment by kissane** [comment]
Dropping this doc in progress here, it's guiding our micro-decisions for now https://docs.google.com/document/d/1nMydLa_Ckj9MDyu6ooGRKeZx5OeAbI1q7lzDUKEr6rw/edit?usp=sharing

**Comment by kissane** [comment]
> I feel like we’re missing a “download data” button at the top of the “most recent data” page. That would then take the reader to the “Initial basic API & csv downloads” page

This is a good idea but that button should probably go to the same place sa it does on the homepage, which is currently the spreadsheet. Maybe this is just a couple of text links at the top, one going to each place?

**Comment by kissane** [comment]
This is SO MUCH PRETTIER thank you! 

@beep I am so sorry but could I please request help getting the top nav links to be MOST RECENT DATA instead of STATES and US HISTORICAL DATA instead of US DAILY?

If you don't have time for that, I can get to it when I return in three-ish hours, not at all an emergency.

**Comment by beep** [comment]
@kissane ON IT

**Comment by beep** [comment]
@kissane I DID IT #65 FYioh you merged it already thank you

**Comment by kissane** [comment]
HEY THERE we did all the things here or officially moved them to the Large Design Thoughts currently earmarked for next week, I'm so happy, ty ty ty.
