### ISSUE TITLE
feat: Analytics

### ISSUE THREAD

**Issue by jefflembeck** [COVID19Tracking/website#632]
Right now we're using Netlify's analytics. It seems solid for tracking pages visited and total visitors, without tracking users or private information.

If we want something more comprehensive (goal tracking, for example), we'll need to switch to something else.

Requirements

- [ ] No user data kept
- [ ] No server code required (static site, so...)
- [ ] Ability to do campaign/goals
- [ ] Some basic client information, especially user agent and language

**Comment by schwartzadev** [comment]
Both from an accessibility standpoint and from a UX standpoint, I would _love_ to avoid client-side JS. With that being said, if we do opt for a client-side JS solution, I would ask to avoid "session replay" types of analytics. (FullStory, Hotjar, etc.)

I'm not super sure if this is relevant here, but Netlify supports "split tests" (A/B testing) natively, if that's something we want to explore.

**Comment by kevee** [comment]
I am there with @schwartzadev about avoiding too heavy a client-side solution, but if a JS-based analytics tool doesn't load, I think that's fine.

We will definitely keep Netlify analytics, which captures all users regardless of the client's state.

**Comment by annesodev** [comment]
Is Matomoto an option you already considered? The tool can be handled for free with their "on premises" offer and their leitmotiv is data protection and customer's privacy. It might fit the project : https://matomo.org/ + @superbiche can ask an hosting provider for a pro-bono server to host it for the project (or on Netlify).

**Comment by kevee** [comment]
@superbiche or @annesodev can you cost out what a Matomo account with (outside ballpark) 20m requests a month would look like?

**Comment by annesodev** [comment]
@kevee : you mean 20 millions? If so, the cheapest offer (cloud hosted) with 6 months data retention and 3 team members, it would cost 289 € per month...

**Comment by kevee** [comment]
Thanks! We're engaging with an analytics vendor right now and since this is more of an inside-baseball discussion I'm going to close this issue for now and we can pick up the convo in slack.
