### ISSUE TITLE
Reinstate map tooltips on smaller screens

### ISSUE THREAD

**Issue by vijaysharwar** [COVID19Tracking/website#635]
For V1 launch, map tooltips are to be disabled on smaller screens via https://github.com/COVID19Tracking/website/issues/634 .

This Issue is about restoring the functionality, which likely requires some thought/redesign.

Possible strategies:
- Decreasing size of tooltips
- Decreasing amount of information inside tooltips
- Put tooltips content in a single container above or below the map

**Comment by julialedur** [comment]
perhaps we can do just total numbers for the bubble map and per capita numbers for the choropleth?
