### ISSUE TITLE
Featured on the front page of The Boston Globe

### ISSUE THREAD

**Issue by jakejarvis** [COVID19Tracking/website#651]
Hi everyone!

The site was just featured as the main source in today's front-page article of The Boston Globe:

https://www.bostonglobe.com/2020/04/18/nation/amid-flurry-national-coronavirus-data-massachusetts-remains-hot-spot-infection/

...so well done! You're cited near the top of the article as well as in their main infographic. I've added the Globe to `homepage-press.yml` and its vector logo in #652. Let me know if I should add `featured: true` as well? I think it's a pretty big deal! 👍 

I'm also not sure where the articles on the In the Press page are pulled from, I'm guessing a spreadsheet that you all have access to? If I'm missing it then just let me know. :)

<img width="1143" alt="Screen Shot 2020-04-19 at 10 18 58 AM" src="https://user-images.githubusercontent.com/1703673/79690280-a2823880-8227-11ea-9a9c-b3d58ca45b4a.png">

**Comment by kevee** [comment]
Assigning to @julialedur for review.

**Comment by kissane** [comment]
I got this, thank you!
