### ISSUE TITLE
PR conflict help requested

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#67]
Hello! This great PR from @jeremiak slid by me and I only just saw it. @beep has since made a bunch of great CSS changes and we've changed the homepage text. Could one of you wonderful humans merge master in and update the PR to fix conflicts before we merge the PR? 

THANKS, SORRY, SO MANY THINGS.

**Comment by olivierlacan** [comment]
Fixed via https://github.com/COVID19Tracking/website/pull/56/commits/f5eff1038f0b5fd8affaf890a4bac97053d76372
