### ISSUE TITLE
Y Axis on Graphs - MISLEADING - Scale Incorrect

### ISSUE THREAD

**Issue by mseifert2** [COVID19Tracking/website#677]
Let us know what the design issue is. Screenshots are helpful!
Y axis on the graphs being shown in the newspapers are INCORRECT.  The scale for "Hospitalizations and deaths comparison" on 4/19/20 show a scale of 0 to 100 and then to 1000.  If the increments are 100 then they all must be 100 (i.e. 0 to 100 to 200 to 300, etc.).  The arc you are showing is about a 30 degree angle when it really should be about 80 degrees (almost vertical).  Saw multiple charts from your organization with the same problem.  YOU ARE BEING VERY MISLEADING ABOUT THE SEVERITY OF THE CRISIS.  Please correct all of these graphs ASAP.

**Comment by jeremiak** [comment]
Hey @mseifert2 thanks for the feedback. We actually aren't a newspaper or a publisher, we just make sure to provide timely, high quality time series data for this crisis. If you have an issue with a particular publisher's charts I recommend writing a letter to their editor. I'm closing this since its not actionable on our part. Have a good one.

**Comment by mseifert2** [comment]
To clarify, they reference you as the source:
Tampa Bay Times:  "Source:  The COVID Tracking Project"


    On Wednesday, April 22, 2020, 10:53:46 AM EDT, Jeremia Kimelman <notifications@github.com> wrote:  
 
 


Hey @mseifert2 thanks for the feedback. We actually aren't a newspaper or a publisher, we just make sure to provide timely, high quality time series data for this crisis. If you have an issue with a particular publisher's charts I recommend writing a letter to their editor. I'm closing this since its not actionable on our part. Have a good one.

**Comment by jeremiak** [comment]
Ah, got it. In this case @mseifert2 we're just the data source. The Tampa Bay Times went ahead and created the chart themselves so I'd recommend getting in touch with their data editor/graphics desk :)
