### ISSUE TITLE
US Daily 4pm Spreadsheet - In ICU & On Ventilator

### ISSUE THREAD

**Issue by jburns513** [COVID19Tracking/website#687]
Let us know what the design issue is. Screenshots are helpful!
For the US Daily 4pm ET Spreadsheet:  
In ICU and On Ventilator
Are the columns: Cumulative and Currently switched maybe?

Thank you for this valuable service.

**Comment by schwartzadev** [comment]
Thanks for the issue! Please see our [data page](https://covidtracking.com/data/) for information about this question:

> States are currently reporting two fundamentally unlike statistics: current hospital/ICU admissions and cumulative hospitalizations/ICU admissions. Across the country, this reporting is also sparse. In short: it is impossible to assemble anything resembling the real statistics for hospitalizations, ICU admissions, or ventilator usage across the United States. As a result, we will no longer provide national-level summary hospitalizations, ICU admissions, or ventilator usage statistics on our site.

> We will continue tracking these numbers on a state-by-state basis, but it does not feel responsible to continue to display these US-wide statistics for a general audience. These heavily caveated numbers will remain in the API for advanced data users.
