### ISSUE TITLE
margin after press logos 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#688]
this section of the website feels a bit crowded. 
i suggest we add a breathing space between the press logos and the list of stories. 

<img width="1313" alt="Screen Shot 2020-04-22 at 4 45 22 PM" src="https://user-images.githubusercontent.com/39416238/80039546-09248200-84c6-11ea-816e-aa4beebaba71.png">

**Comment by karinanguyen** [comment]
Working on it!

**Comment by karinanguyen** [comment]
Just made the PR
