### ISSUE TITLE
Ignore auto-generated times in Jest tests

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#691]
**Describe the bug**

[Here's an example](https://circleci.com/gh/COVID19Tracking/website/440?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link)

```
    -       Last updated: Thu Apr 16 2020 10:00 pm ET
    +       Last updated: Fri Apr 17 2020 12:00 am ET
[...]
 › 1 snapshot failed.
```

Jest tests seem to fail because of auto-generated times. Is there a way to ignore these?

**Comment by kevee** [comment]
Fixed in https://github.com/COVID19Tracking/website/pull/690/commits/0525c94c80ef1217cdbbb7af6d7a1f7681181491

The issue was the test had a timezone offset. I made it GMT and made zone explicit in `formatDateToString`
