### ISSUE TITLE
feat: Search

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#693]
We need to add a search feature to the website. I [started a branch on this](https://github.com/COVID19Tracking/website/tree/kevee/algolia-search), but never finished. Please start a new branch called `feature/search` so we can do PRs against it.

Some big things to consider: Algolia breaks different types of documents into different "indices" - I made one for states, blog posts, and pages, and prefaced them with `test_`. Eventually we can create a separate `live_` version of these indices.

In the branch, I added a plugin for Algolia, and Gatsby updates the search index *on every build* so we get the most updated data in the indexes. So it basically updates all states, pages, and blog posts for every deploy. You can [see how I setup configuration here](https://github.com/COVID19Tracking/website/blob/kevee/algolia-search/src/utilities/algolia.js). It's a bit rough, and I feel like dumping entire page and blog post bodies into Algolia is the wrong way to go - maybe there's a way to just put in like keywords? Unsure.

The index name prefixes (i.e. `test_` should be determined by an environment variable so we can different ones for different environments.

The public search API key (read only) [should be available to the search interfaces](https://www.gatsbyjs.org/docs/environment-variables/#client-side-javascript) by using a `GATSBY_` prefixed environment variable.

What we need is a search interface that allows:

- [x] Ordering by index type, i.e. show states first, then blog posts, then pages - if I type "California" I probably want to jump to California's page
- [x] A search results page at `/search` that supports queries - i.e. `/search?q=stuff`
- [x] A search box that goes on the header. Do *not* worry about design right now, but just make sure it works.
- [x] A search automcomplete - we already use [Reach's combobox](https://reacttraining.com/reach-ui/combobox) component on the site for the state dropdown, and I like it because of all all the accessibility features in it, but I am not wedded to that component

EDIT: Adding the few last items discussed on Slack, please add if I'm missing something: 
- [x] Add last update date for States in index + results  
- [x] Add last update date for Pages in index + results  
- [x] Add States `notes` to index

**Comment by superbiche** [comment]
@kevee should we keep the todo here or on the PR? For now I'm updating the PR one

**Comment by muamichali** [comment]
**Idea**: We could index our tweets as well and display them on the site as search results. A lot of our content so far is in tweets. CC @kissane for your thoughts

**Comment by superbiche** [comment]
@muamichali if you have an API key for the Twitter account I'd be happy to give it a try so we can have something to iterate on
