### ISSUE TITLE
Proposal: add client error reporting

### ISSUE THREAD

**Issue by superbiche** [COVID19Tracking/website#698]
Talked to @kevee about having some client-side error reporting like Sentry, Bugsnag or whatever works (and would donate an account for the project). 
This issue is primarily to start a discussion if need be, and also find out if some of you feel like trying to get one of these companies to donate an account (I'd be surprised if Sentry refused).

Also I'd love to help setting it up but I'm already focusing on the new Search so anyone more available and happy to do it is welcome!

**Comment by kevee** [comment]
I'm reaching out to a few companies to see if they'll donate a probono account.

**Comment by superbiche** [comment]
@kevee if you don't have any answer, would a on-premises Sentry be OK for now?
You can [ask DigitalOcean for free credits] (https://www.digitalocean.com/community/pages/covid-19) . [OVH also started a similar initiative](https://open-solidarity.com/)

Otherwise my company could give away one of our servers for this use (and other stuff that we can't get an account for)
