### ISSUE TITLE
See if we can get covid19tracking.com

### ISSUE THREAD

**Issue by hammer** [COVID19Tracking/website#7]
Our Twitter and GitHub handles are @COVID19Tracking so it would be nice to own covid19tracking.com.

WHOIS shows JericoDeAngelo@Gmail.com as the owner, who appears to be this guy https://www.linkedin.com/in/deangelo-jerico-0a733479.

Anyone want to reach out to him?

**Comment by kissane** [comment]
Just sent an email to him.

**Comment by kissane** [comment]
The guy who has it is a domain scalper who is offering it to us at the low low price of $2,300. I did not respond.
