### ISSUE TITLE
feat: some kind of "Past Contributors" section on Volunteer credits

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/website#704]
Love the new auto-populated Contributors on https://covidtracking.com/about-project! But I know that Dustin Preisler is no longer involved with the project, so he should be removed from the Team Leads section. (first task)

However, he did some crucial work early on, as did people like Lucas Gonze who is also no longer involved. Could we have some kind of "Past Contributors" section? (second task, main request) Probably would need to be manually updated. The model I had in mind is http://www.rossettiarchive.org/about/credits.html

**Comment by kevee** [comment]
We can add a Contentful snippet for that and put them below the contributors. I'll open a PR to fix that.

**Comment by kevee** [comment]
I removed dustin from Contentful.

**Comment by kissane** [comment]
Moving contributors into a "past" section may eventually get pretty unwieldy—I'm not against the section, but flagging the effort.
