### ISSUE TITLE
Responsive Navbar Seems weird and crowded.

### ISSUE THREAD

**Issue by ishandeveloper** [COVID19Tracking/website#712]
The mobile navbar seems so crowded and basic. It just doesn't match with the whole layout of the site.

I suggest we either add some space between the navbar items or create a vertical hamburger menu instead.

#### Screenshots
<img src="https://user-images.githubusercontent.com/54989142/80286262-f4572100-8747-11ea-8639-23883d91fd1b.png" width="45%">&nbsp;&nbsp;<img src="https://user-images.githubusercontent.com/54989142/80286243-d5588f00-8747-11ea-8c2e-35876e231bbe.png" width="45%">

**Comment by schwartzadev** [comment]
Great call, @ishandeveloper! Thanks for pointing this out.

I _think_ that older versions of the site handled this better...it looks like the nav was broken somewhere along the line.

For whoever ends up taking this on -- try checking out older versions of the site (maybe from a week or two ago) to see if the nav was in a better spot then. I bet this is a simple flex fix.

**Comment by superbiche** [comment]
Went back to this commit
```
commit 667cec2084460a745192ef8afface00646c59370
Author: Andrew Schwartz <andrew@aschwartz.me>
Date:   Mon Apr 20 12:51:06 2020 -0600

    fix(sheets): rm unnecessary if
```

And it does look better: 
![image](https://user-images.githubusercontent.com/2478146/80326416-fe0c8180-8838-11ea-91d9-2491add735c2.png)

Working on it

**Comment by superbiche** [comment]
Huh, checked out fresh `master` and here's what I get : 
![image](https://user-images.githubusercontent.com/2478146/80326547-73785200-8839-11ea-9dc1-5eca19750c12.png)

Seems OK to me. @schwartzadev can we close this one? Seems someone fixed it between two PRs

**Comment by schwartzadev** [comment]
Huh, this seems to be working OK for me as well. @ishandeveloper could you share a little more about the devices and browsers you were using? It seems like this might be an issue particular to only some configurations.

@superbiche let's hold off until we can replicate (or maybe not replicate) this issue

**Comment by ishandeveloper** [comment]
Hey @schwartzadev ! 
I'm currently using Google Chrome version :  81.0.4044.122
And the issue was being faced on devices having width between 388px and 1080px.

<details>
<summary>Screenshot [Mobile Devices]</summary>
<img src="https://user-images.githubusercontent.com/54989142/80342515-f1604b80-8881-11ea-8062-d5811927da0d.png" height="500em">
</details>
<details>
<summary>Screenshot [Tablets]</summary>
<img src="https://user-images.githubusercontent.com/54989142/80342786-63389500-8882-11ea-9010-3f6f74169eef.png" >
</details>

**Comment by kevee** [comment]
I don't see it in actual mobile, but do see in various desktop windows that are in our sm-md viewport range. Did a PR.

**Comment by kevee** [comment]
@ishandeveloper - want to [see if this preview site still has the issue](https://deploy-preview-727--upbeat-lovelace-3e9fff.netlify.app/)?
