### ISSUE TITLE
Broken footer alignment

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#715]
Let us know what the design issue is. Screenshots are helpful!
![image](https://user-images.githubusercontent.com/18607205/80315282-b394f180-87b3-11ea-91f5-b30e04963845.png)

The `Contact, etc.` section should be right-aligned on large viewports.

![image](https://user-images.githubusercontent.com/18607205/80315302-d45d4700-87b3-11ea-93d3-ad0ba718cb59.png)
On small viewports, this should also be cleaned up -- I would suggest a single column layout but I defer to @beep

**Comment by beep** [comment]
Thanks, @schwartzadev! Just opened up #718, which should sort this out.
