### ISSUE TITLE
Add timezone to screenshot times

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#716]
Please let us know the page you are talking about, and your content suggestions!
![image](https://user-images.githubusercontent.com/18607205/80315319-fb1b7d80-87b3-11ea-869b-6633b7a08f9b.png)

See the title -- I would suggest adding a note to the historical tables like: `All screenshot times are in ET` instead of repeating the timezone all over the table. (Right now, we do neither of these.)

I do not know if the screenshots times are in ET or not -- the above is just an example.

**Comment by kissane** [comment]
Fully agree with adding timezone (ET) and note, thank you @schwartzadev !

**Comment by kevee** [comment]
They are in ET. How about just change the heading from Screenshot to **Screenshot (ET)** and then add a note in the footer of the table?

**Comment by schwartzadev** [comment]
#728 will close this
