### ISSUE TITLE
Progress indicator

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#717]
When transitioning from one page to another, especially the heavier visualization page, there can be a bit of a lag. Let's add a progress indicator to let the user know something is happening.

I think the [Gatsby nprogress indicator](https://www.gatsbyjs.org/packages/gatsby-plugin-nprogress/) will probably work.

Choose a color for the progress bar that pops. [Honey](https://covid19tracking.github.io/website-docs/?path=/story/colors--colors-honey), maybe?

**Comment by IVIosi** [comment]
Hi @kevee !
Such a great idea to inform more and more people in these days.
I'd like to work on it. Like you mentioned, I think Gatsby nProgress plugin will be the answer.

**Comment by kevee** [comment]
Fixed in https://github.com/COVID19Tracking/website/commit/4aed7cb4c116d739b782b6b1016e05ed84585aee
