### ISSUE TITLE
Tables: Improve typography and general styling

### ISSUE THREAD

**Issue by toddparker** [COVID19Tracking/website#721]
This is part of the larger table work in #457

For this first pass, let's create a branch and focus on taking a pass at improving the table styles for improved clarity. We should also look at our underlying table semantics to make sure these are as accessible as possible.

**Note**: In this first pass, we're not yet adding in responsive enhancements other than the simple overflow we have now. We will make issues for those features.

## Designs

Details for the design are in the **[Figma file](https://www.figma.com/file/fKUKsYMNw3NLSyIEOI1HKc/v2-refresh?node-id=95%3A2627)** but here are some highlights:

### Core table styles
- [ ] **Table headers** (`th`) are 13px heavy and should match the horizontal alignment of their corresponding cells (right if numeric, left if text)
- [ ] **Grouped column headers** are 17px heavy
- [ ] **Cells** are 16px regular weight and should be aligned right if they contain numbers, left if just regular text like the state name or date
- [ ] **Rows** should have a delimiter to help aid in horizontal scanning across wide tables. We're unsure of which approach we want to use so can we create _classes_ to switch between bottom row lines `1px solid rgba(0,0,0,.1)` or alternating (zebra) row fills `rgba(0,0,0,.03)`
- [ ] **Grouped columns** should have a left border on each TH and TD to chunk the columns for easier scanning. These should be darker than the row lines - `1px solid rgba(0,0,0,.2)`
- [ ] A **row hover** to add a bg color to the rows when you `:hover` or `:focus`. With the line dividers, the hover could be the zebra bg color. For zebra, it gets more complicated but maybe we can just increase the opacity of the RGBA fills %?

(Ignore sorting for now)

![image](https://user-images.githubusercontent.com/359929/80394364-be1cbd00-887f-11ea-8031-1813041e3a81.png)

**Comment by dasulit** [comment]
👋 I got a start on this in https://github.com/COVID19Tracking/website/pull/720. I haven't yet put together a zebra version, but figured I'd get some eyes on what's there so far. Let me know what you think!

**State page:**

<img width="1177" alt="Screen Shot 2020-04-28 at 12 41 47 AM" src="https://user-images.githubusercontent.com/8495845/80448060-20f66e80-88e9-11ea-9188-fa3fb02ab14a.png">

---

**US Daily:**

<img width="1173" alt="Screen Shot 2020-04-28 at 12 42 08 AM" src="https://user-images.githubusercontent.com/8495845/80448059-205dd800-88e9-11ea-8d23-c3da766629e1.png">

**Comment by toddparker** [comment]
@dasulit these look amazing, so much cleaner looking. Thank you! 

- [ ] **Reduce the spacing between the grouping header and column headers.** Design:

![image](https://user-images.githubusercontent.com/359929/80503219-90974880-893f-11ea-8790-45e8d2149dd0.png)

- [ ] **Add a bit of bottom margin on tables to avoid notes from being so close**:

Code:
![image](https://user-images.githubusercontent.com/359929/80503359-bde3f680-893f-11ea-93ae-ff8048ca3741.png)


- [ ] **In the mockups, we had switched to heavy weight for the groupings and headers.** Do we load that weight now?

- [ ] **Refine the row highlight hover color** - Maybe @Jason Santa Maria can help out there

**Comment by toddparker** [comment]
@dasulit If you have time, we might want to tidy up the grouped summary table headings so they are more parallel:

- [ ] Add a grouping call Outcomes over the death and recovered columns
- [ ] Move Total Test Results up as a header group
- [ ] Remove the parens around (Positive + Negative)

Mockup:
![image](https://user-images.githubusercontent.com/359929/80514439-803a9a00-894e-11ea-9d89-6dadee1b7b3a.png)

**Comment by dasulit** [comment]
Thanks for looking @toddparker! I just pushed a commit that addresses your recommendations above, with the exception of row highlight color; I can wait for other folks to weigh in there.

One minor decision I made I wanted to highlight: in order to left-align grouping headers and column headers, I opted to left-align the leftmost column header, while keeping the data in the column itself right-align. Here's an example (observe the alignment of `Tests` and `Positive`):

| Before | After |
|--|--|
| <img width="265" alt="Screen Shot 2020-04-28 at 10 51 08 PM" src="https://user-images.githubusercontent.com/8495845/80557344-95421800-89a4-11ea-9407-1555ac35589d.png"> | <img width="258" alt="Screen Shot 2020-04-28 at 10 50 59 PM" src="https://user-images.githubusercontent.com/8495845/80557358-a1c67080-89a4-11ea-9935-844fc67ca64c.png"> |

**Comment by toddparker** [comment]
Hi @dasulit - this looks great, **thank you**. Funny, I was debating what to do about the mis-alignment of the header and first cell and I agree that cheating it that way just feels better.

I'm working with @jasonsantamaria on the row hover color fine tuning but it seems that for now, we can drop in `#E2F1FC` since that's in our color palette.

![image](https://user-images.githubusercontent.com/359929/80602913-b97e1300-89fd-11ea-9072-e14d0e109a5e.png)

**Comment by beep** [comment]
This is looking really great, folks! One small request/suggestion: would it be possible to avoid [using pixels for font-sizes](https://github.com/COVID19Tracking/website/pull/720/files#diff-57e273918c642429a4079b5bf0215bbbR23), if possible? We’ve been trying to use rems—with an optional pixel fallback, if you’d prefer!—for accessibility reasons.

**Comment by toddparker** [comment]
Good call @beep, I didn't look to closely at the code yet, we'll fix that up.

@dasulit here's a recap of the final tweaks:

- [ ] Do some QA across all the tables and a few browsers (I did this but would like a second set of eyes)
- [ ] Check the horizontal padding between the th and td...these look slightly mis-aligned (see above)
- [ ] Convert font size and padding values to `rem`
- [ ] Swap in `E2F1FC` for the row hover color
- [ ] Look into ideas to keep this last column from wrapping quite so much. For now, an inline min-width in rems to at least keep things to 2 lines would help or we could add a `nowrap` to the P+N header?

![image](https://user-images.githubusercontent.com/359929/80647815-13ea9400-8a3d-11ea-9742-0eb41f08701e.png)

**Comment by dasulit** [comment]
Thanks for the eyes @toddparker @beep! I just pushed the following changes:

- [x] Use `rem` for fonts and padding
- [x] Fix padding discrepancy between `th` and `td`
- [x] Add minimum width to grouping headers
- [x] Use `E2F1FC` for hover color

Did some quick QA across Safari and Firefox as well, didn't spot anything out of sorts. I have [a PR up](https://github.com/COVID19Tracking/website/pull/720), just marked ready for review. 🙇‍♀️

**Comment by toddparker** [comment]
Thanks @dasulit. I checked the PR and it seems that the preview URL hasn't updated. Maybe that's related to these errors?

![image](https://user-images.githubusercontent.com/359929/80716505-b8b0b400-8ac5-11ea-903d-7d9311ade40e.png)
