### ISSUE TITLE
Proposal: volunteer onboarding guide

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#750]
We have so many resources like our style guide, getting setup on the local dev machine, etc that new developers need access to. Some ideas of things that need to be covered below.

Should this just be a Google Doc? A wiki on this repo?

- Code of conduct
- Style guide
- Storybook & documentation site
- How to setup a local environment
- Automated testing
- Our deploy previews, branch previews, and how the site gets live
- External services like Contentful and Algolia

**Comment by schwartzadev** [comment]
Yes! I would support a wiki here to keep things organized. A lot of this content is already on the repo, too:
* [Code of conduct](https://github.com/COVID19Tracking/code-of-conduct/blob/master/CODE_OF_CONDUCT.md)
* [Style guide, other misc.](https://github.com/COVID19Tracking/website/blob/master/CONTRIBUTING.md)
* [Installation, testing from the README](https://github.com/COVID19Tracking/website/blob/master/README.md)

I can start consolidating info once we have a game-plan 👍
