### ISSUE TITLE
blog headshots are stretched on Safari

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#759]
Let us know what the design issue is. Screenshots are helpful!

See title -- this is a Safari-specific bug that I thought was fixed in #737 (see @kevee's review)

![image](https://user-images.githubusercontent.com/18607205/80837699-921d7680-8bb4-11ea-8fda-e4ea20972069.png)

**Comment by AaronMullan** [comment]
PR coming in a second.

**Comment by AaronMullan** [comment]
![Screen Shot 2020-05-01 at 2 35 41 PM](https://user-images.githubusercontent.com/50382381/80844058-a4021800-8bba-11ea-92c1-b6cf0d4942a5.png)

**Comment by kevee** [comment]
Fixed in #763
