### ISSUE TITLE
Link to crawl history on state pages

### ISSUE THREAD

**Issue by hammer** [COVID19Tracking/website#76]
I believe @julia326 or @joshuaellinger are the keepers of this data on S3. It would be amazing if we could link to it on the state page, or even have a carousel display of it!

**Comment by joshuaellinger** [comment]
Julia -- can you post the S3 link for them to integrate?

**Comment by kevee** [comment]
How about having the most recent snapshot, along with links to data sources, etc to the side next to the state notes? That would help bring up the data, and separate more metadata about the state from the actual data. Then we can have a separate `/data/state/[state-name]/history` page with more detailed info and a screenshot per crawl.

![IMG-3372](https://user-images.githubusercontent.com/270536/77177077-5367ad00-6a9b-11ea-9f2e-daf6f0b9bf9b.jpg)

**Comment by hammer** [comment]
http://covid-data-archive.s3-website.us-east-2.amazonaws.com/state_screenshots

**Comment by julia326** [comment]
Afaik @webmasterkai is already pointing to that bucket in his API to also serve screenshots from covidtracking.com like https://covidtracking.com/screenshots/AK/AK-20200320-010029.png - Kai do you have logic in there that would easily integrate?

**Comment by kevee** [comment]
The `/screenshots/` is actually just a [netlify redirect](https://github.com/COVID19Tracking/website/blob/master/_redirects#L6) to the S3 bucket.

**Comment by webmasterkai** [comment]
There's an API that lists screenshots by state https://covidtracking.com/api/screenshots
I haven't parsed out the date yet. I can do that.

**Comment by kevee** [comment]
I've got a branch I'm working on and will have a PR soon - we will need to do some sort of cropping.

**Comment by julia326** [comment]
@kevee the screenshots aren't perfect (how often they break is prob similar to what urlwatch is seeing), and I've been fixing them as I find out they're broken - in case this affects the decision to feature them on the state site right now. Also if you have ideas for cropping logic, I can potentially put those in the backup script - I did the simplest thing for screenshots initially.

**Comment by julia326** [comment]
The screenshot timestamp is in the filenames (date, time in EST) and the sources come from the States tab COVID-19 site column.

**Comment by julia326** [comment]
@kevee @webmasterkai let me know if you want to display anything that you don't currently have enough metadata for, happy to add as needed

**Comment by kevee** [comment]
@julia326 It would be great to reduce file size if there was a cropped/resized version to like 400x400 or something like that. Right now I'm just cropping using a div and `overflow: hidden`

**Comment by kevee** [comment]
Now that I'm thinking about this a big more - should we just add another column to the "History" table that links to the screenshot for that day?

![Sample table](https://user-images.githubusercontent.com/270536/77210404-51234400-6ad7-11ea-8105-f32fefe01fa0.png)

**Comment by kevee** [comment]
Closing, per #79
