### ISSUE TITLE
Byline style issues without Javascript

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#760]
Let us know what the design issue is. Screenshots are helpful!
![image](https://user-images.githubusercontent.com/18607205/80838267-df4e1800-8bb5-11ea-9e2f-9dd93ee78f22.png)

This seems to be rendering in a funky way without Javascript. I'm not totally sure why this is happening, but /shrug/ that's how it goes.

**Comment by jrubenoff** [comment]
@schwartzadev Hmmm, can't seem to reproduce in the latest versions of:

- Chrome or Firefox on Mac
- Edge and Firefox on Windows

If you're still seeing this, what browser / device are you using?

**Comment by schwartzadev** [comment]
Thanks for following up on this @jrubenoff! It looks like it's no longer an issue :thinking: ... not sure why this happened, but I'll take it!
