### ISSUE TITLE
Search: chunked content return multiple results

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#761]
Please let us know the page you are talking about, and your content suggestions!

Here's an example of the issue:
![image](https://user-images.githubusercontent.com/18607205/80838738-ee819580-8bb6-11ea-8f75-26b664f17922.png)

**Comment by kevee** [comment]
I'm going to:

- Add a new field to algolia indexes that links records to each other, using the GraphQL ID. We *could* use slug, but we might have a pattern later on that doesn't have slugs.
- Filter out results with the same ID.
