### ISSUE TITLE
Site Search: UI tweaks + cleanup/bugs

### ISSUE THREAD

**Issue by neeshabeee** [COVID19Tracking/website#764]
**Search box in Nav + Search Results page**

0) Accessibility improvements:
- On mobile, let's make the search field gain focus by default when the user has opened the menu. Basically, we want to remove the step of clicking into the search bar on mobile.
- Make the "Search" text to behave as a label. Remove the placeholder entirely. Below is a screenshot of what "Search" should now look like. The Figma file has also been updated to reflect this change, too.

![image](https://user-images.githubusercontent.com/22971446/81229604-f5d4e480-8fa4-11ea-9d5d-6c9d71197f4e.png)

1) When expanded, the left edge of the search box should align with the left edge of the text of the first listed nav item ("Our Data" in this case). Right now, the search box overshoots this a bit. I found that `width: 28.5rem;` seems to work great.

_This is what it currently looks like:_
![image](https://user-images.githubusercontent.com/22971446/80843819-0e668880-8bba-11ea-9cc9-b917e955c683.png)

2) Currently the X icon to clear a search is veryy close to the magnifying glass icon button - making it too easy to click the wrong thing. This is happening in both the nav + in the Search Results page. Adding 8px to the `padding-right` of the input area would do the trick, for both search boxes. 

_This is what it currently looks like:_
![image](https://user-images.githubusercontent.com/22971446/80844912-b4b38d80-8bbc-11ea-9d19-27820780dbb6.png)

3) Occasionally, I see that the magnifying glass icon with an unexpected color (gray when it should be blue and vice versa). I haven't yet found a way to reliably reproduce this - but will update this when I do. This also happens on the search box on the Search Results page.

_Here is a screenshot from when I got into this state:_
![image](https://user-images.githubusercontent.com/22971446/80842926-bb8bd180-8bb7-11ea-84d8-ff651b94b2e7.png)

4) Occasionally, I see the search box change shape as well. It should retain its rectangular shape.

![image](https://user-images.githubusercontent.com/22971446/80846522-62c13680-8bc1-11ea-8f2c-27e8dc7b1560.png) 

![image](https://user-images.githubusercontent.com/22971446/80846553-7a002400-8bc1-11ea-8b31-5cb4e94362c5.png)

**Autocomplete**

5) Can we hide duplicate options that appear in the autocomplete dropdown?
6) Also, let's add a border around the dropdown box, so it doesn't disappear into the white background below it. We can do `border: 1px solid #676b6d` (this matches the border in the dropdown on the State by State page).

_This is what it currently looks like:_
![image](https://user-images.githubusercontent.com/22971446/80843370-022dfb80-8bb9-11ea-8277-4326aed81964.png)

7) Also, I'm not sure what's causing this, but when I type in "total" into the search box - I see that there's no label above the top 2 autocomplete options.

_Here is a screenshot from when I got into this state:_
![image](https://user-images.githubusercontent.com/22971446/80844057-a3698180-8bba-11ea-9239-eb0eb57530f9.png)

**Comment by superbiche** [comment]
Will be working on it next week unless someone wants to have fun before :)

**Comment by neeshabeee** [comment]
FYI - Updated the list to include additional tweaks that make the search bar more a11y-friendly (bullet #0 at the top). Thanks :)

**Comment by superbiche** [comment]
@neeshabeee all fixed! Will make a PR out of it so you get a review environment.
I didn't know that the label needed to be visible; would be very interested in knowing how it helps a11y for my personal knowledge :)

**Comment by kevee** [comment]
Fixed in #822
