### ISSUE TITLE
Bring back TOC on the main page?

### ISSUE THREAD

**Issue by metasj** [COVID19Tracking/website#765]
As a visitor or to demo the site, I generally visit ct.org and scroll or search the page to find the state I want.  I almost always want one of **US current**, **US historical**, _State_ **current**, or _State_ **historical**.  

* From the **data** page:  I would love a small version of the old TOC visible on the first page, w/o scrolling, both on desktop and mobile.  It would make my quick one-off uses of the site 2x-5x faster, and save scroll fatigue :)
* From the **main** page:  I would love direct links to the same data tabs (_State by State_,
_Totals for the U.S._, _Data API_) that appear once you visit the Data page.

**Comment by kevee** [comment]
Hi, @metasj !

We have big plans for the data page, so I'm going to add this issue to that project when it gets started next week.

This also makes me think maybe we need some kind of dashboard for power users and volunteers. As we add more context and content to guide other users, we might add more interfaces that would be helpful to the public, but less helpful to the folks who are in this data every day.

**Comment by metasj** [comment]
Still keen on this!

**Comment by kevee** [comment]
I think this is more in the context of the internal website tool, which will include a lot of these features.
