### ISSUE TITLE
please add '?date' query string back to All States historical data OR add date:YYYYMMDD field to '/api/v1/states/current.json'

### ISSUE THREAD

**Issue by tomjmcnamee** [COVID19Tracking/website#766]
Prior to 5/1/20, the All States Historical Data accepted a Query String to request only a specific date.  Without that option, your entire States History data set needs to be pulled and parsed on the recipient side to isolate a single date.  Your '/api/v1/states/current.json' route isolates the most recent day's data, but does not hold the date:YYYYMMDD attribute.

My logic relies on this 'date' field to know if I am pulling updated information or not.  I've accounted for this change on my backend by pulling all historic data to verify whether or not the day's data is posted.  No problems here.

For the sake of consistent processing logic between the full data set and 'current' data, please either return the '?date' query string back to the All States Historical Data or add a 'date:YYYYMMDD' attribute to the All States Current schema.
-----------
Thanks for the data and the management of it!  I've been excited about it since releasing this react app in mid-March:  www.covid.tomjmcnamee.com

![image](https://user-images.githubusercontent.com/38674764/80862463-5d0c3500-8c43-11ea-96dc-86cf49227ba8.png)

**Comment by kevee** [comment]
Hi, Tom, you can request a states historic value by day like this:


https://covidtracking.com/api/v1/states/ca/20200403.json

**Comment by tomjmcnamee** [comment]
> Hi, @tomjmcname, you can request a states historic value by day like this:
> https://covidtracking.com/api/v1/states/ca/20200403.json
@kevee - Thank you for the quick reply.  
The route you provided holds data for only a single state+day combo (.../states/<state>/<date>.json).  There is no way to easily target ALL states for a single day.  
Implementing my first suggestion would keep users needing all state data for a single day from pulling the entire dataset OR making 50+ calls to date+state specific routes.

**Comment by kevee** [comment]
Gotcha, then try this:


https://covidtracking.com/api/v1/states/20200404.json

That endpoint is undocumented, I'll make sure it's added to our list.

**Comment by tomjmcnamee** [comment]
Perfect! ...though I'm kinda upset I didn't figure that one out for myself.
Thanks again for the help **and your contributions**!!!
