### ISSUE TITLE
show change rate of new cases

### ISSUE THREAD

**Issue by gciurpita** [COVID19Tracking/website#767]
in addition to map show total number of cases, trend in new cases, red increasing, green decreasing.   7 day average.

would show growth of hot spots

**Comment by kevee** [comment]
Hi, @gciurpita! We have plans to incorporate new interfaces like the ones you described, but right now we're already supporting [lots of other amazing journalists](https://covidtracking.com/about-project/in-the-press) who are doing the exact things you mentioned in.
