### ISSUE TITLE
Add state population data for comparison

### ISSUE THREAD

**Issue by dnspano** [COVID19Tracking/website#771]
Please let us know the page you are talking about, and your content suggestions!
I was comparing your COVID testing tracking data to the most recent population estimates per state, and I believe it's notable to display population information to show the percentage of people who have actually been able to obtain testing at this point. many of the states with the highest amount of testing and confirmed cases also have some of the highest population estimates, which may indicate that, relative to the population, there is still a widely unknown count of positive vs. negative cases. i believe this is not only an important data point to track the virus spread, but will be beneficial to states verifying the need for additional supplies and funding.

**Comment by kevee** [comment]
Hi, @dnspano!
We have plans to incorporate new interfaces like the ones you described, but right now we're already supporting lots of other amazing journalists who are doing the exact things you mentioned in.
