### ISSUE TITLE
Please fix the "Confirmed Cases by Province/State/Dependency" (aka Admin1) view

### ISSUE THREAD

**Issue by kabraha** [COVID19Tracking/website#772]
In the Chrome browser, this section has been showing this error for several days: "Not fully configured" Thanks!

**Comment by kevee** [comment]
Can you provide the URL you are talking about?

**Comment by kabraha** [comment]
https://coronavirus.jhu.edu/map.html

[cid:image001.png@01D6220A.58347AE0]
