### ISSUE TITLE
Replace "Pos + Neg" column with "% New Positive"

### ISSUE THREAD

**Issue by benhalpern** [COVID19Tracking/website#774]
As a user I find the "Pos + Neg" column kind of unimportant because it's always the same value as "Total Tests".

As a proposed replacement, I think a more useful column would be one which tallies the percentage of new tests that day which are positive. This is something I like to tally in order to get a sense for how the virus might be trending.

E.g. on April 15th New York reported 26,869 tests and 11,571 positives (43% new positives that day). On May April 29th, New York reported 27,487 test and 4,585 positives (16% new positives that day).

Since there is currently this doubled-up column I think it could be useful to replace it with something which I think conveys more interesting information at a glance.

**Comment by kevee** [comment]
Thanks, @benhalpern! We're planning a redo of that page, so I'm going to put this issue into a project to track it.

**Comment by thehammah** [comment]
Which field should we use in the load?  ie is there one that will be replaced?

**Comment by kevee** [comment]
Hi, @benhalpern! This is being tracked in our data redesign project, so I'm going to close this ticket.
