### ISSUE TITLE
Large dataset component (John hopkins)

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#776]
Large dataset (John hopkins)
✅ mobile
`components/pages/homepage/large-dataset.js`

**Comment by tealtan** [comment]
Has more to do with the section title above this component:

- [ ] Let’s left-align the section title for now.
- [ ] As on other sections, the section title should be 1.5rem on mobile.

As for this component!
- [ ] Let’s change the font size of the title to 1.5rem on desktop, and keep it as it is for mobile
- [ ] Can we adjust the space below the headline to 0.5rem
- [ ] Can we adjust the paragraph color to `$color-slate-700`?
