### ISSUE TITLE
Press logos

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#780]
✅ mobile

**Comment by tealtan** [comment]
- [ ] Mobile-specific: can we adjust the horizontal margin from 1.8rem to 1rem, and the vertical margin from 3.125rem to 2rem?
- [ ] Mobile-specific: can we adjust the height to 1.5rem?

Otherwise, looks great, thanks!

**Comment by kevee** [comment]
Redid mobile in https://github.com/COVID19Tracking/website/commit/e42c7e9305878c545c25c4e2e01d36034bfca732
