### ISSUE TITLE
Latest totals (What we've tracked so far)

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#781]
`components/pages/homepage/latest-totals.js`
✅ mobile

Latest Data component (Every day...) inc. latest numbers, "see all data" CTA

**Comment by tealtan** [comment]
- [ ] Can we adjust the headline here to be 24px on mobile?
- [ ] We can reduce the padding of each number (the blue box) by half, and if easy, reduce the space between the boxes by half.
- [ ] On mobile, we have some values that are 6rem that I’d like to be 4rem – the classes are `latest-totals-module--container` and `latest-totals-module--header-container--RSYHh`

**Comment by schwartzadev** [comment]
>  Can we adjust the headline here to be 24px on mobile?

Is this the `Every day, our volunteers compile the latest numbers on tests, confirmed cases, hospitalizations, and patient outcomes from every US state and territory.` header or the `Latest totals` one?

**Comment by kevee** [comment]
We already set the header size to 1.5rem/25rem for that "Paragraph" component since it's used elsewhere - is this one supposed to be different?

**Comment by tealtan** [comment]
Ah, that should work! (I meant to say it’s for the `Every day` one.)

**Comment by schwartzadev** [comment]
This one is wrapped up, then!
