### ISSUE TITLE
Historical Data

### ISSUE THREAD

**Issue by DadPlatinum** [COVID19Tracking/website#786]
https://covidtracking.com/data

The page includes a snap shot of current-day data. Some of these data points are not included in the historical data tables. Would it be possible to include the following fields in the historical data for each state (showing N/A if data is not available)?
> Hospitalized (Currently)
> In ICU (Currently)
> On Ventilator (Currently)

**Comment by kevee** [comment]
Hi, @DadPlatinum we have a plan to add this information soon. We haven't included these in the history because it was difficult to provide context. I'm closing this issue, but I have marked it in our project plan.

**Comment by DadPlatinum** [comment]
Kevin,

Thank you for the quick response. Would it possible to notify me when this information becomes available?
