### ISSUE TITLE
Consider making table headers sticky on state pages

### ISSUE THREAD

**Issue by olivierlacan** [COVID19Tracking/website#792]
Right now we have many days listed past the viewport height which results in many columns of data that can be hard to differentiate once headers disappear.

Easy: 
![screenshot of a table including state data with the column headers visible](https://user-images.githubusercontent.com/65950/81123406-016ecf80-8f01-11ea-80c6-89ff3c4fadeb.png)

Hard: 
![screenshot of a table without any headers after scrolling lower on the page](https://user-images.githubusercontent.com/65950/81123439-13e90900-8f01-11ea-99c8-066d41737eaa.png)

I solved this issue on https://o-vid.herokuapp.com/florida with the following CSS code: 

```css
th {
    position: sticky;
    top: 15px;
    background: white;
}
```
![Screen Recording demonstrating table headers sticking to the top of the screen even when scrolling past the original location of headers](https://user-images.githubusercontent.com/65950/81124135-b0f87180-8f02-11ea-876b-8f23b90146cd.gif)

I think it's a fairly cheap solution that provides outsized value.

**Comment by kevee** [comment]
Thanks, @olivierlacan! I just handed this to the table redesign team.

**Comment by kevee** [comment]
After a thorough review, the table team realized that implementing this would be spotty, as [sticky support](https://caniuse.com/#search=position%3A%20sticky) is spotty, and especially with tables there's a lot of examples of them breaking.

However, I'm tagging this in the tables issue to keep track of it. Thanks!
