### ISSUE TITLE
North Carolina - Hospitalized

### ISSUE THREAD

**Issue by airj1012** [COVID19Tracking/website#793]
Hospitalized number is showing at the top for "Currently". But shouldn't it also be listed on the time stamped data, for each day? It seems that Georga and North Carolina have data in one spot but not the other.  Current or time stamp, but not both. However they appear to be similar data sources.

**Comment by airj1012** [comment]
![NC](https://user-images.githubusercontent.com/64874325/81126038-0b480100-8f08-11ea-9620-f9741da4bb87.png)
![GA](https://user-images.githubusercontent.com/64874325/81126042-0e42f180-8f08-11ea-9a17-7586c41ef88d.png)

**Comment by kevee** [comment]
Hi, @airj1012! We are working on a new version of that data page which will include a fix for this issue.
