### ISSUE TITLE
Feature : To add the serious cases(Ventilator and ICU) for the total country as shown for each states.

### ISSUE THREAD

**Issue by devtechnocode** [COVID19Tracking/website#795]
# Feature
 Adding the serious cases(Ventilator and ICU) for the total country as shown for each states on state by state page of our data.

*To show the serious cases as showing postive, negative and deaths.*
 ![Screenshot from 2020-05-06 15-40-32](https://user-images.githubusercontent.com/52890488/81166704-8dd8cb00-8fb1-11ea-9289-fc7c27358738.png)

**Comment by kevee** [comment]
Hi, @devtechnocode thanks for the feature request. We are redoing these pages currently and I'm making sure your request is in our queue.
