### ISSUE TITLE
Feature : To add the column for hospitalized cases for the country as showing for states. 

### ISSUE THREAD

**Issue by devtechnocode** [COVID19Tracking/website#796]
Adding the column for hospitalized cases for the country as showing for states. 

![Screenshot from 2020-05-06 16-08-22](https://user-images.githubusercontent.com/52890488/81168017-d98c7400-8fb3-11ea-830e-3195a15ed273.png)

**Comment by kevee** [comment]
Hi, @devtechnocode thanks for the feature request. We are redoing these pages currently and I'm making sure your request is in our queue.
