### ISSUE TITLE
Photo/illo credit line

### ISSUE THREAD

**Issue by sarawb** [COVID19Tracking/website#801]
We need to be able to credit images, starting with the CRDT illo on the homepage. Standard style for these will be:

> [Creator Name] / COVID Tracking Project
 
For the CRDT image, please use: 

> Mohini Dutta / COVID Tracking Project

**Comment by kevee** [comment]
@schwartzadev  - you want to take this on? We can probably change the blog photo credit to a standard component and use it in both places.
