### ISSUE TITLE
spacing labels and font-sizes top

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#808]
based on feedback we got from the design team, let's: 
- use font-size: 40px for main text and font-size: 18px for chart text 
- add a bit more spacing in the left side of the chart's y-axis labels, so they don't overlap with the chart on smaller sizes. this can also be solved by moving them to the left sooner 

<img width="651" alt="axes-overlapped" src="https://user-images.githubusercontent.com/39416238/81229710-44db4380-8fbe-11ea-95e3-45f563887ef3.png">

cc @tealtan

**Comment by kevee** [comment]
Preview should be in the PR attached to this ticket.
For mobile, I have 30px for main text and 1rem for chart text. Does that sound fine?

I made the y axis switch to the left on large breakpoints, which is when the header element start to stack.
