### ISSUE TITLE
Rename and revise How You Can Help page

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/website#816]
As per @sarawb, we need to change the name of https://covidtracking.com/about-project/help from "How You Can Help" to "Get Involved" to match the call to action in the global header. Maybe also port the slug from /help to /get-involved. We also need to 

- [x] Rewrite copy (see below) 
- [x] Incorporate action form 
- [x] Link to volunteer application form
- [x] Link to Help We Need google doc (could port to web page eventually, but not immediately)

**COPY**
```
**The COVID Tracking Project is a volunteer effort run by passionate citizens from a range of backgrounds. We’d love to have you involved, too.** 

One small way to help? Subscribe to your local newspaper—or a few, if you can. Local reporters paved the way for us to collect our data. If you’re ready to do a little more, here’s how:  

***Ask for better data*** 
Help us ask every state and territory to provide complete data that meets best practices. Sign up and we’ll send you alerts about when and how to contact government officials and public health offices where you live. 

Name
Email 
ZIP code 
Button: Subscribe to action alerts 

***Volunteer*** 
We need volunteers with ongoing time in their schedules to support crucial efforts in a range of fields, from running daily data entry shifts to doing outreach to government bodies to improving our technical infrastructure. 

Our volunteers come from all kinds of backgrounds, and are some of the kindest people we know. If you’re interested: 
[See what kinds of help we need](https://docs.google.com/document/d/11Lw47PuyIjtOMy3XRnLweff7xBjmlxxtqzVQI5cVdcI/edit?usp=sharing)  
[Fill out a volunteer application](http://j.mp/covid-tracking-volunteer)
```
The link to the volunteer application Google form will be replaced by a link to a native form on covidtracking.com once we build that.

**Comment by kevee** [comment]
Where is the form for "advocate for better" data coming from? Is it mailchimp?

**Comment by sarawb** [comment]
> Where is the form for "advocate for better" data coming from? Is it mailchimp?

This is me attempting to pull together multiple things at once into one cohesive thing! Both advocacy and volunteering will be handled on the new shiny Get Involved page, so I wrote copy to bring it all together. 

This form will go to a Mailchimp list. State outreach has an account set up and is almost ready to start sending email. I am meeting with Michale Parks tomorrow to talk through details. I forget what you'll need for the MC integration -- if you let me know I will make sure we get that from him.

**Comment by kevee** [comment]
Thanks! I think they can make an HTML form for the list in mailchimp. Get the form to use and we can style it and add it to the page

**Comment by jurassicparks** [comment]
Kevin -- I'm dropping HTML for the form here. First time using github so please tell me if I'm doing it wrong.

**Comment by jurassicparks** [comment]
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://covidtracking.us4.list-manage.com/subscribe/post?u=0921fdd380ed1e2245d87c3b6&amp;id=14a2b6d1bd" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Subscribe to the COVID Tracking Project Newsletter</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-FNAME">First Name  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="FNAME" class="required" id="mce-FNAME">
</div>
<div class="mc-field-group">
	<label for="mce-LNAME">Last Name  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="LNAME" class="required" id="mce-LNAME">
</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-MMERGE3">Zip Code </label>
	<input type="text" value="" name="MMERGE3" class="" id="mce-MMERGE3">
</div>
<div class="mc-field-group input-group">
    <strong>What kind of information should we send? </strong>
    <ul><li><input type="checkbox" value="1" name="group[69034][1]" id="mce-group[69034]-69034-0"><label for="mce-group[69034]-69034-0">National / general updates</label></li>
<li><input type="checkbox" value="2" name="group[69034][2]" id="mce-group[69034]-69034-1"><label for="mce-group[69034]-69034-1">News specific to my region (zip code required)</label></li>
</ul>
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_0921fdd380ed1e2245d87c3b6_14a2b6d1bd" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[0]='EMAIL';ftypes[0]='email';fnames[3]='MMERGE3';ftypes[3]='zip';}(jQuery));var $mcj = jQuery.noConflict(true);</script>

**Comment by kevee** [comment]
@jurassicparks that looks fine, we can reformat it to match our style and add that extra line.

I'm considering this dependent on #817

**Comment by kevee** [comment]
@sarawb and @jurassicparks - Here's a preview of the page:

https://deploy-preview-849--upbeat-lovelace-3e9fff.netlify.app/about-project/help

I tested it and signed up in Mailchimp.

**Comment by amandafrench** [comment]
The page title should be changed from How You Can Help to Get Involved, and ditto the tab name.

**Comment by amandafrench** [comment]
I think the correct page preview is https://deploy-preview-849--upbeat-lovelace-3e9fff.netlify.app/get-involved
