### ISSUE TITLE
Create new Volunteer Application form

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/website#817]
Related to #816. As per discussions with @sarawb and @kevee, we need a Volunteer Application form to replace our current Google form. Please ping me privately for the group email address the form should be sent to. 

```
**Volunteer for the COVID Tracking Project**
Timestamp*
Name* [short text]

Email* [short text]
_If possible, this should be a Gmail or Google-linked address, since we rely heavily on Google Docs and Sheets. We will show your email internally to other volunteers but will not share it elsewhere._

URL [short text]
Personal website, LinkedIn, or other website that will tell us about you

About how many hours are you available to work?* [dropdown]
- 1-5
- 5-10
- 10-20
- 20-30
- 30-40
- 40+

What time zone are you in?* [dropdown]
- Pacific
- Mountain
- Central
- Eastern
- Other

When are you most available to work?* [checkboxes]
- Morning, some or all weekdays
- Afternoon, some or all weekdays
- Evening, some or all weekdays
- Weekends

Specializations / Skills* [short text]
_Examples: Python, SQL, Tableau, data viz, editing, social media, public health, research, journalism, etc._

What would you like to volunteer to do for us?* [radio buttons]
- I want to help run the whole program by creating high-level policies and services. 
- I want to recruit, train, and manage volunteers. 
- I want to collect COVID data from state websites and data dashboards. 
- I want to collect data about how COVID is affecting communities of color.  
- I want to maintain ratings of the completeness and quality of state COVID data. 
- I want to find COVID data by watching press conferences and monitoring local news sources. 
- I want to contact state governments and other entities for more and better data. 
- I want to write and edit copy for your website. 
- I want to create data visualizations and graphics with your data. 
- I want to design the front end of your website. 
- I want to build the back end functionality of your website. 
- I want to ensure your heavily-trafficked website is fast and reliable. 

I was referred by … [short text]

Why are you interested in volunteering for us? [long text]

**Comment by kevee** [comment]
@friej715 is taking this on later today, here's some notes:

- This should be it's own page under `contact/volunteer`
- Include the Contentful snippet `volunteer-form` on top
- This needs to be a custom form, not use the "contact us" form component 
- Form name should be "volunteer"
- Make sure to wrap the radios with a `<fieldset>` and `<legend>` for a11y

**Comment by amandafrench** [comment]
Thanks, guys! Sorry it took me so long to review this. There have been some changes to the process logic that require some changes to the form. Which is good, because we are making it simpler! This whole question & its responses: 

```
What would you like to volunteer to do for us?* [radio buttons]
- I want to help run the whole program by creating high-level policies and services. 
- I want to recruit, train, and manage volunteers. 
- I want to collect COVID data from state websites and data dashboards. 
- I want to collect data about how COVID is affecting communities of color.  
- I want to maintain ratings of the completeness and quality of state COVID data. 
- I want to find COVID data by watching press conferences and monitoring local news sources. 
- I want to contact state governments and other entities for more and better data. 
- I want to write and edit copy for your website. 
- I want to create data visualizations and graphics with your data. 
- I want to design the front end of your website. 
- I want to build the back end functionality of your website. 
- I want to ensure your heavily-trafficked website is fast and reliable. 
```
needs to be changed to 

```
What would you like to volunteer to do?* [radio buttons]
- I'd like to help compile and analyze your data.
- I'd like to help design and build your website. 
- I'd like to help write content, monitor news sources, and do original journalism.
- I'd like to help with program management, project management, and/or community management.

**Comment by amandafrench** [comment]
I have a question about routing, as well. I'd like one copy of all application responses to go to a single group email address and a single Slack channel, but I'd also like applications to be routed to four *different* group email addresses and four related Slack channels based on the user's response to the above question about what they want to volunteer to do. Is this possible? We had discussed doing this via Front as per #818 but I think I'd rather avoid that if we can. I could also use Zapier for some of this routing, most likely.

**Comment by kevee** [comment]
@friej715 can you add this to the PR?

**Comment by amandafrench** [comment]
If you can't get to it, @friej715, I think I can hack it out myself in the next day or two

**Comment by friej715** [comment]
@amandafrench oops should have tagged this issue—already pushed a commit that should update these options 👍

**Comment by amandafrench** [comment]
Oh hey awesome thanks @friej715!

**Comment by amandafrench** [comment]
I do also have a new email address the form should be sent to -- is there a demo version I could try, as well? I went to the "deploy preview" on the PR but didn't see the new form.

**Comment by amandafrench** [comment]
New form launch will also require small text / link changes to https://covidtracking.com/get-involved btw

**Comment by amandafrench** [comment]
Namely: remove "See what kinds of help we need" link & text and change link URL on "Fill out a volunteer application" to the URL of the form (or else embed the form on the Get Involved page)

**Comment by friej715** [comment]
@amandafrench got it, I'll get on that now!

The new form lives [here](https://deploy-preview-831--upbeat-lovelace-3e9fff.netlify.app/contact/volunteer). I think all the Netlify stuff is in a testable place, right @kevee?

**Comment by friej715** [comment]
I'll also tweak the "(required)" text on the new volunteer form page to match how it looks on the Get Involved page.

**Comment by friej715** [comment]
Oh wait, I think those links are in Contentful and have to be changed there. In any case, the new form currently lives at `/contact/volunteer`.

**Comment by amandafrench** [comment]
Appreciate your working on this boring thing, @friej715! 🥇  I made some small but necessary changes to the language in a new PR of my own. Other needed changes: 

1. The preview form linked above says ```Want to volunteer for the COVID Tracking Project? We’d love to have you. Please take a moment to learn more about about our workstreams and current needs for help.``` I couldn't find where in the code that was, but if it's still in there somewhere the whole third sentence and its link should be removed. That makes the correct text ```Want to volunteer for the COVID Tracking Project? We’d love to have you.```

2. The email output from the demo form is messy -- will attach screenshot and add you to the Google Group and the Slack channel where I'm testing this so you can see and test yourself. 

<img width="589" alt="Screenshot 2020-05-26 08 53 37" src="https://user-images.githubusercontent.com/227453/82903194-9bd59800-9f2e-11ea-8821-7a753331a2fc.png">

**Comment by kevee** [comment]
Closing per #926
