### ISSUE TITLE
Switch to standard bullet alignment

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#82]
I know we've talked about this for the next design pass but our data guys are extremely brain-itchy about it. @beep could you take a look at this when next you pass by and LMK if it's quick enough to just do?

**Comment by hammer** [comment]
also there's a weird amount of vertical spacing on https://covidtracking.com/software, for example.

**Comment by beep** [comment]
Thanks, folks! Let me know how #85 looks to you?

> also there's a weird amount of vertical spacing on https://covidtracking.com/software, for example.

I think #85’ll help with this, but let me know!

(That said, one of the issues on that page is markdown-related, not CSS-related: each top-level title is getting wrapped in a `p`, which is causing the extra space.  I’ve put in a _very_ hacky fix for this, but hopefully it’ll be short-lived.)
