### ISSUE TITLE
Bring the search autocomplete to mobile

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#825]
Let's bring the search autocomplete to mobile devices. Some things to keep in mind:

- The current `Combobox` portal needs to be positioned better and not cover mobile.
- Let's keep the portal attached to the menu so the menu goes up and down to match content. Maybe?

**Comment by superbiche** [comment]
I'm working on it, I think this can be added to #822 .

**Comment by superbiche** [comment]
Done

**Comment by kevee** [comment]
Fixed in #822
