### ISSUE TITLE
add margin and move "are" on homepage 

### ISSUE THREAD

**Issue by julialedur** [COVID19Tracking/website#832]
@superbiche pointed out that the hero is a bit crowded in a specific size on his computer: 

![image (13)](https://user-images.githubusercontent.com/39416238/81483328-64b37700-920b-11ea-9e6b-171c1d126e8c.png)

- let's move the "are." to the previous sentence so it's not lost in its own line. 
- let's add a bit of margin in between the two bits of text.

**Comment by superbiche** [comment]
Fixed in the PR :point_up:
