### ISSUE TITLE
JS flash on time zones on state data pages

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#847]
On state data pages, it looks like we're adjusting the timestamp ("Last updated: Tue May 12 2020 6:00 am EDT" or whatever, screenshot for clarity but it's not a GIF so it doesn't really show the issue) client-side again, which seems maybe not great?

<img width="389" alt="Screenshot 2020-05-12 17 37 25" src="https://user-images.githubusercontent.com/1910034/81758719-7e58f680-9477-11ea-9d03-6dc05d6d9725.png">

**Comment by kevee** [comment]
Confirmed that the date is coming out in EDT and then being overwritten to local time by the client. I'm on it.
