### ISSUE TITLE
CDC testing numbers on home page - citing source? 

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/website#850]
This seems like a pretty urgent change we should make based on updates the CDC made yesterday.

On the home page at https://covidtracking.com/ we make the claim that "CDC numbers don't tell the full story. Their official count shows 558,293 tests to date across the US. Using a rigorous data-collection process, we've counted 9,637,930 tests." I expected to find a link in that paragraph to the CDC data I could click to verify that claim, or else a linked footnote, but there isn't one. 

When I searched for how many tests the CDC is currently reporting, I found this page https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/testing-in-us.html which says it was last updated May 12 (yesterday). It is reporting a number much closer to ours: **9,724,879.** That might not be an "official" count? Not sure, because I don't know where the 558,293 issue comes from. There's also now the COVID Data Tracker at https://www.cdc.gov/covid-data-tracker/index.html which is also reporting the 9 million number.

Yesterday they apparently moved their old page with testing results to https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/previous-testing-in-us.html and that might be the source of the lower number.

**Comment by kevee** [comment]
The data on that chart is all tests confirmed from that "previous testing" page. I think we need to have a discussion about that new testing page and what it means.
