### ISSUE TITLE
Data page: table headers overlap the sticky “Totals by State” bar

### ISSUE THREAD

**Issue by beep** [COVID19Tracking/website#853]
**Describe the bug**
The positioned [table headers on the data page](https://covidtracking.com/data) seems to be overlapping the sticky “Totals by State” menu bar. Here’s a screencap:

<img width="1170" alt="Screen Shot 2020-05-13 at 1 44 24 PM" src="https://user-images.githubusercontent.com/124493/81846428-0d214e00-9520-11ea-8c7c-da1c450fdb40.png">

Seems like a real minor stacking bug; applying `z-index: 1` to the state-nav-header component fixed it for me!

**Comment by kevee** [comment]
Thanks, @beep, I love having a simple issue today!
