### ISSUE TITLE
Blog tables weird on smaller screens/windows

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#858]
We have a beautiful new table in here thanks to @kevee https://covidtracking.com/blog/antibody-data-reporting

…but it seems to get weird and very wide at smaller widths, which throws off the rest of the page as well. Any ideas?

**Comment by schwartzadev** [comment]
(related: the `line-height` for `th`s is less than one, which makes them rather _smooshed_.  When this gets fixed, let's also bump that up to at least 1, maybe 1.15.)

Example:
![image](https://user-images.githubusercontent.com/18607205/81996797-3b2f8c80-960b-11ea-942f-6232e6f9fda7.png)
