### ISSUE TITLE
Many pages are missing top-level subtitles

### ISSUE THREAD

**Issue by lucasgonze** [COVID19Tracking/website#86]
For a page like https://covidtracking.com/data/, there is a page title in the content, like "Most Recent Data", but not at the window level. In HTML the window title is the element html.head.title. 

For example, the window-level title for that "Most Recent Data" page is the same as for every other page on the site: "The COVID Tracking Project":

![Screen Shot 2020-03-20 at 12 29 00](https://user-images.githubusercontent.com/111581/77199702-81062380-6aa6-11ea-8e4a-8716ff4d31cb.png)

What it *should* be is "The COVID Tracking Project - Most Recent Data"

**Comment by beep** [comment]
Thanks, @lucasgonze. I’m not sure I have the nunjucks skills for this one. More specifically, I think I can figure this out for _most_ pages, but I’m not sure how to handle the individual state pages: they’re not passing a `title` variable to the base template.

**Comment by lucasgonze** [comment]
@beep Do you agree this is a good thing to change?

**Comment by lucasgonze** [comment]
@webmasterkai Are you a good owner for this development work?

**Comment by beep** [comment]
@lucasgonze oh _absolutely_ agree it’s a good thing to change! I just don’t know how to implement it myself—sorry!

**Comment by olivierlacan** [comment]
I can tackle this if @webmasterkai is out.
