### ISSUE TITLE
Tables: mobile stacked variant

### ISSUE THREAD

**Issue by superbiche** [COVID19Tracking/website#860]
[This new blog post from Erin & Quang](https://covidtracking.com/blog/antibody-data-reporting) uses the new Table component - it's the same table component as before, but in Contentful.

But this `contentful` (pun intended) table, in smaller layouts, is rendered in a way that makes it hard to read:  

![image](https://user-images.githubusercontent.com/2478146/82002957-78be0500-965f-11ea-89c3-6dff4e60aee1.png)

Allen worked on a Table component variant that would stack on smaller layouts:  
![image](https://user-images.githubusercontent.com/2478146/82003048-adca5780-965f-11ea-9c5d-e4b31b9ebd3f.png)
[Here's the Figma mockup](https://www.figma.com/file/fKUKsYMNw3NLSyIEOI1HKc/v2-refresh?node-id=1575%3A10275)  

@kevee : We'll need your help to duplicate the component in Contentful - no difference with the table you created this week, just find a proper name for it :)

To do: 

- [x] Create the Contentful table component  
- [ ] Code the stacked table component  
- [ ] Make sure it stacks properly **only on small layouts**
- [ ] Change the line-height to `1.4` **on all layouts but only on blog tables**

**Comment by kevee** [comment]
Good point, @superbiche! I know the folks in the web table group have been gearing up for stacked mobile tables, but I think these content-only tables are safe to play with.

**Comment by kevee** [comment]
So the Contentful table component is just an embedded entity with markdown, since they don't have a built-in tool for that.

However, we can do stacking with just CSS! The component and it's SCSS module is at: `/src/components/pages/blog/table-content-block.js`

**Comment by kevee** [comment]
Closing per #990
