### ISSUE TITLE
🐛 CSV/JSON files are unlabelled, unclear what data it is

### ISSUE THREAD

**Issue by tatianamac** [COVID19Tracking/website#864]
Page: [Data API, endpoints](https://covidtracking.com/api#endpoints)

## Expected Behaviour
The ability to tab through links and know where they go without digging for more info using my screen reader (SR). 

## Actual Behaviour
In the area with all the JSON/CSV files, if I'm navigating using a SR and tabbing through links, it will repeatedly announce "JSON" and "CSV" without the visual context of what's on the list at left.

## Recommendation
Add an `aria-label` to the link that describes what it says to the left: "JSON representation of current state data" This way, a SR user will be able to tab through or collect all links and receive the same context as a sighted user.

## Additional Resources
[ARIA8 aria-labelled](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA8.html)
[Deque: Text link Accessibility](https://www.deque.com/blog/text-links-practices-screen-readers/)

**Comment by kevee** [comment]
I think the page is fixed now, please double-check for me.

**Comment by kevee** [comment]
Links look good now, closing!

**Comment by tatianamac** [comment]
Hiya! sorry I didn't see this alert come through. Minor things: The first JSON link says "curren" and the last link says CSV format instead of version like the rest.

**Comment by kevee** [comment]
Thanks for the catch! Done!
