### ISSUE TITLE
Dates / times not rendering in IE

### ISSUE THREAD

**Issue by ctp-support** [COVID19Tracking/website#875]
From support email:
> When looking at the historical data and last updated date I continue to get “Invalid date”??  Please help.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_23zgx)

**Comment by jdmaresco** [comment]
Second email:
> I was viewing in IE and tried in Chrome and the dates are working there.  Maybe just an IE thing??  Link is https://covidtracking.com/data

![image004](https://user-images.githubusercontent.com/1327983/82262665-53671a80-992f-11ea-9de7-6d341f9f1c5b.jpg)

**Comment by kevee** [comment]
Also issue in Safari 9
