### ISSUE TITLE
CRDT Dashboard: Place percentages side by side

### ISSUE THREAD

**Issue by tatianamac** [COVID19Tracking/website#881]
## Expected Behaviour
For percentages to display side by side if horizontal space exists

## Actual Behaviour
Percentages stack, even when there is room to accommodate forcing extra scroll; it also makes it harder to tell what the second number represents.

<img width="433" alt="image" src="https://user-images.githubusercontent.com/7484549/82348663-0a09e000-99ae-11ea-8b4c-dd2f80a74655.png">

## Recommended Fix
Switch to `flex-direction: row`. Even at its best, which will be 100% (the most number of characters to accommodate, it will still fit)

<img width="435" alt="image" src="https://user-images.githubusercontent.com/7484549/82348534-dc249b80-99ad-11ea-83f3-39856d9d6f8f.png">

## Specs
[MyBrowser.fyi](https://mybrowser.fyi/report/5ec3fefeeed0a90015359c00)

**Comment by schwartzadev** [comment]
Can do! Would you like to keep the `column` behavior for the US overviews? (This uses the same base component.)

Here's the current display on mobile:
![image](https://user-images.githubusercontent.com/18607205/82355634-b86a5100-99bf-11ea-95b1-02ba822cc606.png)

**Comment by tatianamac** [comment]
Ah I should have guessed they were the same! 

Another suggestion so that we can maintain the same behaviour is to instead keep each state as its own row, but flip the number and "of" clause to being columns for smaller widths, like so:
<img width="434" alt="image" src="https://user-images.githubusercontent.com/7484549/82356859-0d569900-99b9-11ea-8399-1950668a7a39.png">

(Instead of what I have, we would top-align the text, though).

**Comment by tatianamac** [comment]
Also, I know this is bad issues-practice, but while you are in there, could you please make it "of cases" and  "of deaths"? It's currently missing visually.
