### ISSUE TITLE
Enable UNFURL when sharing page(s) on social media

### ISSUE THREAD

**Issue by heyheatherirene** [COVID19Tracking/website#888]
Would be cool to unfurl website links, so we have some visual to accompany direct links. This is especially evident, given the new white paper. May need to open another ticket to ensure proper graphic is ready for unfurling.

**Comment by schwartzadev** [comment]
This is in progress:
Plan:
* Use the current share image as the default and add specific images as needed.
* Use the below image for CRDT pages
![CRDT no logo](https://user-images.githubusercontent.com/18607205/83314244-cfd2e680-a1d6-11ea-9aeb-ac8e14cf8a3d.png)
