### ISSUE TITLE
CRDT Dashboard: Extra space between data and descriptor

### ISSUE THREAD

**Issue by tatianamac** [COVID19Tracking/website#892]
## Expected Behaviour
No space between number of states reporting and the descriptor

## Actual Behaviour
<img width="647" alt="image" src="https://user-images.githubusercontent.com/7484549/82478151-583de280-9a85-11ea-92fd-c492aca63a2e.png">

## Recommended Fix
Omit extra <br>

## Specs
https://mybrowser.fyi/report/5ec56a0bcabf07001531559b

**Comment by kevee** [comment]
Good catch! Prettier had wiped those spaces, so I forced them back in.
