### ISSUE TITLE
CRDT Dashboard: Toggle behaviour is unclear

### ISSUE THREAD

**Issue by tatianamac** [COVID19Tracking/website#895]
## Expected Behaviour
Toggle for the 🚩 and the 🔵 to either be independent, or connected.

## Actual Behaviour
When you click on one to expand, and go to click the other one, it closes the first one instead of opening the second one.

I can't upload a video here but I can share it with you if helpful.

**Comment by kevee** [comment]
That's a known issue, should be fixed soon.

**Comment by sarawb** [comment]
Additional toggle issue: Looks like the see why for the red flag is no longer functioning at all.

**Comment by kevee** [comment]
@tatianamac I think this is fixed, the toggles will close the other toggle if it's already expanded now.
