### ISSUE TITLE
CRDT Dashboard: Superscript annotation anchor link behaviour is unclear

### ISSUE THREAD

**Issue by tatianamac** [COVID19Tracking/website#896]
## Expected Behaviour
For anchor links to be clear what they're jumping me to.

## Actual Behaviour
For clear "jumping" down to whatever section I'm supposed to have, perhaps with a corresponding header?

Right now, it jumps me down somewhere, but I honestly can't tell where and what I'm supposed to read?

**Comment by kevee** [comment]
@tatianamac - the anchors were broken to notes, and I believe this issue was fixed in https://github.com/COVID19Tracking/website/commit/a8c3be0d2af690c251d5305f7794ece8641e5530#diff-6cd599bc8dfc2ae13bae13a3a6277532

**Comment by kevee** [comment]
I did more!

- Made the notes link to the header above the notes
- Prevent the anchor from being hidden by the sticky search bar
- Gave notes header better context for AT (read as "Notes [on race/ethnicity] for [state]
