### ISSUE TITLE
Copy edits - racial data dashboard 

### ISSUE THREAD

**Issue by sarawb** [COVID19Tracking/website#897]
- [x] Add "Here's" to first sentence of headline so it is "Here's the latest..." 
- [x] After the headline, we are missing all of the body copy for the intro section: 

> This dashboard includes topline data from our complete race and ethnicity dataset, which is updated twice per week. 
>
> This data is presented alongside corresponding population data for each racial or ethnic group from the Census Bureau’s 2018 ACS 5-Year estimates. Note that we have used standard Census categories for race and ethnicity throughout this dashboard, but many states are currently reporting their data using non-standard categories. 
> 
> See our full dataset as a [spreadsheet](https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vTfUQPxkhP_CRcGmnnpUBihnTNZ9Z8pcizII4_sc2o2n3opOoAJdAM4CRTJBI339tou8LWnQrqbTMgH/pubhtml#) or [CSV](https://docs.google.com/spreadsheets/d/e/2PACX-1vTfUQPxkhP_CRcGmnnpUBihnTNZ9Z8pcizII4_sc2o2n3opOoAJdAM4CRTJBI339tou8LWnQrqbTMgH/pub?gid=902690690&single=true&output=csv).

- [x] - Header for Race and Ethnicity Data by State should be sentence case
- [x] - Purple box text -- change "The following charts" to "The following data tables" 
- [x] - In text above % for states that have race/ethnicity combined, change racial to race so it reads "[State] has reported race and ethnicity data for:" 
- [x] - Percentage of cases/deaths columns for states that do not report -- eg, "Alabama does not report Race data"  and "Alabama does not report Ethnicity" -- no capitalization on race or on ethnicity 
- [x] - Percentage of deaths column for states that do not report -- this is showing the case content, the content here should instead say, "[State] does not report race data for deaths. Help us get better data.
- [x] - Change header on notes areas from Value notes to just Notes

**Comment by sarawb** [comment]
Noting that the copy has changed to "Arkansas does not report race data for deaths that are not deaths." but should say "Arkansas does not report race data for deaths."

**Comment by sarawb** [comment]
First item was not completed: 

Add "Here's" to first sentence of headline so it is "Here's the latest..."

**Comment by kevee** [comment]
Fixed in https://github.com/COVID19Tracking/website/commit/7f26ff119af7f2fe8d390809fa3f83bc0f8ba6ee
