### ISSUE TITLE
Racial data dashboard accessibility review items

### ISSUE THREAD

**Issue by toddparker** [COVID19Tracking/website#899]
URL tested:
https://feature-crdt-dashboard--upbeat-lovelace-3e9fff.netlify.app/race/dashboard

Looked at in Safari, FF and Chrome with VoiceOver and NVDA

- [x] **State input needs a visible focus state**

<img width="259" alt="image" src="https://user-images.githubusercontent.com/359929/82490535-6b66a780-9ab1-11ea-9887-97b55c819610.png">

Seems this rule from the header should just be scoped more broadly

<img width="516" alt="image" src="https://user-images.githubusercontent.com/359929/82490891-e465ff00-9ab1-11ea-88c8-bf50269470d2.png">

So it looks like this:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/359929/82490982-0bbccc00-9ab2-11ea-8efe-0615de86e1b6.png">

- [x] **Turn off [autocomplete](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion) for the state search** by adding `autocomplete="false"` to the `input` or `form`. In Chrome, when I focus in the input and haven't yet entered a letter, I see Chrome's suggestions of saved phone numbers and states _over_ the menu

<img width="451" alt="image" src="https://user-images.githubusercontent.com/359929/82488098-58ea6f00-9aad-11ea-9997-1374efe91424.png">

- [ ] **This ID isn't unique**
<img width="715" alt="image" src="https://user-images.githubusercontent.com/359929/82487520-723eeb80-9aac-11ea-91ac-66f583d806fc.png">

- [x] **There isn't any spacing between this text and the box** at this breakpoint (visual QA)

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/359929/82486447-d8c30a00-9aaa-11ea-884e-96a03a7a5bbf.png">

- [x] **Design feedback**: when I first looked at this page, I thought the tables within each state were accidentally repeated because the heading text is very similar and we bury the lede a bit by having the unique thing in the middle:

**Race data** reported by Arkansas
**Ethnicity data** reported by Arkansas

I wonder if the percentage reporting data could be downplayed a tiny bit, it seems to chunk this into 4 sections when there are just 2, each with a reporting %.

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/359929/82489097-1033b580-9aaf-11ea-9fd3-92a70596b16b.png">

Something to think about, not critical....

- [x] There are a bunch of complaints about using `role="text"` in the headers but I think @beep added that to help it [read back smoothly](https://axesslab.com/text-splitting/)? Seems like a case of practicality over purity so I'm good with keeping until Apple fixes things on VO

<img width="195" alt="image" src="https://user-images.githubusercontent.com/359929/82487197-0d839100-9aac-11ea-8cdc-6865f1c805d2.png">

**Comment by kevee** [comment]
@beep did let us know about role. I'm considering that a tooling issue.

**Comment by tealtan** [comment]
Yep, exactly – role="text" we intentionally added to improve readability.
