### ISSUE TITLE
Provide simple visualizations, link to existing ones in the meantime

### ISSUE THREAD

**Issue by nealmcb** [COVID19Tracking/website#91]
Thanks for this project!

Adding visualizations and the ability to query and drill down into the data would be very handy. E.g. I'd love to see a time series plot of the [daily data](https://github.com/COVID19Tracking/covid-tracking-data/blob/master/data/states_daily_4pm_et.csv) for just one state or one outcome (`positive` or `death` or whatever).

Until that is available, thanks for linking via Twitter to one visualization website for this data:
* [The COVID Tracking Project on Twitter: "Finally, though we have not pushed visualizations to the site, volunteers are beginning to work with the data like Willem Botha's quick dashboard" / Twitter](https://twitter.com/COVID19Tracking/status/1237859685761343489)

That one is great because it shows barcharts of data over time per state. That site is:
* [Workbook: COVID19 in USA](https://public.tableau.com/views/COVID19inUSA/COVID-19spreadinUSA?:display_count=y&:origin=viz_share_link&:showVizHome=no) - Tableau Public Site

I've seen the URL fail a few times with a warning from Tableau, but if it remains stable, you might want to list it from the website.

For comparison, I also note some other visualizations, which as far as I've seen don't provide the ability to drill down to a region and see a time series for just that area:
* [Coronavirus COVID\-19 \(2019\-nCoV\)](https://www.arcgis.com/apps/opsdashboard/index.html?fbclid=IwAR3RSuNS3OZQy2av-BZrucFDd-uqr-kodqBZVobJz2_R9GjuhFhK3cu8-_A#/bda7594740fd40299423467b48e9ecf6) from the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University (JHU) based on their data at [CSSEGISandData - COVID-19 - github](https://github.com/CSSEGISandData/COVID-19)
* [Coronavirus Cases: Statistics and Charts \- Worldometer](https://www.worldometers.info/coronavirus/coronavirus-cases/#case-dayly-outchina)

**Comment by joshuaellinger** [comment]
moved from the general issues to web site.

**Comment by on2air** [comment]
I run an agency around Airtable and decided to pull in your data to Airtable which is pretty good data visualization: https://airtable.com/shrGZit91PisYqpdM/tblvj81hpMq0uZ1FB/viw7h7DDzmL0u4q5p?blocks=bipNeGkkQAz6fvcaA&bip=full

Feel free to share.  It requires a code snippet on my end to run each day and pull in your updates that I'll try to keep updated.

**Comment by nealmcb** [comment]
@on2air Cool - thanks!  Nice stacked bars etc.
But you seem to be showing cumulative sums of values that are already cumulative totals-to-date.

**Comment by on2air** [comment]
ah thanks @nealmcb . I've updated to calculate daily numbers. should be reflected now

**Comment by theojulienne** [comment]
https://covid.graphics/country/usa.html (and sub-state pages) are now pulling the wonderful (:heart: :heart: thank you!) data provided from the API here for US states over the top of JHU CSSE data for the rest of the world.

**Comment by nealmcb** [comment]
Note the excellent visualization project now at https://github.com/COVID19Tracking/covid-tracking-dash

I'd love to see it provide derivatives: daily increments for each parameter, especially for the hospitalization data, as noted at [How to fight the coronavirus SARS-CoV-2 and its disease, COVID-19 Michael Lin, PhD-MD](https://drive.google.com/file/d/1ZaiDO87me4puBte-8VytcSRtpQ3PVpkK/view)

**Comment by MrSteve2** [comment]
@nealmcb  are you looking for something like they talk about on slides 14/15 "Estimated 5% of total infected (not diagnosed cases) require hospitalization"  Ie Chart positives / hospitalizations?
Like this for NY
![visualization-1](https://user-images.githubusercontent.com/4956801/77989060-d84c9500-72eb-11ea-92c7-726e1dbfec3b.png)

I can quickly create Vega/Vegalite versions that could be auto-generated and could be used to insert into your website. IE, if there is anything I can do to help, let me know.

**Comment by nealmcb** [comment]
@MrSteve2 Thanks for the offer!
I'm looking at page 15:
> The next few weeks are critical: We must do whatever we can to reduce R0 or
increase doubling time. Social distancing efforts in CA started 3/20. Since
cases are undercounted, we will only know if efforts are working by looking
at weekly hospitalization trends 2–3 weeks later (4/10).

> If hospitalizations are still doubling each week on 4/10, we have only another
3 weeks to get a second chance.

> If that doesn’t work by 5/1, there will be no third chance. We would have to
immediately clamp down to avoid hospital overflow. This would require
Wuhan-like measures such as central quarantine for sick and enforced
home-isolation for everyone.

So they aren't tracking the ratio of positives / hospitalizations. They don't trust the data on testing since the criteria for and availability of tests varies over time. They see the hospitalization data as more reliable over time. So just plotting the API column `hospitalizedIncrease` by day would show if social distancing is flattening that curve.  Lots of folks are already plotting some of the other columns by day, and I think plotting all the `...Increase` values would be helpful, and especially `hospitalizedIncrease`.

**Comment by MrSteve2** [comment]
@nealmcb I'll see what I can do.  
I also found this site: https://covid19.healthdata.org/projections
Which has hospital data on (bed and ICU occupancy, and ventilator use).

**Comment by MrSteve2** [comment]
OKay I graphed all the data items and added a dropdown to select state.
Check https://mrsteve2.github.io/covidTrackingViz.github.io/covidCharts.html

Let me know if the increase graphs were what you were looking for.

**Comment by nealmcb** [comment]
Thanks, MrSteve2. Those look good! If they were smaller, or combined in cases where the scales are amenible, we could see more of it at once. And I'd put the state selector a the top.

Can the code for that be integrated with the project and dash?

I'll also note a few other links to visualizations that I've been collecting:

* covid.graphics: https://covid.graphics/country/usa.html
* COVID on Worldmapper: https://worldmapper.org/?s=covid
* Coronavirus Deaths by U\.S\. State and Country Over Time: Daily Tracker \- The New York Times: https://www.nytimes.com/interactive/2020/03/21/upshot/coronavirus-deaths-by-country.html

**Comment by MrSteve2** [comment]
> Thanks, MrSteve2. Those look good! If they were smaller, or combined in cases where the scales are amenible, we could see more of it at once. And I'd put the state selector a the top.
Agreed. Just wanted to do first step and create.  UX design is needed
> 
> Can the code for that be integrated with the project and dash?
> 
Yes. Its a simple matter of programming :)  Do you have a particular project(s) I can clone and page/pages you would like to see them integrate with? If so let me know and I will take a look at what it will take.

> I'll also note a few other links to visualizations that I've been collecting:
> 
>     * covid.graphics: https://covid.graphics/country/usa.html
> 
>     * COVID on Worldmapper: https://worldmapper.org/?s=covid
> 
>     * Coronavirus Deaths by U.S. State and Country Over Time: Daily Tracker - The New York Times: https://www.nytimes.com/interactive/2020/03/21/upshot/coronavirus-deaths-by-country.html
Thanks will check and perhaps do a review of them to determine what we can learn and what we should steal (with credits of course)

**Comment by phact** [comment]
I made this viz based on the John's Hopkins data, would be happy to contribute something similar if there is interest.

https://covid-19-keppler.netlify.com/
