### ISSUE TITLE
Flash of unstyled menu when loading page

### ISSUE THREAD

**Issue by jdmaresco** [COVID19Tracking/website#910]
Observed: Brief flash of unstyled content on menu on race page, when opening on mobile

To get here I clicked on a link posted in slack and observed the page inside the slack-embedded web browser 

I was able to reproduce this happen occasionally, about 15-20% of the time

![25C81EAF-5094-4D96-B6C0-F75AB3EDA4C2](https://user-images.githubusercontent.com/1327983/82576898-3e210480-9b58-11ea-84f7-cb7c60080c7c.png)

**Comment by kevee** [comment]
That's our JS-disabled backup menu, I'll hide it for mobile.
