### ISSUE TITLE
"not comparable" / "disparity likely" dialogs inaccessible without Javascript

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#911]
**Describe the bug**

## Current behavior
I hate for Javascript to be My Thing, _but_... There is currently no way to view these dialogs without using Javascript.

![image](https://user-images.githubusercontent.com/18607205/82581754-483e0580-9b4e-11ea-9390-4de1c13b8c3d.png)
(Open links are highlighted)

### Reproduction
1. Disable JS
2. Go to https://covidtracking.com/race/dashboard
3. Click on either `See why ↓` span

## Suggested behavior (1)
These links (`See why ↓`) could link to a `#key` element at the bottom of the page, with the un-collapsed notes.

We could also pair this with a link at the top/in the hero about "what does 🔵 and 🚩 mean?"

### Drawbacks
There wouldn't be a great way to return to the state from which you jumped to the bottom of the page

## Suggested behavior (2)
Both dialog could be displayed below the key, for every state.

### Drawbacks
This would be super repetitive.

**Comment by kevee** [comment]
Good catch! We have the special `.js-disabled` classes - how about we use that to put a link next to these that got to the bottom of the page with a description?
