### ISSUE TITLE
Erroneous 'defer' attribute in html source?

### ISSUE THREAD

**Issue by weatherman0516** [COVID19Tracking/website#917]
At the very end of the html code for each data page (states and us totals) there's a 'defer' attribute just before the </script> tag without any value after it.

**Comment by tsargent** [comment]
I think that's actually valid. It's just the boolean defer attribute for the script tag: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

I believe it's valid to set a boolean attribute to true by assigning it to an empty string: 
https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes

**Comment by weatherman0516** [comment]
Interesting. 

I assumed it was in error because I was getting the following error using Google Apps Script

![image](https://user-images.githubusercontent.com/63274008/82740546-c7326a00-9d17-11ea-9773-b22dc6f34eef.png)

Using the following line of code...

`XmlService.parse(page).getRootElement()`

**Comment by kevee** [comment]
Hi, @weatherman0516!

I'm closing this, @tsargent is correct, empty attributes are valid in the HTML spec. The XmlService is for XML documents, not HTML. I think there's an HTML parsing service in apps script as well.

However, if you're trying to parse our data using apps script, I'd suggest just [checking out our API!](https://covidtracking.com/api)
