### ISSUE TITLE
Contentful cleaning options?

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#918]
I've noticed double spaces between words in some blog posts, and some spaces trailing paragraphs.

Would it be appropriate to clean contentful fields (or maybe just blog content fields) to stop these double/trailing space from hitting the website?

On the other hand, I totally understand if this is overstepping from a content side of things. I'll defer to @sarawb on this.

**Comment by sarawb** [comment]
I am trying to imagine a situation where this goes wrong, and I can't quite think of one! I'd say, let's do it for blog content fields, where we definitely don't have any purposeful double-spaces.
