### ISSUE TITLE
Clarify "Our Data" Menu Text

### ISSUE THREAD

**Issue by amberwojcek** [COVID19Tracking/website#929]
When redesigning menu, consider changing "Our Data" text to "Data by State" to navigate where current "Our Data" is - or adding additional clickable tab from drop down with "state". 

I personally can never find the data by state page because of this - I think the possessive "our data" implies to me that that page will explain how the data is captured or something to that nature.

Additionally, would recommend anchor links or a way to scroll to the state or letter (click K to scroll to Kansas, for instance) to make the page easier to navigate.

Long-long-long term, may consider giving each state a dedicated page to also notate news/updates over time.

**Comment by kevee** [comment]
Fixed in #932
