### ISSUE TITLE
Check in on a nav thing

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#932]
The new subnav is extremely rad, and this is a fairly small thing, but it seems important, so I wanted to raise it. I think the links to the landing pages are sometimes getting lost when people pop open the dropdowns. My biggest concern is that the state-by-state/main data page is getting missed, here:

<img width="378" alt="Screen Shot 2020-05-26 at 8 51 50 PM" src="https://user-images.githubusercontent.com/1910034/82975958-bd686b00-9f92-11ea-8414-a1b01ad402f6.png">

I've had conversations with a couple different people about it as they click around looking for things, and I think there's enough of a usability problem to warrant thinking through some lightweight solutions.

**Comment by kissane** [comment]
I think https://github.com/COVID19Tracking/website/issues/929 provides some related, useful usability notes—Amber's been working on the project for awhile and missed that state pages exist, for example. Stuff for the longer-term hopper.

**Comment by kevee** [comment]
We had a discussion early on about just putting a link to the top-level landing page on the top of the dropdowns as well.

![image](https://user-images.githubusercontent.com/270536/83005233-8cae2300-9fde-11ea-8f61-d4e79bc5feca.png)

**Comment by kissane** [comment]
@kevee I think we should do it—it's redundant, but much better to be a little redundant than to lose people looking for the top level info. (We fielded another inquiry last night about why we removed the main data page, argh.)

**Comment by kevee** [comment]
OK I Added State data to the top of that nav group. Closing this and #929

**Comment by kissane** [comment]
Oh gah, I literally could have just done that! Sorry. I opened this to get overall feelings on the nav stuff, though, rather than to point and dictate the one thing—sorry about that, I think GH issues must not be the right place for that.

**Comment by realfuture** [comment]
Nonetheless, I do think the nav is a wee bit confusing, as it currently stands. This is not my specialty, so I cannot point to a solution, but I do think Erin has ID’d a legit problem.
