### ISSUE TITLE
Convert all import statements to use aliases

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#933]
Change all the `import` statements to use import aliases, i.e. `~components/something` instead of `../../../components/something`

Now that we are using the [Gatsby import alias](https://www.gatsbyjs.org/packages/gatsby-plugin-alias-imports/) plugin (thanks, @superbiche!), we can use the following import aliases instead of all those dots:

```
 src/components, → ~components
 src/context, → ~context
 src/data, → ~data
 src/images, → ~images
 src/pages, → ~pages
 src/scss, → ~scss
 src/templates, → ~templates
 src/utilities → ~utilities

```

**Comment by goldfarb** [comment]
@kevee will the `__test__` files automatically update or should I update the import statements for those files as well?
