### ISSUE TITLE
Document repository

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#934]
Let's make it easy to post documents like PDFs to the website, giving each document a "landing page" and short URL:

Kevin can make the content type in Contentful, which will have:

- [x] Document name
- [x] Description (markdown)
- [x] Slug (url)
- [x] Document 

We then:

- [x] Pull that list of documents in `gatsby-node.js`. For example, [how we do it with content pages](https://github.com/COVID19Tracking/website/blob/master/gatsby-node.js#L77).
- [x] Write a template for the documents
- [x] Build document pages. Use the url `/document/[slug]`

**Comment by schwartzadev** [comment]
I can give this a shot! @kevee can you please let me know once the content is set up in Contentful?

**Comment by kevee** [comment]
OK I made a `Document` content type in Contentful and added the CDC paper.

**Comment by schwartzadev** [comment]
Exciting, thank you!

When you mention `Write a template for the documents`, do you imagine a page that then links to the document, or just the document itself?

(If the case is the former, do we have a design for that landing page?)
