### ISSUE TITLE
CRDT note field changes

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#939]
Make all the note fields the same in states combined and separate in the CRDT data.

## Field changes 
Change definitions in 

- [x] `gatsby-node.js`
- [ ] the GraphQL query in `/src/components/pages/race/dashboard/states.js`

The following columns will no longer exist in “FlattenedTable1”: (states combined)

- [x] blackANHPINotes	
- [x] asianANHPINotes
- [x] aianANHPINotes
- [x] nhpiANHPINotes
- [x] twoANHPINotes
- [x] whiteANHPINotes
- [x] otherANHPINotes

The following columns will now exist in “FlattenedTable1: (states combined)

- [x] blackANHPIPosNotes	
- [x] blackANHPIDeathNotes
- [x] asianANHPIPosNotes
- [x] asianANHPIDeathNotes
- [x] aianANHPIPosNotes
- [x] aianANHPIDeathNotes
- [x] nhpiANHPIPosNotes
- [x] nhpiANHPIDeathNotes
- [x] twoANHPIPosNotes
- [x] twoANHPIDeathNotes
- [x] whiteANHPIPosNotes
- [x] whiteANHPIDeathNotes
- [x] otherANHPIPosNotes
- [x] otherANHPIDeathNotes

**Comment by schwartzadev** [comment]
Hey Kevin -- for the combined query, I'm finding `latinXANHPINotes` as well. Should I eliminate this field as well, or just the ones that you shared?

Also, it looks like you checked off updating `gatsby-node.js`  -- which branch was that on?

**Comment by kevee** [comment]
I'd say eliminate the field. I was working in `kevee/crdt-field-changes` - feel free to take it over!
