### ISSUE TITLE
State Search on Data Page Error

### ISSUE THREAD

**Issue by amberwojcek** [COVID19Tracking/website#944]
I'm accessing https://covidtracking.com/data on my phone (Chrome on Android, Pixel 3) and the state search function isn't responding. I both began typing my state's name and then selected it from the drop down, and separately just scrolled down the dropdown until I found it. It selects the name but doesn't scroll to the anchor. 
![Screenshot_20200528-083946](https://user-images.githubusercontent.com/65978267/83146757-bb062e00-a0c4-11ea-81d5-7f424e262f82.png)

**Comment by kevee** [comment]
Fixed in #948
