### ISSUE TITLE
Social cards in Contentful

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#955]
Let's manage our social cards in Contentful.

- [x] Add social card content type to Contentful with name, slug, image, and description
- [x] Add field to pages in Contentful that relates to social cards
- [x] Let the  `SEO` components accept a `socialCard` prop type that represents a card object.
- [x] The `Layout` component should have `socialCard` that it passes to SEO
- [x] The `src/templates/content.js` template should query for socialCard of pages and pass the card through that prop
- [x] Handle social cards from blog posts
- [x] Pages like `src/pages/race.js` can query for that card directly, just like we do with snippets, and pass the card object to `socialCard`
- [x] Remove the older `description` prop from `Layout` and it's use in a few pages along the site.
- [x] Replace pages that used description with references to social cards in Contentful
- [x] Test with both [FB's sharing debugger](https://developers.facebook.com/tools/debug/) and the [Twitter card validator](https://twitter.com/login?redirect_after_login=https%3A%2F%2Fcards-dev.twitter.com%2Fvalidator)

**Comment by schwartzadev** [comment]
Re: migrating the description prop: these pages will be affected.

 - src/pages/race/dashboard.js
 - src/templates/blog-post.js
 - src/pages/contact/index.js
 - src/pages/data/index.js
 - src/pages/data/us-daily.js
