### ISSUE TITLE
Apply new focus style for links across the site:

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#967]
Let's make focus style consistent across the site [to match this figma file](https://www.figma.com/file/meG3i5VlD94qrTylsqZUXL/Library?node-id=28%3A2)

- [x] Create a links.module.scss file in `/src/scss`
- [x] Add mixins for hover and focus
- [x] Apply mixins to links generally
- [x] Apply mixin to CTA links, press links, all the header and footers for focus

**Comment by schwartzadev** [comment]
(noting this for myself): fix the focus state for `class: navigation-module--caret`
