### ISSUE TITLE
API became case sensitive

### ISSUE THREAD

**Issue by ctp-support** [COVID19Tracking/website#976]
Reported via support email

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_24hjl)

**Comment by jdmaresco** [comment]
Excerpt:

> I've been using https://covidtracking.com/api/v1/states/OR/daily.json for a few days, but it's now returning a 404. I had to switch to a lowercase or to get data back (https://covidtracking.com/api/v1/states/or/daily.json).

**Comment by kevee** [comment]
The case-insensitive URLs was an accident, we never supported upper-case URLs, since the HTTP spec is that URLs should be case-sensitive. I updated the docs in the API site that lower-case is specified.
