### ISSUE TITLE
"States" Refactor to "States and Territories"

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#98]
This should be pretty simple: the Project currently always refers to states _and_ territories as simply "states"

For example, on the `/us-daily/` page, the table indicates that 56 states are tracked while this includes N. Mariana Islands, Guam, Washington D.C., and others:
![image](https://user-images.githubusercontent.com/18607205/77234265-8e88df80-6b72-11ea-85e4-f1e0aa4aca42.png)

I'm not sure how many instances there are where we use this phrasing, but I think it should be revised.

**Comment by hammer** [comment]
For sure! We did not change the sheet as we were afraid to break things that depended on column names. Can definitely make the change on the website.
