### ISSUE TITLE
Auto-resize blog images

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#980]
@tealtan I'm putting this here as a placeholder for our [Slack discussions](https://covid-tracking.slack.com/archives/C010N48RY73/p1591299656198300) about image sizes.

Once you know what we're looking for, please share :arrow_down: :thread:

**Comment by tealtan** [comment]
Hurrah, thank you!

We are going to have a target width of 2000px for blog posts, and then generate/optimize smaller sizes:

500, 1000, 1500, 2000 ?

(@schwartzadev please weigh in on what you think is a good balance of having a wide enough set of sizes while not adding too much to the build process.)

**Comment by tealtan** [comment]
And I guess there isn’t really a reason to limit it to blog images only, right? We could do this for all images?

**Comment by schwartzadev** [comment]
I believe we could, yes. @kevee would know more: Could we use a snippet to handle this for all images?

**Comment by kevee** [comment]
You can resize images from Contentful using [GraphQL queries that automatically make srcsets](https://www.gatsbyjs.org/docs/working-with-images/), and 4 sets of sizes is totally fine!

We are already doing this with the CRDT and homepage images, also using SVG placeholders as well.

**Comment by tealtan** [comment]
🤯
