### ISSUE TITLE
Design system: Spacing 

### ISSUE THREAD

**Issue by kevee** [COVID19Tracking/website#985]
[Figma file](https://www.figma.com/file/meG3i5VlD94qrTylsqZUXL/Library?node-id=1%3A238)

Feature branch: `feature/style-system-1`

To-do:

- [x] Create variables for pre-defined spacing units
- [x] Add mixins for using spacing in padding & margin
- [x] Update all the padding and margins across all components.
- [x] Document special use-cases where margin or padding doesn't fit our defined spaces.

**Comment by superbiche** [comment]
Around 50% done, will finish later this weekend. 
When I'm leaving custom spacers or I'm not sure about the changes I've added a `// STYLE CHECK` comment so we can quickly decide on what to do with these exceptions.

**Comment by kevee** [comment]
Closed in #1023
