### ISSUE TITLE
Add Terms & Conditions

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#986]
Hello! [Here are the final terms and conditions](https://docs.google.com/document/d/10X7xCzUjblIkVT6xys54QYdNFxxvxU0Bwj0HjvnLV_g/edit?usp=sharing) from the friendly lawyers at The Atlantic. We need to make it a page and add it to the footer nav on the CTP site, and I would love to know how to do that.

**Comment by kevee** [comment]
Let's make this a page in Contentful, and we can add the link to the footer after it's published.

**Comment by kissane** [comment]
Great, I can do the first part now!

**Comment by kissane** [comment]
Should be live at https://covidtracking.com/terms-and-conditions on the next build.
