### ISSUE TITLE
Update Typo CI Ignore

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#995]
Let's add the following to the Typo CI ignore file:
* `nhpi`
* `aian`

**Comment by dileep-g** [comment]
Hi @schwartzadev, Please have a look at the [PR to fix this](https://github.com/COVID19Tracking/website/pull/998), . I added above words to list of words to exclude in a PR. This is my firs time contributing to the COVID19Tracking project and I apologize for any misunderstanding. Happy to be corrected.

**Comment by schwartzadev** [comment]
Closed by #998
