### ISSUE TITLE
Handle footer on midsize viewports

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#996]
With the new T+C link in the footer, we're having some clash at some viewport widths. Here's 814px wide.
![image](https://user-images.githubusercontent.com/18607205/83976218-e8698d80-a8b5-11ea-8780-28da2d9608ea.png)

In this case, let's:
* add right spacing to the logo
* justify the footer links

Once we drop below 768px, like this:
![image](https://user-images.githubusercontent.com/18607205/83976266-32eb0a00-a8b6-11ea-942c-1b8ffe8a82e4.png)

...let's also justify the links

**Comment by tiagofsanchez** [comment]
Hi @schwartzadev, I have added the spacing (not entirely sure what you mean by justify the links) however, I still don't have permission to the project. Can you or @kevee add me?

**Comment by schwartzadev** [comment]
Hey @tiagofsanchez, thanks for helping out!

Here's [a doc on justifying flex content](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Aligning_Items_in_a_Flex_Container). This would entail:

- setting `display: flex` on the ul
- setting `flex-wrap: wrap;` on the ul
- setting `justify-content: center;` on the ul

Nobody has permission to push to the master branch since we use a pull request system for all contributions. You should be able to make a pull request to the master branch, and we can then review the changes there. Let me know if you have any questions!

**Comment by Melvin-Viana** [comment]
Took a stab at this issue, one of my first Open-Source Contributions.

Any feedback is welcome.
https://github.com/COVID19Tracking/website/pull/1005

**Comment by kevee** [comment]
@tiagofsanchez added you to the team!
