### ISSUE TITLE
"Tests" & "Cases" usage on website

### ISSUE THREAD

**Issue by amandafrench** [COVID19Tracking/website#997]
I noticed Thursday night that the website uses the term “tests” when it should use “cases." Our published “Positives” number for every state includes both people who have tested positive for COVID and people who have not been tested. Usually the latter are people who have been diagnosed with COVID-19 because they’ve got all the symptoms and are known to have been in contact with someone who did test positive for it. 

So, for instance, the current published version of the spreadsheet lists 20,500 in the "Positive" column for AL. 

<img width="399" alt="Screenshot 2020-06-07 19 45 16" src="https://user-images.githubusercontent.com/227453/83982808-8893d680-a8f7-11ea-8135-8e6d6657f57a.png">

The Data page at http://covidtracking.com/data lists this "Positive" number under a header called "Tests | Positive":

<img width="1212" alt="Screenshot 2020-06-07 20 02 24" src="https://user-images.githubusercontent.com/227453/83983115-d6a9d980-a8f9-11ea-82c0-f529d60d8b5a.png">

Which is also the way it is presented on Alabama's state page at https://covidtracking.com/data/state/alabama

But what the number actually represents is Positive *cases* of COVID-19, meaning people who have COVID-19, whether they've been tested for it or whether they have just been diagnosed with it by a doctor, usually because (as I mentioned above) they have all the symptoms and have been in contact with someone who *has* tested positive for COVID-19. This is clear in the column title of the sheet we work in: 

<img width="1201" alt="Screenshot 2020-06-07 20 00 31" src="https://user-images.githubusercontent.com/227453/83983087-95192e80-a8f9-11ea-8ca1-21a971441c5c.png">

And you can see that Alabama reports these numbers separately on its data dashboard:

<img width="1026" alt="Screenshot 2020-06-07 19 58 14" src="https://user-images.githubusercontent.com/227453/83983099-b24dfd00-a8f9-11ea-8d0b-33e84b553aa4.png">

We have been tracking which cases are confirmed and which are "probable" separately, but for now only the "lumped" Positives number is published, and that number includes cases of people who have COVID-19 but have not received a diagnostic test.

**Comment by goldfarb** [comment]
@amandafrench Should the header on the state history table also be `New Cases` instead of `New Tests`?

![image](https://user-images.githubusercontent.com/3722037/83983419-44570500-a8fc-11ea-84fa-c3299f978997.png)

**Comment by kissane** [comment]
Oh wow, exciting. I think "positives" **strongly implies a positive test result**, not a clinically diagnosed case. So this is something we should probably untangle further back from the website.

**Comment by kissane** [comment]
("Positive cases" is not a thing I think the CDC uses, for instance.)

**Comment by kissane** [comment]
I see that the CDC does talk about "presumptive positive cases," but agh, "positives" seems so ambiguous here to me, considering our readership(s).
